// packages/epicenter-vue-components/src/components/empty-state/EpEmptyState.vue
<template>
  <div :class="['ep-empty-state', classes]">
    <div
      v-if="$slots.img"
      class="ep-empty-state__img"
    >
      <!-- @slot Image or icon to display in the empty state -->
      <slot name="img" />
    </div>
    <div class="ep-empty-state__body">
      <!-- @slot Main content/message of the empty state -->
      <slot />
      <div
        v-if="$slots.subtext"
        class="text--subtle font-size--small"
      >
        <!-- @slot Additional descriptive text or instructions -->
        <slot name="subtext" />
      </div>
      <div
        v-if="$slots.cta"
        class="ep-empty-state__body__cta"
      >
        <!-- @slot Call-to-action button or link -->
        <slot name="cta" />
      </div>
    </div>
  </div>
</template>

<script setup>
  import { computed } from 'vue'

  defineOptions({
    name: 'EpEmptyState',
  })

  const props = defineProps({
    /**
     * Layout direction of the empty state content.
     * @values 'column', 'row'
     */
    direction: {
      type: String,
      default: 'column'
    },
    /**
     * Horizontal alignment of the content.
     * @values 'left', 'center', 'right'
     */
    justify: {
      type: String,
      default: 'center'
    },
  })

  const classes = computed(() => {
    return {
      'ep-empty-state--column': props.direction === 'column',
      'ep-empty-state--row': props.direction === 'row',
      'ep-empty-state--justify-left': props.justify === 'left',
      'ep-empty-state--justify-right': props.justify === 'right',
    }
  })
</script>

// packages/epicenter-components-react/src/components/empty-state/EpEmptyState.tsx
import React, { ReactNode } from 'react'

export interface EpEmptyStateProps {
  /**
   * Main content/message of the empty state
   */
  children?: ReactNode
  /**
   * Call-to-action button or link
   */
  cta?: ReactNode
  /**
   * Layout direction of the empty state content.
   * @default 'column'
   */
  direction?: 'column' | 'row'
  /**
   * Image or icon to display in the empty state
   */
  img?: ReactNode
  /**
   * Horizontal alignment of the content.
   * @default 'center'
   */
  justify?: 'left' | 'center' | 'right'
  /**
   * Additional descriptive text or instructions
   */
  subtext?: ReactNode
}

export const EpEmptyState: React.FC<EpEmptyStateProps> = ({
  direction = 'column',
  justify = 'center',
  img,
  children,
  subtext,
  cta
}) => {
  const classes = [
    'ep-empty-state',
    direction === 'column' && 'ep-empty-state--column',
    direction === 'row' && 'ep-empty-state--row',
    justify === 'left' && 'ep-empty-state--justify-left',
    justify === 'right' && 'ep-empty-state--justify-right'
  ].filter(Boolean).join(' ')

  return (
    <div className={classes}>
      {img && (
        <div className="ep-empty-state__img">
          {img}
        </div>
      )}
      <div className="ep-empty-state__body">
        {children}
        {subtext && (
          <div className="text--subtle font-size--small">
            {subtext}
          </div>
        )}
        {cta && (
          <div className="ep-empty-state__body__cta">
            {cta}
          </div>
        )}
      </div>
    </div>
  )
}
