// packages/epicenter-vue-components/src/components/map/EpMap.vue
<template>
  <div
    ref="epMapContainer"
    class="ep-map-container"
  >
    <div id="ep-map" />
  </div>
</template>

<script setup>
  import { ref, nextTick, onMounted, onBeforeUnmount, watch } from 'vue'
  import 'mapbox-gl/dist/mapbox-gl.css'

  defineOptions({
    name: 'EpMap',
  })

  const props = defineProps({
    accessToken: {
      type: String,
      required: true
    },
    mapCenter: {
      type: Array,
      default: () => [-122.3321, 47.6062]
    },
    mapZoom: {
      type: Number,
      default: 12
    },
    mapStyle: {
      type: String,
      default: 'mapbox://styles/mapbox/streets-v11'
    },
    mapSource: {
      type: Object,
      default: null
    },
    mapLayer: {
      type: Object,
      default: null
    },
    pinLocations: {
      type: Array,
      default: () => []
    },
    scrollZoom: {
      type: Boolean,
      default: true
    },
    navigationControl: {
      type: Boolean,
      default: true
    },
    fitToBounds: {
      type: Boolean,
      default: false
    }
  })

  const emit = defineEmits(['centerChange', 'dropPin', 'zoomChange'])

  const init = ref(true)
  const map = ref(null)
  const markers = ref([])
  let mapboxgl = null

  watch(() => props.mapCenter, (newCenter) => {
    emit('centerChange', newCenter)
    flyTo(newCenter, props.mapZoom)
  })

  watch(() => props.mapZoom, (newZoom) => {
    emit('zoomChange', newZoom)
    flyTo(props.mapCenter, newZoom)
  })

  watch(() => props.mapStyle, (newStyle) => {
    map.value.setStyle(newStyle)
  })

  watch(() => props.pinLocations, () => {
    removeMarkers()
    addMarkers()
  })

  watch(() => props.scrollZoom, (newScrollZoom) => {
    if (newScrollZoom) {
      map.value.scrollZoom.enable()
    } else {
      map.value.scrollZoom.disable()
    }
  })

  // get a reference to the parent container
  const epMapContainer = ref(null)

  // create a new ResizeObserver instance
  const observer = new ResizeObserver(() => {
    if (map.value) {
      // Ensure map.value is initialized before calling resize
      nextTick(() => {
        map.value.resize()
      })
    }
  })

  onMounted(() => {
    loadMap().then(() => {
      // map layer
      if (props.mapSource) addSource(props.mapSource, props.mapLayer)
      // fit to bounds
      if (props.fitToBounds) {
        fitBounds(getBounds(props.mapSource.source.data.geometry.coordinates))
      }
      // if pin locations exist, add them
      if (props.pinLocations.length) addMarkers()
      init.value = false
    })

    // attach the observer to the container
    observer.observe(epMapContainer.value)
  })

  onBeforeUnmount(() => {
    observer.disconnect()

    if (map.value) {
      if (map.value.getLayer('test')) map.value.removeLayer('test')
      if (map.value.getSource('test')) map.value.removeSource('test')
      map.value.remove()
    }
  })

  const loadMap = () => {
    return new Promise((resolve) => {
      // Perform the dynamic import and other async operations
      import('mapbox-gl').then((module) => {
        mapboxgl = module.default
        map.value = new mapboxgl.Map({
          accessToken: props.accessToken,
          container: 'ep-map',
          center: props.mapCenter,
          zoom: props.mapZoom,
          style: props.mapStyle,
        })

        // Various options
        if (!props.scrollZoom) map.value.scrollZoom.disable()
        if (props.navigationControl) map.value.addControl(new mapboxgl.NavigationControl())

        map.value.on('load', () => resolve())
        map.value.on('dragend', onDragEnd)
      })
    })
  }

  const addMarkers = () => {
    props.pinLocations.forEach((location) => {
      const marker = new mapboxgl.Marker().setLngLat(location).addTo(map.value)
      markers.value.push(marker)
    })
  }

  const removeMarkers = () => {
    markers.value.forEach((marker) => marker.remove())
    markers.value = []
  }

  const flyTo = (center = props.mapCenter, zoom = props.mapZoom) => {
    map.value.flyTo({
      center,
      zoom
    })
  }

  const onDragEnd = () => {
    const center = map.value.getCenter()
    emit('centerChange', [center.lng, center.lat])
  }

  const getBounds = (coordinates) => {
    return coordinates.reduce(
      (bounds, coord) => bounds.extend(coord),
      new mapboxgl.LngLatBounds(coordinates[0], coordinates[0])
    )
  }

  const fitBounds = (bounds) => {
    map.value.fitBounds(bounds, {
      linear: false,
      duration: 1000,
      padding: 60
    })
  }

  const addSource = (source, layer) => {
    map.value.addSource(source.id, source.source)
    map.value.addLayer(layer)
  }
</script>

// packages/epicenter-components-react/src/components/map/EpMap.tsx
import React, { useEffect, useRef, useState } from 'react'

export interface PinLocation {
  lat: number
  lng: number
}

export interface MapSource {
  id: string
  source: any
}

export interface EpMapProps {
  /** Mapbox access token (required) */
  accessToken: string
  /** Additional CSS classes */
  className?: string
  /** Fit map to bounds of source data */
  fitToBounds?: boolean
  /** Map center coordinates [lng, lat] */
  mapCenter?: [number, number]
  /** Map layer configuration */
  mapLayer?: any
  /** Map source configuration */
  mapSource?: MapSource | null
  /** Mapbox style URL */
  mapStyle?: string
  /** Map zoom level */
  mapZoom?: number
  /** Show navigation control */
  navigationControl?: boolean
  /** Callback when center changes */
  onCenterChange?: (center: [number, number]) => void
  /** Callback when pin is dropped */
  onDropPin?: (location: PinLocation) => void
  /** Callback when zoom changes */
  onZoomChange?: (zoom: number) => void
  /** Array of pin locations to display */
  pinLocations?: PinLocation[]
  /** Enable scroll zoom */
  scrollZoom?: boolean
}

/**
 * EpMap - Mapbox GL wrapper component
 * 
 * Interactive map with pin markers, custom layers, and navigation controls.
 * Automatically resizes with container using ResizeObserver.
 */
export const EpMap: React.FC<EpMapProps> = ({
  accessToken,
  mapCenter = [-122.3321, 47.6062],
  mapZoom = 12,
  mapStyle = 'mapbox://styles/mapbox/streets-v11',
  mapSource = null,
  mapLayer = null,
  pinLocations = [],
  scrollZoom = true,
  navigationControl = true,
  fitToBounds = false,
  onCenterChange,
  onZoomChange,
  className = ''
}) => {
  const mapContainerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<any>(null)
  const markersRef = useRef<any[]>([])
  const mapboxglRef = useRef<any>(null)
  const [init, setInit] = useState(true)

  // Load map
  useEffect(() => {
    const loadMap = async () => {
      const mapboxgl = (await import('mapbox-gl')).default
      await import('mapbox-gl/dist/mapbox-gl.css')
      mapboxglRef.current = mapboxgl

      if (!mapContainerRef.current) return

      mapRef.current = new mapboxgl.Map({
        accessToken,
        container: mapContainerRef.current,
        center: mapCenter,
        zoom: mapZoom,
        style: mapStyle
      })

      // Various options
      if (!scrollZoom) mapRef.current.scrollZoom.disable()
      if (navigationControl) mapRef.current.addControl(new mapboxgl.NavigationControl())

      mapRef.current.on('load', () => {
        // map layer
        if (mapSource) addSource(mapSource, mapLayer)
        // fit to bounds
        if (fitToBounds && mapSource) {
          fitBoundsToSource(getBounds(mapSource.source.data.geometry.coordinates))
        }
        // if pin locations exist, add them
        if (pinLocations.length) addMarkers()
        setInit(false)
      })

      mapRef.current.on('dragend', () => {
        const center = mapRef.current.getCenter()
        onCenterChange?.([center.lng, center.lat])
      })
    }

    loadMap()

    return () => {
      if (mapRef.current) {
        removeMarkers()
        if (mapRef.current.getLayer('test')) mapRef.current.removeLayer('test')
        if (mapRef.current.getSource('test')) mapRef.current.removeSource('test')
        mapRef.current.remove()
      }
    }
  }, [])

  // Watch for map center changes
  useEffect(() => {
    if (!init && mapRef.current) {
      onCenterChange?.(mapCenter)
      flyTo(mapCenter, mapZoom)
    }
  }, [mapCenter])

  // Watch for map zoom changes
  useEffect(() => {
    if (!init && mapRef.current) {
      onZoomChange?.(mapZoom)
      flyTo(mapCenter, mapZoom)
    }
  }, [mapZoom])

  // Watch for map style changes
  useEffect(() => {
    if (!init && mapRef.current) {
      mapRef.current.setStyle(mapStyle)
    }
  }, [mapStyle])

  // Watch for pin location changes
  useEffect(() => {
    if (!init && mapRef.current) {
      removeMarkers()
      addMarkers()
    }
  }, [pinLocations])

  // Watch for scroll zoom changes
  useEffect(() => {
    if (!init && mapRef.current) {
      if (scrollZoom) {
        mapRef.current.scrollZoom.enable()
      } else {
        mapRef.current.scrollZoom.disable()
      }
    }
  }, [scrollZoom])

  // Resize observer
  useEffect(() => {
    if (!mapContainerRef.current || !mapRef.current) return

    const observer = new ResizeObserver(() => {
      if (mapRef.current) {
        setTimeout(() => {
          mapRef.current.resize()
        }, 0)
      }
    })

    observer.observe(mapContainerRef.current)

    return () => {
      observer.disconnect()
    }
  }, [init])

  const addMarkers = () => {
    if (!mapboxglRef.current || !mapRef.current) return
    pinLocations.forEach((location) => {
      const marker = new mapboxglRef.current.Marker()
        .setLngLat([location.lng, location.lat])
        .addTo(mapRef.current)
      markersRef.current.push(marker)
    })
  }

  const removeMarkers = () => {
    markersRef.current.forEach((marker) => marker.remove())
    markersRef.current = []
  }

  const flyTo = (center = mapCenter, zoom = mapZoom) => {
    if (mapRef.current) {
      mapRef.current.flyTo({ center, zoom })
    }
  }

  const getBounds = (coordinates: number[][]) => {
    if (!mapboxglRef.current) return null
    return coordinates.reduce(
      (bounds, coord) => bounds.extend(coord),
      new mapboxglRef.current.LngLatBounds(coordinates[0], coordinates[0])
    )
  }

  const fitBoundsToSource = (bounds: any) => {
    if (mapRef.current && bounds) {
      mapRef.current.fitBounds(bounds, {
        linear: false,
        duration: 1000,
        padding: 60
      })
    }
  }

  const addSource = (source: MapSource, layer: any) => {
    if (mapRef.current) {
      mapRef.current.addSource(source.id, source.source)
      if (layer) mapRef.current.addLayer(layer)
    }
  }

  return (
    <div className={`ep-map${className ? ` ${className}` : ''}`}>
      <div ref={mapContainerRef} className="ep-map__canvas" />
    </div>
  )
}
