// packages/epicenter-components-react/src/components/code-view/EpCodeView.tsx
import React, { useEffect, useState } from 'react'

export interface EpCodeViewProps {
  /** Additional CSS classes */
  className?: string
  /** The code to display */
  code: string
  /** The language of the code */
  language: string
  /** The theme to use for highlighting */
  theme?: string
}

/**
 * EpCodeView - Syntax-highlighted code viewer
 * 
 * Uses Shiki for syntax highlighting with customizable themes.
 */
export const EpCodeView: React.FC<EpCodeViewProps> = ({
  code,
  language,
  theme = 'one-dark-pro',
  className = ''
}) => {
  const [highlightedCode, setHighlightedCode] = useState('')

  useEffect(() => {
    const highlightCode = async () => {
      try {
        const { codeToHtml } = await import('shiki')
        const html = await codeToHtml(code, {
          lang: language,
          theme: theme,
          colorReplacements: {
            '#282c34': 'var(--interface-surface)'
          }
        })
        setHighlightedCode(html)
      } catch (error) {
        console.error('Error highlighting code:', error)
        // Fallback to plain text
        setHighlightedCode(code)
      }
    }

    highlightCode()
  }, [code, language, theme])

  return (
    <div
      className={`ep-code-view${className ? ` ${className}` : ''}`}
      dangerouslySetInnerHTML={{ __html: highlightedCode }}
    />
  )
}

// packages/epicenter-components-vue/src/components/code-view/EpCodeView.vue
<script setup lang="ts">
  import { codeToHtml } from 'shiki'
  import { computed, onMounted, onUpdated, ref } from 'vue'

  interface Props {
    code: string
    language: string
    theme?: string
  }

  const {
    code,
    language,
    theme = 'one-dark-pro',
  } = defineProps<Props>()

  defineOptions({ name: 'EpCodeView' })

  const highlightedCode = ref('')
  const highlightedSignature = ref('')
  const highlightSignature = computed(() => `${language}::${theme}::${code}`)

  const highlightCode = async (): Promise<void> => {
    const signature = highlightSignature.value

    if (highlightedSignature.value === signature) return

    highlightedSignature.value = signature

    try {
      highlightedCode.value = await codeToHtml(code, {
        lang: language,
        theme: theme,
        colorReplacements: {
          '#282c34': 'var(--interface-surface)',
        }
      })
    } catch (error) {
      console.error('Error highlighting code:', error)
      highlightedCode.value = code
    }
  }

  onMounted(() => {
    void highlightCode()
  })

  onUpdated(() => {
    void highlightCode()
  })
</script>

<!-- eslint-disable vue/no-v-html -->
<template>
  <div
    class="ep-code-view"
    v-html="highlightedCode"
  />
</template>
