// packages/epicenter-components-react/src/components/range-input-filter/EpRangeInputFilter.tsx
import React, { forwardRef, useState, ChangeEvent } from 'react';

export interface EpRangeInputFilterProps {
  [key: string]: unknown;
  appliedFilters: Record<string, unknown>;
  className?: string;
  columnKey: string;
  filterKey: string;
  max: number;
  min: number;
  onChange?: (filters: Record<string, number>) => void;
  value?: number;
}

export const EpRangeInputFilter = forwardRef<
  HTMLInputElement,
  EpRangeInputFilterProps
>(
  (
    {
      columnKey,
      min,
      max,
      value,
      onChange,
      className = '',
      ...props
    },
    ref
  ) => {
    const [selectedRange, setSelectedRange] = useState(value ?? 0);

    const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
      const newValue = Number(e.target.value);
      setSelectedRange(newValue);
      onChange?.({ [columnKey]: newValue });
    };

    return (
      <div className={`ep-range-input-filter ${className}`.trim()}>
        <input
          ref={ref}
          type="range"
          min={min}
          max={max}
          value={selectedRange}
          onChange={handleChange}
          {...props}
        />
        <span>{selectedRange}</span>
      </div>
    );
  }
);

EpRangeInputFilter.displayName = 'EpRangeInputFilter';

// packages/epicenter-vue-components/src/components/table/EpRangeInputFilter.vue
<template>
  <div>
    <input
      v-model="selectedRange"
      type="range"
      :min="min"
      :max="max"
      @input="applyFilter"
    >
    <span>{{ selectedRange }}</span>
  </div>
</template>

<script setup>
  import { ref } from 'vue'

  const props = defineProps({
    appliedFilters: {
      type: Object,
      required: true
    },
    filterKey: {
      type: String,
      required: true
    },
    columnKey: {
      type: String,
      required: true
    },
    min: {
      type: Number,
      required: true
    },
    max: {
      type: Number,
      required: true
    }
  })

  // Initialize selected range
  const selectedRange = ref(0)

  // Method to apply filter and emit event
  const applyFilter = () => {
    // Emit event to update applied filters in parent component
    emit('update:appliedFilters', { [columnKey]: selectedRange.value })
  }
</script>
