// packages/epicenter-components-react/src/components/table/EpTablePagination.tsx
import React, { useMemo } from 'react'

import { EpButton } from '../button/EpButton'
import { EpFlex } from '../flexbox/EpFlex'
import { EpFooter } from '../footer/EpFooter'
import { EpSelect } from '../select/EpSelect'

export interface EpTablePaginationProps {
  /** Additional CSS classes */
  className?: string
  /** Current page number */
  currentPage: number
  /** Callback when page changes */
  onPageChange: (page: number) => void
  /** Callback when results per page changes */
  onResultsPerPageChange: (value: number) => void
  /** Results per page */
  resultsPerPage: number
  /** Show individual page buttons */
  showPages?: boolean
  /** Total number of pages */
  totalPages: number
}

const resultsPerPageOptions = [
  { label: '10', value: 10 },
  { label: '20', value: 20 },
  { label: '50', value: 50 },
  { label: '100', value: 100 }
]

/**
 * EpTablePagination - Pagination controls for tables
 * 
 * Provides page navigation with optional page numbers, ellipsis truncation,
 * and results-per-page selector.
 */
export const EpTablePagination: React.FC<EpTablePaginationProps> = ({
  currentPage,
  showPages = false,
  resultsPerPage,
  totalPages,
  onPageChange,
  onResultsPerPageChange,
  className = ''
}) => {
  const truncationThreshold = 9

  const shouldShowStartEllipsis = useMemo(() => {
    return totalPages > truncationThreshold && currentPage > 3
  }, [totalPages, currentPage])

  const shouldShowEndEllipsis = useMemo(() => {
    return totalPages > truncationThreshold && currentPage < totalPages - 2
  }, [totalPages, currentPage])

  const pageRange = useMemo(() => {
    const range: number[] = []
    if (totalPages <= truncationThreshold) {
      for (let i = 2; i < totalPages; i++) {
        range.push(i)
      }
    } else {
      if (currentPage <= 3) {
        for (let i = 2; i <= 4; i++) {
          range.push(i)
        }
      } else if (currentPage >= totalPages - 2) {
        for (let i = totalPages - 3; i < totalPages; i++) {
          range.push(i)
        }
      } else {
        for (let i = currentPage - 1; i <= currentPage + 1; i++) {
          range.push(i)
        }
      }
    }
    return range
  }, [totalPages, currentPage])

  const prevPage = () => {
    if (currentPage > 1) {
      onPageChange(currentPage - 1)
    }
  }

  const nextPage = () => {
    if (currentPage < totalPages) {
      onPageChange(currentPage + 1)
    }
  }

  return (
    <div className={`ep-table-pagination${className ? ` ${className}` : ''}`}>
      <EpFooter rightGap="1rem" leftFlex="0 1 40rem">
        <EpFlex className="justify-end align-center gap-10 text--overflow-hidden" slot="left">
          Results per page
          <EpSelect
            value={resultsPerPage}
            selectId="resultsPerPage"
            options={resultsPerPageOptions}
            width="7.5rem"
            onChange={onResultsPerPageChange}
          />
        </EpFlex>
        <EpFlex slot="right">
          <EpButton
            disabled={currentPage === 1}
            aria-label="Previous page"
            onClick={prevPage}
            iconLeft={
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M10 12l-4-4 4-4" stroke="currentColor" strokeWidth="2" fill="none" />
              </svg>
            }
          />
          {showPages && (
            <>
              <EpButton
                aria-label="First page"
                className={currentPage === 1 ? 'ep-button--selected' : ''}
                onClick={() => onPageChange(1)}
              >
                1
              </EpButton>
              {shouldShowStartEllipsis && <span>...</span>}
              {pageRange.map((page) => (
                <EpButton
                  key={page}
                  aria-label={`Page ${page}`}
                  className={currentPage === page ? 'ep-button--selected' : ''}
                  onClick={() => onPageChange(page)}
                >
                  {page.toString()}
                </EpButton>
              ))}
              {shouldShowEndEllipsis && <span>...</span>}
              {totalPages > 1 && (
                <EpButton
                  aria-label="Last page"
                  className={currentPage === totalPages ? 'ep-button--selected' : ''}
                  onClick={() => onPageChange(totalPages)}
                >
                  {totalPages.toString()}
                </EpButton>
              )}
            </>
          )}
          <EpButton
            aria-label="Next page"
            disabled={currentPage === totalPages}
            onClick={nextPage}
            iconRight={
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M6 12l4-4-4-4" stroke="currentColor" strokeWidth="2" fill="none" />
              </svg>
            }
          />
        </EpFlex>
      </EpFooter>
    </div>
  )
}

// packages/epicenter-vue-components/src/components/table/EpTablePagination.vue
<template>
  <div class="ep-table-pagination">
    <ep-footer
      right-gap="1rem"
      left-flex="0 1 40rem"
    >
      <template #right>
        <ep-button
          :disabled="currentPage === 1"
          aria-label="Previous page"
          @click="prevPage"
        >
          <template #icon-left>
            chevron left icon
          </template>
        </ep-button>
        <template v-if="showPages">
          <ep-button
            aria-label="First page"
            :class="{ 'ep-button--selected': currentPage === 1 }"
            @click="emit('pageChange', 1)"
          >
            1
          </ep-button>
          <span v-if="shouldShowStartEllipsis">...</span>
          <ep-button
            v-for="page in pageRange"
            :key="page"
            aria-label="Page {{ page }}"
            :class="{ 'ep-button--selected': currentPage === page }"
            @click="emit('pageChange', page)"
          >
            {{ page.toString() }}
          </ep-button>
          <span v-if="shouldShowEndEllipsis">...</span>
          <ep-button
            v-if="totalPages > 1"
            aria-label="Last page"
            :class="{ 'ep-button--selected': currentPage === totalPages }"
            @click="emit('pageChange', totalPages)"
          >
            {{ totalPages.toString() }}
          </ep-button>
        </template>
        <ep-button
          aria-label="Next page"
          :disabled="currentPage === totalPages"
          @click="nextPage"
        >
          <template #icon-right>
            chevron right icon
          </template>
        </ep-button>
      </template>
      <template #left>
        <ep-flex class="justify-end align-center gap-10 text--overflow-hidden">
          Results per page
          <ep-select
            v-model="resultsPerPage"
            select-id="resultsPerPage"
            :options="resultsPerPageOptions"
            width="7.5rem"
            @update:model-value="onResultsPerPageChange"
          />
        </ep-flex>
      </template>
    </ep-footer>
  </div>
</template>

<script setup>
  import { computed, ref } from 'vue'

  import EpButton from '../button/EpButton.vue'
  import EpFlex from '../flexbox/EpFlex.vue'
  import EpFooter from '../footer/EpFooter.vue'
  import EpSelect from '../select/EpSelect.vue'

  defineOptions({
    name: 'EpTablePagination'
  })

  const props = defineProps({
    currentPage: {
      type: Number,
      required: true
    },
    showPages: {
      type: Boolean,
      default: false
    },
    resultsPerPage: {
      type: Number,
      required: true
    },
    totalPages: {
      type: Number,
      required: true
    }
  })

  const resultsPerPage = ref(props.resultsPerPage)

  const resultsPerPageOptions = [
    { label: '10', value: 10 },
    { label: '20', value: 20 },
    { label: '50', value: 50 },
    { label: '100', value: 100 }
  ]

  const onResultsPerPageChange = (value) => {
    emit('update:resultsPerPage', value)
  }

  const showPages = ref(props.showPages)

  const emit = defineEmits(['pageChange', 'update:resultsPerPage'])

  const prevPage = () => {
    if (props.currentPage > 1) {
      emit('pageChange', props.currentPage - 1)
    }
  }

  const nextPage = () => {
    if (props.currentPage < props.totalPages) {
      emit('pageChange', props.currentPage + 1)
    }
  }

  const truncationThreshold = 9

  const shouldShowStartEllipsis = computed(() => {
    return props.totalPages > truncationThreshold && props.currentPage > 3
  })

  const shouldShowEndEllipsis = computed(() => {
    return props.totalPages > truncationThreshold && props.currentPage < props.totalPages - 2
  })

  const pageRange = computed(() => {
    const range = []
    if (props.totalPages <= truncationThreshold) {
      for (let i = 2; i < props.totalPages; i++) {
        range.push(i)
      }
    } else {
      if (props.currentPage <= 3) {
        for (let i = 2; i <= 4; i++) {
          range.push(i)
        }
      } else if (props.currentPage >= props.totalPages - 2) {
        for (let i = props.totalPages - 3; i < props.totalPages; i++) {
          range.push(i)
        }
      } else {
        for (let i = props.currentPage - 1; i <= props.currentPage + 1; i++) {
          range.push(i)
        }
      }
    }
    return range
  })
</script>
