// packages/epicenter-components-react/src/components/table/EpTableHead.tsx
import React from 'react'

import type { Column } from './EpTable'

export interface EpTableHeadProps {
  /** Array of width values for each column cell */
  cellWidths?: React.CSSProperties[]
  /** Array of column configuration objects defining table structure */
  columns: Column[]
  /** If true, enables fixed header behavior */
  fixedHeader?: boolean
  /** Custom header renderer for sortable columns */
  renderHeader?: (props: {
    column: Column
    cellWidths: React.CSSProperties[]
    columnIndex: number
  }) => React.ReactNode
  /** If true, shows an additional column for the actions menu */
  showActionsMenu?: boolean
}

/**
 * EpTableHead - Table header component with support for custom column rendering
 * 
 * Used within EpTable to render table headers with optional custom renderers
 * for sortable columns.
 */
export const EpTableHead: React.FC<EpTableHeadProps> = ({
  columns,
  cellWidths = [],
  showActionsMenu = false,
  renderHeader
}) => {
  return (
    <thead>
      <tr>
        {columns.map((column, columnIndex) => {
          if (renderHeader && column.sortable) {
            return (
              <React.Fragment key={`head-${column.key}`}>
                {renderHeader({ column, cellWidths, columnIndex })}
              </React.Fragment>
            )
          }

          return (
            <th key={`head-${column.key}`} style={cellWidths[columnIndex]}>
              <div>
                <span className="label">{column.label}</span>
              </div>
            </th>
          )
        })}
        {showActionsMenu && (
          <th className="ep-table__actions-menu">
            <div>
              <span className="label">&nbsp;</span>
            </div>
          </th>
        )}
      </tr>
    </thead>
  )
}

// packages/epicenter-vue-components/src/components/table/EpTableHead.vue
<template>
  <thead ref="tableHeadd">
    <tr>
      <template
        v-for="(column, columnIndex) in columns"
        :key="`head-${column.key}`"
      >
        <!-- @slot Custom header content for sortable columns. Receives column, cellWidths, and columnIndex as scoped props. -->
        <slot
          v-if="$slots.header && column.sortable"
          name="header"
          v-bind="{ column, cellWidths, columnIndex }"
        />
        <th
          v-else
          :style="cellWidths[columnIndex]"
        >
          <div>
            <span class="label">{{ column.label }}</span>
          </div>
        </th>
      </template>
      <th
        v-if="showActionsMenu"
        class="ep-table__actions-menu"
      >
        <div>
          <span class="label">
            &nbsp;
          </span>
        </div>
      </th>
    </tr>
  </thead>
</template>

<script setup>
  defineOptions({
    name: 'EpTableHead'
  })

  const props = defineProps({
    /**
     * Array of column configuration objects defining table structure.
     */
    columns: {
      type: Array,
      required: true
    },
    /**
     * Array of width values for each column cell.
     */
    cellWidths: {
      type: Array,
      default: () => []
    },
    /**
     * If true, enables fixed header behavior.
     */
    fixedHeader: Boolean,
    /**
     * If true, shows an additional column for the actions menu.
     */
    showActionsMenu: Boolean,
  })
</script>
