// packages/epicenter-vue-components/src/components/textarea/EpTextarea.vue
<template>
  <div class="ep-textarea">
    <textarea
      :id="id"
      v-model="modelValue"
      :name="name"
      :placeholder="placeholder"
      :disabled="disabled"
      :required="required"
      :rows="rows"
      :cols="cols"
      :maxlength="maxlength"
      :minlength="minlength"
      :readonly="readonly"
      :autofocus="autofocus"
      :autocomplete="autocomplete"
      :spellcheck="spellcheck"
      :wrap="wrap"
      v-bind="$attrs"
      @focus="onFocus"
      @blur="onBlur"
    />
  </div>
</template>

<script setup>
  defineOptions({
    name: 'EpTextarea',
  })

  const props = defineProps({
    /**
     * The ID attribute for the textarea element.
     */
    id: {
      type: String,
      default: null,
    },
    /**
     * The name attribute for the textarea.
     */
    name: {
      type: String,
      default: null,
    },
    /**
     * Placeholder text shown when textarea is empty.
     */
    placeholder: {
      type: String,
      default: null,
    },
    /**
     * If true, disables the textarea.
     */
    disabled: {
      type: Boolean,
      default: false,
    },
    /**
     * If true, marks the textarea as required.
     */
    required: {
      type: Boolean,
      default: false,
    },
    /**
     * Number of visible text rows.
     */
    rows: {
      type: Number,
      default: 2,
    },
    /**
     * Number of visible text columns (width).
     */
    cols: {
      type: Number,
      default: 20,
    },
    /**
     * Maximum character length allowed.
     */
    maxlength: {
      type: Number,
      default: null,
    },
    /**
     * Minimum character length required.
     */
    minlength: {
      type: Number,
      default: null,
    },
    /**
     * If true, makes the textarea read-only.
     */
    readonly: {
      type: Boolean,
      default: false,
    },
    /**
     * If true, automatically focuses on mount.
     */
    autofocus: {
      type: Boolean,
      default: false,
    },
    /**
     * Controls autocomplete behavior.
     * @values 'on', 'off'
     */
    autocomplete: {
      type: String,
      default: 'on',
    },
    /**
     * If true, enables spellcheck.
     */
    spellcheck: {
      type: Boolean,
      default: false,
    },
    /**
     * Controls how text wraps.
     * @values 'soft', 'hard'
     */
    wrap: {
      type: String,
      default: 'soft',
    },
  })

  const modelValue = defineModel({
    type: String,
    default: '',
  })

  const emit = defineEmits(['update:modelValue', 'focus', 'blur'])

  const onFocus = (event) => {
    emit('focus', event)
  }

  const onBlur = (event) => {
    emit('blur', event)
  }
</script>

// packages/epicenter-react-components/src/components/textarea/EpTextarea.tsx
import React, { ChangeEvent, FocusEvent, forwardRef } from 'react';

interface EpTextareaProps {
  /** The ID attribute for the textarea element */
  id?: string;
  /** The name attribute for the textarea */
  name?: string;
  /** Placeholder text shown when textarea is empty */
  placeholder?: string;
  /** The value of the textarea */
  value?: string;
  /** If true, disables the textarea */
  disabled?: boolean;
  /** If true, marks the textarea as required */
  required?: boolean;
  /** Number of visible text rows */
  rows?: number;
  /** Number of visible text columns (width) */
  cols?: number;
  /** Maximum character length allowed */
  maxLength?: number;
  /** Minimum character length required */
  minLength?: number;
  /** If true, makes the textarea read-only */
  readOnly?: boolean;
  /** If true, automatically focuses on mount */
  autoFocus?: boolean;
  /** Controls autocomplete behavior */
  autoComplete?: 'on' | 'off';
  /** If true, enables spellcheck */
  spellCheck?: boolean;
  /** Controls how text wraps */
  wrap?: 'soft' | 'hard';
  /** Callback when value changes */
  onChange?: (event: ChangeEvent<HTMLTextAreaElement>) => void;
  /** Callback when textarea receives focus */
  onFocus?: (event: FocusEvent<HTMLTextAreaElement>) => void;
  /** Callback when textarea loses focus */
  onBlur?: (event: FocusEvent<HTMLTextAreaElement>) => void;
  /** Additional CSS classes */
  className?: string;
}

/**
 * EpTextarea - A textarea input component with comprehensive configuration options
 */
const EpTextarea = forwardRef<HTMLTextAreaElement, EpTextareaProps>(({
  id,
  name,
  placeholder,
  value,
  disabled = false,
  required = false,
  rows = 2,
  cols = 20,
  maxLength,
  minLength,
  readOnly = false,
  autoFocus = false,
  autoComplete = 'on',
  spellCheck = false,
  wrap = 'soft',
  onChange,
  onFocus,
  onBlur,
  className = '',
}, ref) => {
  return (
    <div className={`ep-textarea${className ? ` ${className}` : ''}`}>
      <textarea
        ref={ref}
        id={id}
        name={name}
        placeholder={placeholder}
        value={value}
        disabled={disabled}
        required={required}
        rows={rows}
        cols={cols}
        maxLength={maxLength}
        minLength={minLength}
        readOnly={readOnly}
        autoFocus={autoFocus}
        autoComplete={autoComplete}
        spellCheck={spellCheck}
        wrap={wrap}
        onChange={onChange}
        onFocus={onFocus}
        onBlur={onBlur}
      />
    </div>
  );
});

EpTextarea.displayName = 'EpTextarea';

export default EpTextarea;
