// packages/epicenter-vue-components/src/components/input/EpMultiSearch.vue
<template>
  <div
    :class="['ep-multi-search', classes]"
    :style="inputStyles"
  >
    <div
      v-if="icon"
      class="ep-multi-search__icon"
      :style="iconStyles"
    >
      <ep-icon v-bind="icon" />
    </div>
    <div class="queries">
      <div
        v-for="(query, index) in query"
        :key="index"
        class="query"
        @click="onQueryClose(query, index)"
      >
        <span class="query__text font-size--small">{{ query }}</span>
        <ep-icon
          name="close"
          weight="bold"
          :size="16"
          class="query__close"
        />
      </div>
    </div>
    <input
      ref="input"
      type="text"
      :placeholder="placeholderValue"
      :disabled="disabled"
      v-model="value"
      @input="onInput"
      @focus="onFocus"
      @blur="onBlur"
      @keydown.enter="onEnter"
      @keydown.delete="onDelete"
      @keydown.esc="onEsc"
    />
    <div
      v-if="clearable"
      class="ep-multi-search__clear"
      :style="iconStyles"
      @click="onClear"
    >
      <ep-icon name="close" />
    </div>
  </div>
</template>

<script>
  import EpIcon from '../icon/EpIcon.vue'

  export default {
    name: 'EpMultiSearch',
    components: {
      EpIcon
    },
    data() {
      return {
        hasError: false,
        hasFocus: false,
        // value is the value of the input
        value: '',
        // query is the array of values that have been added to the search
        query: [],
      }
    },
    props: {
      placeholder: {
        type: String,
        default: ''
      },
      icon: {
        type: Object,
        default: () => { }
      },
      disabled: {
        type: Boolean,
        default: false
      },
      autofocus: {
        type: Boolean,
        default: false
      },
      width: {
        type: String,
        default: '100%'
      },
      height: {
        type: String,
        default: '5rem'
      },
      borderWidth: {
        type: String,
        default: '0.1rem'
      },
      borderStyle: {
        type: String,
        default: 'solid'
      },
      borderColor: {
        type: String,
        default: 'var(--border-color)'
      },
      borderRadius: {
        type: String,
        default: 'var(--border-radius)'
      },
      backgroundColor: {
        type: String,
        default: 'var(--background-2)'
      },
      color: {
        type: String,
        default: 'var(--text-color)'
      }
    },
    emits: ['input', 'focus', 'esc', 'blur', 'enter', 'clear', 'query-close', 'delete'],
    methods: {
      onQueryClose(query, index) {
        this.query.splice(index, 1)
        this.$emit('query-close', query)
      },
      onInput(event) {
        this.$emit('input', event.target.value)
      },
      onEsc(event) {
        this.$refs.input.blur()
        this.$emit('esc', event.target.value)
      },
      onFocus(event) {
        this.hasFocus = true
        this.$emit('focus', event.target.value)
      },
      onBlur(event) {
        this.hasFocus = false
        this.$emit('blur', event.target.value)
      },
      onEnter() {
        // on enter, add the value to the query array
        this.query.push(this.value)
        // then emit the query array
        this.$emit('enter', this.query)
        // then clear the input
        this.value = ''
      },
      onDelete() {
        // make sure there's nothing in the input
        if (this.value === '') {
          // find the last element in the query array and remove it
          this.query.splice(this.query.length - 1, 1)
          // then emit the query array
          this.$emit('delete', this.query)
        }
      },
      onClear() {
        this.query = []
        this.value = ''
        this.$refs.input.focus()
        this.$emit('clear', this.query)
      }
    },
    computed: {
      classes() {
        return {
          'ep-multi-search--has-icon': this.icon,
          'ep-multi-search--focus': this.hasFocus,
          'ep-multi-search--disabled': this.disabled,
          // 'ep-input--error': this.error,
          // 'ep-input--success': this.success,
          // 'ep-input--warning': this.warning
        }
      },
      clearable() {
        // if value and query is not empty, then clearable is true
        // if value is empty and query is not empty, then clearable is true
        // if value is not empty and query is empty, then clearable is true
        // if value and query is empty, then clearable is false
        return (this.value && this.query.length > 0) || (!this.value && this.query.length > 0) || (this.value && this.query.length === 0)
      },
      iconStyles() {
        return {
          flex: `0 0 ${this.height}`,
          height: this.height,
        }
      },
      inputStyles() {
        return {
          width: this.width,
          height: this.height,
          borderRadius: this.borderRadius,
          backgroundColor: this.backgroundColor,
          color: this.color
        }
      },
      placeholderValue() {
        // if the input is empty, no value and no query, show the prop placeholder
        // if the query isn't empty, show "add to your search"
        return this.value === '' && this.query.length === 0 ? this.placeholder : 'Add to your search'
      }
    },
    watch: {
      query() {
        console.log('query', this.query)
      }
    },
  }
</script>

<style lang="scss" scoped></style>

// packages/epicenter-components-react/src/components/multi-search/EpMultiSearch.tsx
import {
  forwardRef,
  useState,
  useRef,
  KeyboardEvent,
  ChangeEvent,
  CSSProperties,
} from 'react';

// Placeholder icons - replace with actual icons when available
const Search01 = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
    <circle cx="11" cy="11" r="8" />
    <path d="m21 21-4.35-4.35" />
  </svg>
);

const Cancel01 = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
    <path d="M18 6 6 18M6 6l12 12" />
  </svg>
);

interface ParsedQuery {
  and: string[];
  or: string[];
}

export interface EpMultiSearchProps {
  autofocus?: boolean;
  backgroundColor?: string;
  borderColor?: string;
  borderRadius?: string;
  borderStyle?: string;
  borderWidth?: string;
  className?: string;
  color?: string;
  disabled?: boolean;
  height?: string;
  icon?: boolean;
  onBlur?: (query: ParsedQuery) => void;
  onClear?: (query: ParsedQuery) => void;
  onDelete?: (query: ParsedQuery) => void;
  onEnter?: (query: ParsedQuery) => void;
  onEsc?: (query: ParsedQuery) => void;
  onFocus?: (query: ParsedQuery) => void;
  onInput?: (value: string) => void;
  onQueryClose?: (query: ParsedQuery) => void;
  placeholder?: string;
  queries?: string[];
  value?: string;
  width?: string;
}

export const EpMultiSearch = forwardRef<HTMLDivElement, EpMultiSearchProps>(
  (
    {
      placeholder = '',
      icon = false,
      disabled = false,
      autofocus = false,
      width = '100%',
      height = '5rem',
      borderRadius = 'var(--border-radius--default)',
      backgroundColor = 'var(--interface-foreground)',
      color = 'var(--text-color)',
      value: controlledValue,
      queries: controlledQueries,
      onInput,
      onFocus,
      onBlur,
      onEnter,
      onEsc,
      onClear,
      onQueryClose,
      onDelete,
      className = '',
      ...props
    },
    ref
  ) => {
    const [value, setValue] = useState(controlledValue || '');
    const [query, setQuery] = useState<string[]>(controlledQueries || []);
    const [hasFocus, setHasFocus] = useState(false);
    const inputRef = useRef<HTMLInputElement>(null);

    const isOperator = (term: string) => term === 'AND' || term === 'OR';

    const parseQuery = (queries: string[]): ParsedQuery => {
      const andQueries: string[] = [];
      const orQueries: string[] = [];
      let currentOperator = 'OR';

      queries.forEach((q) => {
        if (isOperator(q)) {
          currentOperator = q;
        } else {
          if (currentOperator === 'AND') {
            andQueries.push(q);
          } else {
            orQueries.push(q);
          }
        }
      });

      return { and: andQueries, or: orQueries };
    };

    const classes = [
      'ep-multi-search',
      icon && 'ep-multi-search--has-icon',
      hasFocus && 'ep-multi-search--focus',
      disabled && 'ep-multi-search--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    const clearable = query.length > 0 || value.length > 0;

    const iconStyles: CSSProperties = {
      flex: `0 0 ${height}`,
      height,
    };

    const inputStyles: CSSProperties = {
      width,
      height,
      borderRadius,
      backgroundColor,
      color,
    };

    const placeholderValue =
      value === '' && query.length === 0 ? placeholder : '+ Add to your search';

    const handleQueryClose = (index: number) => {
      const newQuery = [...query];
      newQuery.splice(index, 1);
      setQuery(newQuery);
      onQueryClose?.(parseQuery(newQuery));
    };

    const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.value;
      setValue(newValue);
      onInput?.(newValue);
    };

    const handleEsc = () => {
      inputRef.current?.blur();
      onEsc?.(parseQuery(query));
    };

    const handleFocus = () => {
      setHasFocus(true);
      onFocus?.(parseQuery(query));
    };

    const handleBlur = () => {
      setHasFocus(false);
      onBlur?.(parseQuery(query));
    };

    const handleEnter = (_e: KeyboardEvent<HTMLInputElement>) => {
      const trimmedValue = value.trim();
      if (!trimmedValue) return;

      const lastQueryItem = query[query.length - 1];

      if (isOperator(trimmedValue)) {
        // Prevent consecutive operators
        if (!query.length || isOperator(lastQueryItem)) return;
      }

      const newQuery = [...query, trimmedValue];
      setQuery(newQuery);
      onEnter?.(parseQuery(newQuery));
      setValue('');
    };

    const handleDelete = (_e: KeyboardEvent<HTMLInputElement>) => {
      if (value === '') {
        const newQuery = [...query];
        newQuery.pop();
        setQuery(newQuery);
        onDelete?.(parseQuery(newQuery));
      }
    };

    const handleClear = () => {
      setQuery([]);
      setValue('');
      inputRef.current?.focus();
      onClear?.(parseQuery([]));
    };

    const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
      switch (e.key) {
        case 'Enter':
          e.preventDefault();
          handleEnter(e);
          break;
        case 'Backspace':
        case 'Delete':
          handleDelete(e);
          break;
        case 'Escape':
          e.preventDefault();
          handleEsc();
          break;
      }
    };

    return (
      <div ref={ref} className={classes} style={inputStyles} {...props}>
        {icon && (
          <div className="ep-multi-search__icon" style={iconStyles}>
            <Search01 />
          </div>
        )}
        <div className="queries">
          {query.map((item, index) => (
            <div
              key={index}
              className={`query ${isOperator(item) ? 'query--operator' : ''}`}
              onClick={() => handleQueryClose(index)}
            >
              <span className="query__text font-size--small">{item}</span>
              <Cancel01 />
            </div>
          ))}
        </div>
        <input
          ref={inputRef}
          type="text"
          data-focus-ring="none"
          value={value}
          placeholder={placeholderValue}
          disabled={disabled}
          autoFocus={autofocus}
          onChange={handleInput}
          onFocus={handleFocus}
          onBlur={handleBlur}
          onKeyDown={handleKeyDown}
        />
        {clearable && (
          <div
            className="ep-multi-search__clear"
            style={iconStyles}
            onClick={handleClear}
          >
            <Cancel01 />
          </div>
        )}
      </div>
    );
  }
);

EpMultiSearch.displayName = 'EpMultiSearch';
