// packages/epicenter-vue-components/src/components/enrichment-dropdown/EpEnrichmentDropdown.vue
<template>
  <div class="ep-enrichment-dropdown">
    <ep-dropdown
      v-bind="$attrs"
      @close="showPreview = false"
    >
      <template #trigger="{ attrs, on }">
        <ep-button
          size="large"
          class="ep-button-var--ghost"
          v-bind="attrs"
          v-on="on"
        >
          {{ label }}
          <template #icon-right>
            <Asterisk02 class="lookup-asterisk" />
          </template>
        </ep-button>
      </template>
      <template #content>
        <div class="ep-enrichment-content">
          <ep-menu class="ep-menu-subtle">
            <ep-menu-item
              v-for="(option, index) in enrichmentOptions"
              :key="index"
              type="item"
              @mouseover="onHover(option)"
            >
              <ep-button class="ep-button--menu-item">
                {{ option.label }}
              </ep-button>
            </ep-menu-item>
          </ep-menu>
          <div
            v-if="showPreview"
            class="enrichment-preview"
          >
            <ep-loading-state
              v-if="loading"
              :message="{ icon: 'oval', message: 'Fetching data…' }"
            />
            <ep-flex
              v-if="enrichmentData"
              class="flex-col gap-10"
            >
              <ep-key-value-table
                :data="enrichmentData[hoveredItem.label]"
                section-headers
              />
              <ep-flex class="gap-10">
                <!-- slot for "action" button -->
                <slot name="action" />
                <ep-button>
                  Source
                  <template #icon-right>
                    <ArrowUpRight01 class="source-button-icon" />
                  </template>
                </ep-button>
              </ep-flex>
            </ep-flex>
          </div>
        </div>
      </template>
    </ep-dropdown>
  </div>
</template>

<script setup>
  import { ArrowUpRight01, Asterisk02 } from '@ericpitcock/epicenter-icons'
  import { ref } from 'vue'

  import EpButton from '../button/EpButton.vue'
  import EpDropdown from '../dropdown/EpDropdown.vue'
  import EpFlex from '../flexbox/EpFlex.vue'
  import EpKeyValueTable from '../key-value-table/EpKeyValueTable.vue'
  import EpLoadingState from '../loading-state/EpLoadingState.vue'
  import EpMenu from '../menu/EpMenu.vue'
  import EpMenuItem from '../menu/EpMenuItem.vue'

  const props = defineProps({
    label: {
      type: String,
      default: ''
    },
    enrichmentOptions: {
      type: Array,
      required: true
    },
    enrichmentData: {
      type: Object,
      default: null
    }
  })

  const hoveredItem = ref(null)
  const loading = ref(false)
  const showPreview = ref(false)
  const hasBeenHovered = []

  const onHover = (item) => {
    if (hasBeenHovered.includes(item.label)) {
      hoveredItem.value = item
      showPreview.value = true
      return
    }

    hasBeenHovered.push(item.label)
    hoveredItem.value = item
    showPreview.value = true
    loading.value = true

    setTimeout(() => {
      loading.value = false
    }, 400)
  }
</script>

<style scoped>
  .ep-enrichment-dropdown {
    position: relative;
    display: inline-block;
  }

  .ep-enrichment-content {
    position: relative;
  }

  .enrichment-preview {
    position: absolute;
    top: 0;
    left: calc(100% + 0.5rem);
    min-width: 40rem;
    padding: 2rem;
    background: var(--interface-foreground);
    border: 1px solid var(--border-color);
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow--dropdown);
    z-index: var(--z-index--dropdown);
  }

  .lookup-asterisk {
    --ep-icon-width: 1.5rem;
    --ep-icon-height: 1.5rem;
    --ep-icon-stroke-width: 2px;
    color: var(--primary-color-up-5-200);
    position: relative;
    top: -5px;
    left: -8px;
  }

  .source-button-icon {
    --ep-icon-width: 1.4rem;
    --ep-icon-height: 1.4rem;
    --ep-icon-stroke-width: 2px;
  }
</style>

// packages/epicenter-react-components/src/components/EpEnrichmentDropdown.tsx
import React, { forwardRef, useState, ReactNode } from 'react';
import EpButton from './button/EpButton';
import EpDropdown from './dropdown/EpDropdown';
import EpFlex from './flexbox/EpFlex';
import EpKeyValueTable from './key-value-table/EpKeyValueTable';
import EpLoadingState from './loading-state/EpLoadingState';
import EpMenu from './menu/EpMenu';
import EpMenuItem from './menu/EpMenuItem';

// Placeholder icons - replace with actual icons when available
const ArrowUpRight01 = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
    <path d="M7 17L17 7M7 7h10v10" />
  </svg>
);

const Asterisk02 = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
    <path d="M12 2v20M5.5 8.5l13 7M5.5 15.5l13-7" />
  </svg>
);

export interface EnrichmentOption {
  label: string;
  [key: string]: unknown;
}

export interface EpEnrichmentDropdownProps {
  label?: string;
  enrichmentOptions: EnrichmentOption[];
  enrichmentData?: Record<string, unknown> | null;
  trigger?: ReactNode;
  action?: ReactNode;
  className?: string;
  [key: string]: unknown;
}

export const EpEnrichmentDropdown = forwardRef<
  HTMLDivElement,
  EpEnrichmentDropdownProps
>(
  (
    {
      label = '',
      enrichmentOptions,
      enrichmentData = null,
      trigger,
      action,
      className = '',
      ...props
    },
    ref
  ) => {
    const [hoveredItem, setHoveredItem] = useState<EnrichmentOption | null>(null);
    const [loading, setLoading] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const hasBeenHoveredRef = React.useRef<string[]>([]);

    const handleHover = (item: EnrichmentOption) => {
      if (hasBeenHoveredRef.current.includes(item.label)) {
        setHoveredItem(item);
        setShowPreview(true);
        return;
      }

      hasBeenHoveredRef.current.push(item.label);
      setHoveredItem(item);
      setShowPreview(true);
      setLoading(true);

      setTimeout(() => {
        setLoading(false);
      }, 400);
    };

    const handleClose = () => {
      setShowPreview(false);
    };

    return (
      <div ref={ref} className={`ep-enrichment-dropdown ${className}`.trim()} {...props}>
        <EpDropdown onClose={handleClose}>
          <div slot="trigger" className="trigger-wrapper">
            {trigger ? trigger : label}
            <Asterisk02 className="lookup-asterisk" />
          </div>
          <div slot="content" className="ep-enrichment-content">
            <EpMenu className="ep-menu-subtle">
              {enrichmentOptions.map((option, index) => (
                <EpMenuItem
                  key={index}
                  type="item"
                  onMouseOver={() => handleHover(option)}
                  onFocus={() => handleHover(option)}
                >
                  <EpButton className="ep-button--menu-item">
                    {option.label}
                  </EpButton>
                </EpMenuItem>
              ))}
            </EpMenu>
            {showPreview && (
              <div className="enrichment-preview">
                {loading && (
                  <EpLoadingState
                    message={{
                      icon: 'oval',
                      message: 'Fetching data…',
                    }}
                  />
                )}
                {enrichmentData && hoveredItem && (
                  <EpFlex className="flex-col gap-10">
                    <EpKeyValueTable
                      data={enrichmentData[hoveredItem.label] as Record<string, unknown>}
                      sectionHeaders
                    />
                    <EpFlex className="gap-10">
                      {action}
                      <EpButton iconRight={<ArrowUpRight01 className="source-button-icon" />}>
                        Source
                      </EpButton>
                    </EpFlex>
                  </EpFlex>
                )}
              </div>
            )}
          </div>
        </EpDropdown>
      </div>
    );
  }
);

EpEnrichmentDropdown.displayName = 'EpEnrichmentDropdown';
