// packages/epicenter-vue-components/src/components/breadcrumbs/EpBreadcrumbs.vue
<template>
  <nav aria-label="Breadcrumb">
    <ol class="ep-breadcrumbs">
      <li
        v-for="(crumb, index) in breadcrumbItems"
        :key="index"
        class="ep-breadcrumbs__item"
        :class="crumb.customClass"
      >
        <template v-if="$slots.item">
          <!-- @slot item - Custom content for each breadcrumb item. Provides crumb, index, and is-last via slot props. -->
          <slot
            name="item"
            :crumb="crumb"
            :index="index"
            :is-last="index === breadcrumbItems.length - 1"
          />
        </template>
        <template v-else>
          <router-link
            v-if="index !== breadcrumbItems.length - 1"
            :to="crumb.to"
          >
            {{ crumb.label }}
          </router-link>
          <span
            v-else
            aria-current="page"
            class="ep-breadcrumbs__item--current"
          >{{ crumb.label }}</span>
        </template>
        <span
          v-if="index !== breadcrumbItems.length - 1"
          class="ep-breadcrumbs__separator"
          aria-hidden="true"
        >
          <!-- @slot separator - Custom separator between breadcrumb items. Provides index via slot props. -->
          <slot
            name="separator"
            :index="index"
          >
            <ArrowRight01 />
          </slot>
        </span>
      </li>
    </ol>
  </nav>
</template>

<script setup>
  import ArrowRight01 from '@ericpitcock/epicenter-icons/epicenter-icons/ArrowRight01'
  import { computed } from 'vue'
  import { useRoute } from 'vue-router'

  const props = defineProps({
    /**
     * An array of breadcrumb items with label, to, and optional customClass properties.
     */
    items: {
      type: Array,
      default: () => []
    },
    /**
     * If true, automatically generates breadcrumbs from the current route.
     */
    auto: {
      type: Boolean,
      default: false
    }
  })

  const route = useRoute()

  const breadcrumbItems = computed(() => {
    if (props.auto) {
      return route.matched
        .filter(record => record.meta && record.meta.breadcrumb !== false)
        .map(record => ({
          label: record.meta.breadcrumb || record.name || '',
          to: record.path,
          customClass: record.meta.customClass || ''
        }))
    } else {
      return props.items
    }
  })
</script>

<style lang="scss" scoped>
  .ep-breadcrumbs {
    list-style: none;
    display: flex;

    &__item {
      display: flex;
      align-items: center;
      color: var(--text-color--subtle);

      a {
        cursor: pointer;

        &:hover {
          color: var(--text-color--loud);
        }
      }

      &--current {
        color: var(--text-color--loud);
        cursor: default;
      }
    }

    &__separator {
      padding-inline: 0.5em;

      .ep-icon {
        --ep-icon-width: 1em;
        --ep-icon-height: 1em;
        --ep-icon-stroke-width: 3px;
        --ep-icon-color: var(--text-color--disabled);
      }
    }
  }
</style>

// packages/epicenter-components-react/src/components/breadcrumbs/EpBreadcrumbs.tsx
import React, { ReactNode } from 'react'
import { Link } from 'react-router-dom'

export interface BreadcrumbItem {
  customClass?: string
  label: string
  to?: string
}

export interface EpBreadcrumbsProps {
  /**
   * An array of breadcrumb items with label, to, and optional customClass properties.
   */
  items?: BreadcrumbItem[]
  /**
   * Custom render function for breadcrumb items
   */
  renderItem?: (crumb: BreadcrumbItem, index: number, isLast: boolean) => ReactNode
  /**
   * Custom separator between breadcrumb items
   */
  separator?: ReactNode
}

export const EpBreadcrumbs: React.FC<EpBreadcrumbsProps> = ({
  items = [],
  separator,
  renderItem
}) => {
  const defaultSeparator = separator || (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M9 6l6 6-6 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )

  return (
    <nav aria-label="Breadcrumb">
      <ol className="ep-breadcrumbs">
        {items.map((crumb, index) => {
          const isLast = index === items.length - 1

          return (
            <li
              key={index}
              className={['ep-breadcrumbs__item', crumb.customClass].filter(Boolean).join(' ')}
            >
              {renderItem ? (
                renderItem(crumb, index, isLast)
              ) : (
                <>
                  {!isLast && crumb.to ? (
                    <Link to={crumb.to}>
                      {crumb.label}
                    </Link>
                  ) : (
                    <span
                      aria-current={isLast ? 'page' : undefined}
                      className={isLast ? 'ep-breadcrumbs__item--current' : undefined}
                    >
                      {crumb.label}
                    </span>
                  )}
                  {!isLast && (
                    <span className="ep-breadcrumbs__separator" aria-hidden="true">
                      {defaultSeparator}
                    </span>
                  )}
                </>
              )}
            </li>
          )
        })}
      </ol>
    </nav>
  )
}
