// packages/epicenter-components-react/src/components/code-view/EpCodeView.tsx
import React, { useEffect, useState } from 'react'

export interface EpCodeViewProps {
  /** Additional CSS classes */
  className?: string
  /** The code to display */
  code: string
  /** The language of the code */
  language: string
  /** The theme to use for highlighting */
  theme?: string
}

/**
 * EpCodeView - Syntax-highlighted code viewer
 * 
 * Uses Shiki for syntax highlighting with customizable themes.
 */
export const EpCodeView: React.FC<EpCodeViewProps> = ({
  code,
  language,
  theme = 'one-dark-pro',
  className = ''
}) => {
  const [highlightedCode, setHighlightedCode] = useState('')

  useEffect(() => {
    const highlightCode = async () => {
      try {
        const { codeToHtml } = await import('shiki')
        const html = await codeToHtml(code, {
          lang: language,
          theme: theme,
          colorReplacements: {
            '#282c34': 'var(--interface-surface)'
          }
        })
        setHighlightedCode(html)
      } catch (error) {
        console.error('Error highlighting code:', error)
        // Fallback to plain text
        setHighlightedCode(code)
      }
    }

    highlightCode()
  }, [code, language, theme])

  return (
    <div
      className={`ep-code-view${className ? ` ${className}` : ''}`}
      dangerouslySetInnerHTML={{ __html: highlightedCode }}
    />
  )
}

// packages/epicenter-vue-components/src/components/code-view/EpCodeView.vue
<!-- eslint-disable vue/no-v-html -->
<template>
  <div
    class="ep-code-block"
    v-html="highlightedCode"
  />
</template>

<script setup>
  import { onMounted, ref } from 'vue'
  import { codeToHtml } from 'shiki'

  defineOptions({
    name: 'EpCodeView'
  })

  const props = defineProps({
    /**
     * The code to display.
     */
    code: {
      type: String,
      required: true
    },
    /**
     * The language of the code.
     */
    language: {
      type: String,
      required: true
    },
    /**
     * The theme to use for highlighting.
     */
    theme: {
      type: String,
      default: 'vitesse-dark'
    }
  })

  const highlightedCode = ref('')

  const highlightCode = async () => {
    try {
      highlightedCode.value = await codeToHtml(props.code, {
        lang: props.language,
        theme: 'one-dark-pro',
        colorReplacements: {
          '#282c34': 'var(--interface-surface)',
        }
      })
    } catch (error) {
      console.error('Error highlighting code:', error)
      // Fallback to plain text
      highlightedCode.value = props.code
    }
  }

  onMounted(() => {
    highlightCode()
  })
</script>

<style lang="scss">
  .ep-code-block pre {
    white-space: pre;
  }
</style>
