// packages/epicenter-components-react/storybook/intro/EpIntro.tsx
import { Github } from '@ericpitcock/epicenter-icons-react/Github.jsx'
import { DocumentCode } from '@ericpitcock/epicenter-icons-react/DocumentCode.jsx'

import { EpButton, EpFlex, EpicenterLogo } from '@ericpitcock/epicenter-components-react'

import './EpIntro.scss'

const buttons = [
  {
    href: 'https://github.com/ericpitcock/epicenter-design-system',
    label: 'GitHub',
    icon: <Github />,
  },
  {
    href: '/docs',
    label: 'Docs',
    icon: <DocumentCode />,
  },
]

export function EpIntro() {
  return (
    <div className="intro">
      <div className="hero">
        <div className="logo-container">
          <EpicenterLogo style={{ '--logo-stroke-width': 4 } as React.CSSProperties} />
        </div>
        <div className="copy-block">
          <h1 className="font-size--jumbo">
            Epicenter Design System: React
          </h1>
          <p className="monospace">
            {'{ React } = componentsForApps'}
          </p>
          <EpFlex className="gap-10">
            {buttons.map((btn, index) => (
              <EpButton
                key={index}
                className="hero-btn"
                href={btn.href}
                size="large"
                iconLeft={btn.icon}
              >
                {btn.label}
              </EpButton>
            ))}
          </EpFlex>
        </div>
      </div>
    </div>
  )
}

// src/intro/EpIntro.vue
<template>
  <div class="intro">
    <div class="logo-container">
      <e />
    </div>
    <div class="copy-block">
      <h1>E Design System</h1>
      <p>Vue 3 components designed and built by <a href="https://www.ericpitcock.com">Eric Pitcock</a>.</p>
      <p>Check out the code on <a href="https://github.com/ericpitcock/ep-design-system">GitHub</a>.</p>
    </div>
  </div>
</template>

<script>
  import E from '@/components/logo/E'

  export default {
    name: 'Intro',
    components: {
      E
    }
  }
</script>

<style lang="scss" scoped>
  .intro {
    padding: 8rem 10rem;
    .logo-container {
      width: 10rem;
    }
  }
</style>
