// packages/epicenter-vue-components/src/components/input/EpInput.vue
<template>
  <ep-input-styler
    v-bind="stylerProps"
    @click="onClear"
  >
    <template
      v-if="$slots['icon-left']"
      #icon-left
    >
      <!-- @slot Optional icon displayed on the left side of the input -->
      <slot name="icon-left" />
    </template>
    <input
      :id="computedId"
      ref="input"
      v-model="modelValue"
      :class="['ep-input', inputClasses]"
      :type="type"
      :placeholder="computedPlaceholder"
      :disabled="disabled"
      :autofocus="autofocus"
      :readonly="readonly"
      :required="required"
      v-bind="$attrs"
      @focus="onFocus"
      @blur="onBlur"
      @keydown="onKeyDown"
      @keydown.esc="onEsc"
    >
    <template
      v-if="$slots['icon-right']"
      #icon-right
    >
      <!-- @slot Optional icon displayed on the right side of the input (overridden by clearable button if active) -->
      <slot name="icon-right" />
    </template>
  </ep-input-styler>
</template>

<script setup>
  import { computed, ref, useId, watch } from 'vue'

  import EpInputStyler from '../input-styler/EpInputStyler.vue'

  defineOptions({
    inheritAttrs: false,
  })

  const props = defineProps({
    /**
     * The ID attribute for the input element. Auto-generated if not provided.
     */
    inputId: {
      type: String,
      default: ''
    },
    /**
     * Label text for the input (used as placeholder when empty).
     */
    label: {
      type: String,
      default: ''
    },
    /**
     * The input type attribute.
     * @values 'text', 'email', 'password', 'number', 'tel', etc.
     */
    type: {
      type: String,
      default: 'text'
    },
    /**
     * Placeholder text shown when the input is empty.
     */
    placeholder: {
      type: String,
      default: ''
    },
    /**
     * If true, displays a clear button when input has a value.
     */
    clearable: {
      type: Boolean,
      default: false
    },
    /**
     * If true, disables the input element.
     */
    disabled: {
      type: Boolean,
      default: false
    },
    /**
     * If true, automatically focuses the input on mount.
     */
    autofocus: {
      type: Boolean,
      default: false
    },
    /**
     * If true, marks the input as required.
     */
    required: {
      type: Boolean,
      default: false
    },
    /**
     * If true, makes the input read-only.
     */
    readonly: {
      type: Boolean,
      default: false
    },
    /**
     * The size variant of the input.
     * @values 'default', 'large', 'xlarge'
     */
    size: {
      type: String,
      default: 'default'
    },
  })

  const emit = defineEmits(['focus', 'esc', 'blur', 'enter', 'clear'])

  const input = ref(null)

  const modelValue = defineModel({
    type: String,
    required: true
  })

  const hasInput = ref(!!modelValue.value)
  const computedId = ref(props.inputId || useId())

  const computedPlaceholder = computed(() => props.placeholder || props.label)

  const stylerProps = computed(() => ({
    id: computedId.value,
    hasInput: hasInput.value,
    label: props.label,
    clearable: props.clearable,
    disabled: props.disabled,
    size: props.size,
  }))

  const inputClasses = computed(() => ({
    [`ep-input--${props.size}`]: props.size,
    'ep-input--disabled': props.disabled
  }))

  watch(modelValue, (value) => {
    hasInput.value = !!value
  })

  const onEsc = () => {
    input.value?.blur()
    emit('esc', modelValue.value)
  }

  const onFocus = () => {
    emit('focus', modelValue.value)
  }

  const onBlur = () => {
    emit('blur', modelValue.value)
  }

  const onKeyDown = (event) => {
    if (event.key === 'Enter') {
      emit('enter', modelValue.value)
    }
  }

  const onClear = () => {
    modelValue.value = ''
    input.value?.focus()
    emit('clear', '')
  }
</script>

// packages/epicenter-components-react/src/components/input/EpInput.tsx
import React, { forwardRef, ReactNode, useId, KeyboardEvent, FocusEvent, ChangeEvent } from 'react'

import { EpInputStyler } from '../input-styler/EpInputStyler'

export interface EpInputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size' | 'onChange' | 'onFocus' | 'onBlur'> {
  /**
   * If true, automatically focuses the input on mount.
   * @default false
   */
  autofocus?: boolean
  /**
   * If true, displays a clear button when input has a value.
   * @default false
   */
  clearable?: boolean
  /**
   * If true, disables the input element.
   * @default false
   */
  disabled?: boolean
  /**
   * If true, displays the input in error state.
   * @default false
   */
  error?: boolean
  /**
   * If true, enables error state styling and message display.
   * @default false
   */
  errorEnabled?: boolean
  /**
   * Error message to display below the input.
   */
  errorMessage?: string
  /**
   * Icon content for left side
   */
  iconLeft?: ReactNode
  /**
   * Icon content for right side (overridden by clearable button if active)
   */
  iconRight?: ReactNode
  /**
   * The ID attribute for the input element. Auto-generated if not provided.
   */
  inputId?: string
  /**
   * Label text for the input (used as placeholder when empty).
   */
  label?: string
  /**
   * Handler called when input loses focus
   */
  onBlur?: (value: string) => void
  /**
   * Change handler for controlled input
   */
  onChange?: (value: string) => void
  /**
   * Handler called when clear button is clicked
   */
  onClear?: () => void
  /**
   * Handler called when Enter key is pressed
   */
  onEnter?: (value: string) => void
  /**
   * Handler called when Escape key is pressed
   */
  onEsc?: (value: string) => void
  /**
   * Handler called when input is focused
   */
  onFocus?: (value: string) => void
  /**
   * Placeholder text shown when the input is empty.
   */
  placeholder?: string
  /**
   * If true, makes the input read-only.
   * @default false
   */
  readonly?: boolean
  /**
   * If true, marks the input as required.
   * @default false
   */
  required?: boolean
  /**
   * The size variant of the input.
   * @default 'default'
   */
  size?: 'default' | 'large' | 'xlarge'
  /**
   * The input type attribute.
   * @default 'text'
   */
  type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' | 'search'
  /**
   * Current value of the input
   */
  value?: string
}

export const EpInput = forwardRef<HTMLInputElement, EpInputProps>(({
  inputId,
  label = '',
  type = 'text',
  placeholder,
  value = '',
  onChange,
  clearable = false,
  disabled = false,
  autofocus = false,
  required = false,
  readonly = false,
  size = 'default',
  errorEnabled = false,
  error = false,
  errorMessage = '',
  iconLeft,
  iconRight,
  onFocus,
  onBlur,
  onEsc,
  onEnter,
  onClear,
  ...rest
}, ref) => {
  const generatedId = useId()
  const computedId = inputId || generatedId
  const computedPlaceholder = placeholder || label
  const hasInput = !!value

  const inputClasses = [
    'ep-input',
    size !== 'default' && `ep-input--${size}`,
    disabled && 'ep-input--disabled'
  ].filter(Boolean).join(' ')

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    onChange?.(event.target.value)
  }

  const handleFocus = (event: FocusEvent<HTMLInputElement>) => {
    onFocus?.(event.target.value)
  }

  const handleBlur = (event: FocusEvent<HTMLInputElement>) => {
    onBlur?.(event.target.value)
  }

  const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Escape') {
      event.currentTarget.blur()
      onEsc?.(value)
    } else if (event.key === 'Enter') {
      onEnter?.(value)
    }
  }

  const handleClear = () => {
    onChange?.('')
    onClear?.()
    // Focus the input after clearing
    if (ref && 'current' in ref && ref.current) {
      ref.current.focus()
    }
  }

  return (
    <EpInputStyler
      id={computedId}
      hasInput={hasInput}
      label={label}
      clearable={clearable}
      disabled={disabled}
      errorEnabled={errorEnabled}
      error={error}
      errorMessage={errorMessage}
      size={size}
      iconLeft={iconLeft}
      iconRight={iconRight}
      onClear={handleClear}
    >
      <input
        id={computedId}
        ref={ref}
        className={inputClasses}
        type={type}
        placeholder={computedPlaceholder}
        value={value}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        disabled={disabled}
        autoFocus={autofocus}
        readOnly={readonly}
        required={required}
        {...rest}
      />
    </EpInputStyler>
  )
})

EpInput.displayName = 'EpInput'
