// packages/epicenter-design-system/src/components/checkbox/EpCheckbox.vue
<template>
  <div :class="['ep-checkbox', classes]">
    <input
      type="checkbox"
      ref="input"
      :id="id"
      :name="name"
      :value="value"
      :checked="checked"
      :indeterminate="indeterminate"
      :disabled="disabled"
      :required="required"
      :readonly="readonly"
      :tabindex="tabindex"
      @change="onChange(command, $event)"
    >
    <label :for="id">{{ label }}</label>
  </div>
</template>

<script>
  export default {
    name: 'EpCheckbox',
    props: {
      id: {
        type: String,
        default: 'default'
      },
      name: {
        type: String,
        default: null
      },
      value: {
        type: String,
        default: null
      },
      checked: {
        type: Boolean,
        default: false
      },
      indeterminate: {
        type: Boolean,
        default: false
      },
      disabled: {
        type: Boolean,
        default: false
      },
      label: {
        type: String,
        default: 'Checkbox'
      },
      required: {
        type: Boolean,
        default: false
      },
      readonly: {
        type: Boolean,
        default: false
      },
      tabindex: {
        type: Number,
        default: null
      },
      command: {
        type: Function,
        default: null
      }
    },
    computed: {
      classes() {
        return {
          'ep-checkbox--disabled': this.disabled
        }
      }
    },
    watch: {
      indeterminate() {
        this.$refs.input.indeterminate = this.indeterminate
      }
    },
    methods: {
      onChange(command, event) {
        // console.log('onChange', event.target.checked)
        this.$emit('checkchange', event.target.checked)
        if (command) {
          command(event.target.checked)
        }
      }
    }
  }
</script>

// packages/epicenter-components-react/src/components/checkbox/EpCheckbox.tsx
import React, { ChangeEvent, ReactNode, forwardRef } from 'react';

export interface EpCheckboxProps {
  /** The ID of the checkbox */
  id: string;
  /** The label for the checkbox */
  label: string;
  /** The name of the checkbox */
  name: string;
  /** The value of the checkbox */
  value: string;
  /** Whether the checkbox is checked */
  checked?: boolean;
  /** Whether the checkbox is disabled */
  disabled?: boolean;
  /** Whether the checkbox is indeterminate */
  indeterminate?: boolean;
  /** Whether the checkbox is required */
  required?: boolean;
  /** Callback when checkbox state changes */
  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
  /** Additional CSS classes */
  className?: string;
  /** Optional children to override label */
  children?: ReactNode;
}

/**
 * EpCheckbox - A checkbox input component with label and various states
 */
export const EpCheckbox = forwardRef<HTMLInputElement, EpCheckboxProps>(({
  id,
  label,
  name,
  value,
  checked = false,
  disabled = false,
  indeterminate = false,
  required = false,
  onChange,
  className = '',
  children,
}, ref) => {
  const classes = ['ep-checkbox'];
  
  if (checked) classes.push('ep-checkbox--checked');
  if (disabled) classes.push('ep-checkbox--disabled');
  if (indeterminate) classes.push('ep-checkbox--indeterminate');
  if (className) classes.push(className);

  return (
    <label htmlFor={id} className={classes.join(' ')}>
      <input
        ref={ref}
        id={id}
        type="checkbox"
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        required={required}
        onChange={onChange}
      />
      {children || label}
    </label>
  );
});

EpCheckbox.displayName = 'EpCheckbox';
