// packages/epicenter-components-react/src/components/checkbox/EpCheckbox.tsx
import React, { ChangeEvent, ReactNode, forwardRef } from 'react';

export interface EpCheckboxProps {
  /** The ID of the checkbox */
  id: string;
  /** The label for the checkbox */
  label: string;
  /** The name of the checkbox */
  name: string;
  /** The value of the checkbox */
  value: string;
  /** Whether the checkbox is checked */
  checked?: boolean;
  /** Whether the checkbox is disabled */
  disabled?: boolean;
  /** Whether the checkbox is indeterminate */
  indeterminate?: boolean;
  /** Whether the checkbox is required */
  required?: boolean;
  /** Callback when checkbox state changes */
  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
  /** Additional CSS classes */
  className?: string;
  /** Optional children to override label */
  children?: ReactNode;
}

/**
 * EpCheckbox - A checkbox input component with label and various states
 */
export const EpCheckbox = forwardRef<HTMLInputElement, EpCheckboxProps>(({
  id,
  label,
  name,
  value,
  checked = false,
  disabled = false,
  indeterminate = false,
  required = false,
  onChange,
  className = '',
  children,
}, ref) => {
  const classes = ['ep-checkbox'];
  
  if (checked) classes.push('ep-checkbox--checked');
  if (disabled) classes.push('ep-checkbox--disabled');
  if (indeterminate) classes.push('ep-checkbox--indeterminate');
  if (className) classes.push(className);

  return (
    <label htmlFor={id} className={classes.join(' ')}>
      <input
        ref={ref}
        id={id}
        type="checkbox"
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        required={required}
        onChange={onChange}
      />
      {children || label}
    </label>
  );
});

EpCheckbox.displayName = 'EpCheckbox';

// packages/epicenter-components-vue/src/components/checkbox/EpCheckbox.vue
<script setup lang="ts">
  import { computed } from 'vue'

  interface EpCheckboxProps {
    /** Whether the checkbox is checked. */
    checked?: boolean
    /** Whether the checkbox is disabled. */
    disabled?: boolean
    /** The ID of the checkbox. */
    id: string
    /** Whether the checkbox is indeterminate. */
    indeterminate?: boolean
    /** The label for the checkbox. */
    label: string
    /** The name of the checkbox. */
    name: string
    /** Whether the checkbox is required. */
    required?: boolean
    /** The value of the checkbox. */
    value: string
  }

  const {
    checked = false,
    disabled = false,
    indeterminate = false,
    required = false,
  } = defineProps<EpCheckboxProps>()

  const modelValue = defineModel<boolean>({ required: true })

  const classes = computed(() => {
    return {
      'ep-checkbox--checked': modelValue.value,
      'ep-checkbox--disabled': disabled,
      'ep-checkbox--indeterminate': indeterminate,
    }
  })
</script>

<template>
  <label
    :for="id"
    :class="['ep-checkbox', classes]"
  >
    <input
      :id="id"
      v-model="modelValue"
      type="checkbox"
      :name
      :value
      :checked
      :disabled
      :indeterminate
      :required
    >
    <slot>
      {{ label }}
    </slot>
  </label>
</template>
