// packages/epicenter-components-vue/src/components/tabs/EpTabs.vue
<script setup lang="ts">
  import { computed, ref } from 'vue'

  interface TabItem {
    exact?: boolean
    label: string
    to?: string
  }

  interface EpTabsProps {
    activeTabIndex?: number
    items?: (string | TabItem)[]
    variant?: string
  }

  const { activeTabIndex = 0, items = [], variant = 'default' } = defineProps<EpTabsProps>()

  const emit = defineEmits<{
    'tab-click': [payload: { item: TabItem; index: number } | number]
  }>()

  const tabs = computed((): TabItem[] => {
    return items.map(item => (typeof item === 'object' ? item : { label: item }))
  })

  const onClick = ({ item, index }: { item: TabItem; index: number }): void => {
    if (!item.to) {
      emit('tab-click', { item, index })
    }
  }

  const handleKeydown = (index: number, event: KeyboardEvent): void => {
    const keyActions: Record<string, () => void> = {
      ArrowRight: () => focusTab((index + 1) % tabs.value.length),
      ArrowLeft: () => focusTab((index - 1 + tabs.value.length) % tabs.value.length),
      Home: () => focusTab(0),
      End: () => focusTab(tabs.value.length - 1),
      Enter: () => emit('tab-click', index),
      ' ': () => emit('tab-click', index),
    }

    if (keyActions[event.key]) {
      keyActions[event.key]()
    }
  }

  const tabList = ref<HTMLDivElement | null>(null)

  const focusTab = (index: number): void => {
    const tabElements = tabList.value?.querySelectorAll('[role="tab"]') || []
      ; (tabElements[index] as HTMLElement)?.focus()
  }
</script>

<template>
  <div
    ref="tabList"
    class="ep-tabs"
    :class="{ 'ep-tabs--classic': variant === 'classic' }"
    role="tablist"
  >
    <component
      :is="item.to ? 'router-link' : 'button'"
      v-for="(item, index) in tabs"
      :id="`tab-${index}`"
      :key="index"
      :aria-controls="`tabpanel-${index}`"
      :class="[
        'ep-tabs__tab-item',
        { 'ep-tabs__tab-item--active': !item.to && index === activeTabIndex }
      ]"
      :to="item.to ? item.to : undefined"
      :exact="item.to ? item.exact : undefined"
      role="tab"
      :aria-selected="index === activeTabIndex"
      :tabindex="index === activeTabIndex ? 0 : -1"
      @click="onClick({ item, index })"
      @keydown="handleKeydown(index, $event)"
    >
      <span>{{ item.label }}</span>
    </component>
  </div>
</template>

// packages/epicenter-react-components/src/components/tabs/EpTabs.tsx
import React, { useRef, KeyboardEvent } from 'react'
import { Link } from 'react-router-dom'

export interface TabItem {
  label: string
  to?: string
  exact?: boolean
}

export interface EpTabsProps {
  /**
   * The index of the active tab.
   * @default 0
   */
  activeTabIndex?: number
  /**
   * The tabs to display.
   */
  items: (string | TabItem)[]
  /**
   * The variant of the tabs, default or classic.
   * @default 'default'
   */
  variant?: 'default' | 'classic'
  /**
   * Handler called when a tab is clicked
   */
  onTabClick?: (data: { item: TabItem; index: number }) => void
}

const EpTabs: React.FC<EpTabsProps> = ({
  activeTabIndex = 0,
  items,
  variant = 'default',
  onTabClick
}) => {
  const tabListRef = useRef<HTMLDivElement>(null)

  const tabs = items.map(item => 
    typeof item === 'object' ? item : { label: item }
  )

  const handleClick = (item: TabItem, index: number) => {
    if (!item.to) {
      onTabClick?.({ item, index })
    }
  }

  const focusTab = (index: number) => {
    const tabElements = tabListRef.current?.querySelectorAll('[role="tab"]') || []
    ;(tabElements[index] as HTMLElement)?.focus()
  }

  const handleKeyDown = (index: number, event: KeyboardEvent) => {
    const keyActions: Record<string, () => void> = {
      ArrowRight: () => focusTab((index + 1) % tabs.length),
      ArrowLeft: () => focusTab((index - 1 + tabs.length) % tabs.length),
      Home: () => focusTab(0),
      End: () => focusTab(tabs.length - 1),
      Enter: () => onTabClick?.({ item: tabs[index], index }),
      ' ': () => onTabClick?.({ item: tabs[index], index })
    }

    if (keyActions[event.key]) {
      event.preventDefault()
      keyActions[event.key]()
    }
  }

  return (
    <div
      ref={tabListRef}
      className={[
        'ep-tabs',
        variant === 'classic' && 'ep-tabs--classic'
      ].filter(Boolean).join(' ')}
      role="tablist"
    >
      {tabs.map((item, index) => {
        const isActive = !item.to && index === activeTabIndex
        const tabClasses = [
          'ep-tabs__tab-item',
          isActive && 'ep-tabs__tab-item--active'
        ].filter(Boolean).join(' ')

        const commonProps = {
          id: `tab-${index}`,
          'aria-controls': `tabpanel-${index}`,
          className: tabClasses,
          role: 'tab' as const,
          'aria-selected': index === activeTabIndex,
          tabIndex: index === activeTabIndex ? 0 : -1,
          onKeyDown: (e: KeyboardEvent) => handleKeyDown(index, e)
        }

        if (item.to) {
          return (
            <Link
              key={index}
              to={item.to}
              {...commonProps}
            >
              <span>{item.label}</span>
            </Link>
          )
        }

        return (
          <button
            key={index}
            type="button"
            {...commonProps}
            onClick={() => handleClick(item, index)}
          >
            <span>{item.label}</span>
          </button>
        )
      })}
    </div>
  )
}

export default EpTabs
