// packages/epicenter-vue-components/src/components/lazy-image/EpLazyImage.vue
<template>
  <div
    ref="imageEl"
    :class="['ep-image', { 'ep-image--rounded': rounded, 'ep-image--loading': !isLoaded }]"
  >
    <img
      v-if="isLoaded"
      :src="src"
      :alt="alt"
      :width="width"
      :height="height"
      :class="['ep-image__img', className]"
      :style="{ aspectRatio: aspectRatio, objectFit: objectFit }"
    >
    <div
      v-else
      class="ep-image__placeholder"
      :style="placeholderStyle"
    />
  </div>
</template>

<script setup>
  import { computed, onBeforeUnmount, onMounted, ref } from 'vue'

  const props = defineProps({
    /**
     * The source URL of the image.
     */
    src: {
      type: String,
      required: true,
    },
    /**
     * The alt text for the image.
     */
    alt: {
      type: String,
      default: '',
    },
    /**
     * The width of the image.
     */
    width: {
      type: [String, Number],
      default: '100%',
    },
    /**
     * The height of the image.
     */
    height: {
      type: [String, Number],
      default: '100%',
    },
    /**
     * The aspect ratio of the image (e.g., '16 / 9').
     */
    aspectRatio: {
      type: String,
      default: '16 / 10',
    },
    /**
     * How the image fits within its container.
     * @values contain, cover, fill, none, scale-down
     */
    objectFit: {
      type: String,
      default: 'contain',
    },
    /**
     * Additional CSS class name for the image element.
     */
    className: {
      type: String,
      default: '',
    },
    /**
     * URL of the placeholder image to display while loading.
     */
    placeholder: {
      type: String,
      default: '',
    },
    /**
     * The background color of the placeholder.
     */
    placeholderColor: {
      type: String,
      default: '#f5f5f5',
    },
    /**
     * The opacity of the placeholder.
     */
    placeholderOpacity: {
      type: Number,
      default: 1,
    },
    /**
     * If true, enables lazy loading using Intersection Observer.
     */
    lazy: {
      type: Boolean,
      default: true,
    },
    /**
     * If true, applies rounded corners to the image.
     */
    rounded: {
      type: Boolean,
      default: true,
    },
    /**
     * The root margin for the Intersection Observer (controls when loading starts).
     */
    rootMargin: {
      type: String,
      default: '0px 0px 100px 0px',
    },
  })

  const isLoaded = ref(false)
  const imageEl = ref(null)
  let observer = null

  const placeholderStyle = computed(() => {
    return {
      width: props.width,
      height: props.height,
      aspectRatio: props.aspectRatio,
      backgroundColor: props.placeholderColor,
      opacity: props.placeholderOpacity,
      backgroundImage: props.placeholder ? `url(${props.placeholder})` : '',
      backgroundSize: 'cover',
    }
  })

  const addLazyLoadListener = () => {
    observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          loadImage()
          observer.unobserve(entry.target)
        }
      })
    }, {
      rootMargin: props.rootMargin,
      threshold: 0.1,
    })

    if (imageEl.value) {
      observer.observe(imageEl.value)
    }
  }

  const loadImage = () => {
    isLoaded.value = true
  }

  onMounted(() => {
    if (props.lazy) {
      addLazyLoadListener()
    } else {
      loadImage()
    }
  })

  onBeforeUnmount(() => {
    if (observer) {
      observer.disconnect()
      observer = null
    }
  })
</script>

<style lang="scss" scoped>
  .ep-image {
    position: relative;
    display: block;
    overflow: hidden;
    max-width: 100%;

    &--rounded {
      border-radius: var(--border-radius--large);
    }

    &--loading {
      background: var(--interface-surface);

      &::after {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        animation: shimmer 1.5s infinite;
        background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
        content: '';
      }
    }
  }

  .ep-image__img {
    display: block;
    width: 100%;
    height: auto;
    opacity: 0;
    transition: opacity 0.4s ease-in-out;
    animation: fadeIn 0.4s ease-in-out forwards;
  }

  .ep-image__placeholder {
    position: absolute;
    top: 0;
    left: 0;
  }

  @keyframes fadeIn {
    to {
      opacity: 1;
    }
  }

  @keyframes shimmer {
    0% {
      transform: translateX(-100%);
    }

    100% {
      transform: translateX(100%);
    }
  }
</style>

// packages/epicenter-components-react/src/components/lazy-image/EpLazyImage.tsx
import React, { useState, useRef, useEffect, CSSProperties } from 'react';

export interface EpLazyImageProps {
  /** The alt text for the image. */
  alt?: string;
  /** The aspect ratio of the image (e.g., '16 / 9'). */
  aspectRatio?: string;
  /** Additional CSS class name for the image element. */
  className?: string;
  /** The height of the image. */
  height?: string | number;
  /** If true, enables lazy loading using Intersection Observer. */
  lazy?: boolean;
  /** How the image fits within its container. */
  objectFit?: string;
  /** URL of the placeholder image to display while loading. */
  placeholder?: string;
  /** The background color of the placeholder. */
  placeholderColor?: string;
  /** The opacity of the placeholder. */
  placeholderOpacity?: number;
  /** The root margin for the Intersection Observer. */
  rootMargin?: string;
  /** If true, applies rounded corners to the image. */
  rounded?: boolean;
  /** The source URL of the image. */
  src: string;
  /** The width of the image. */
  width?: string | number;
}

/**
 * EpLazyImage - An image component with lazy loading, aspect ratio, and shimmer loading
 */
export const EpLazyImage: React.FC<EpLazyImageProps> = ({
  alt = '',
  aspectRatio = '16 / 10',
  className = '',
  height = '100%',
  lazy = true,
  objectFit = 'contain',
  placeholder = '',
  placeholderColor = '#f5f5f5',
  placeholderOpacity = 1,
  rootMargin = '0px 0px 100px 0px',
  rounded = true,
  src,
  width = '100%',
}) => {
  const [isLoaded, setIsLoaded] = useState(false);
  const imageRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!lazy) {
      setIsLoaded(true);
      return;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setIsLoaded(true);
            observer.unobserve(entry.target);
          }
        });
      },
      { rootMargin, threshold: 0.1 }
    );

    if (imageRef.current) {
      observer.observe(imageRef.current);
    }

    return () => {
      observer.disconnect();
    };
  }, [lazy, rootMargin]);

  const placeholderStyle: CSSProperties = {
    width,
    height,
    aspectRatio,
    backgroundColor: placeholderColor,
    opacity: placeholderOpacity,
    backgroundImage: placeholder ? `url(${placeholder})` : undefined,
    backgroundSize: 'cover',
  };

  const classes = [
    'ep-image',
    rounded && 'ep-image--rounded',
    !isLoaded && 'ep-image--loading',
  ].filter(Boolean).join(' ');

  return (
    <div ref={imageRef} className={classes}>
      {isLoaded ? (
        <img
          src={src}
          alt={alt}
          width={typeof width === 'number' ? width : undefined}
          height={typeof height === 'number' ? height : undefined}
          className={`ep-image__img${className ? ` ${className}` : ''}`}
          style={{ aspectRatio, objectFit } as CSSProperties}
        />
      ) : (
        <div className="ep-image__placeholder" style={placeholderStyle} />
      )}
    </div>
  );
};

EpLazyImage.displayName = 'EpLazyImage';
