// packages/epicenter-components-react/src/components/checkbox/EpCheckbox.tsx
import React, { ChangeEvent, ReactNode, forwardRef } from 'react';

export interface EpCheckboxProps {
  /** The ID of the checkbox */
  id: string;
  /** The label for the checkbox */
  label: string;
  /** The name of the checkbox */
  name: string;
  /** The value of the checkbox */
  value: string;
  /** Whether the checkbox is checked */
  checked?: boolean;
  /** Whether the checkbox is disabled */
  disabled?: boolean;
  /** Whether the checkbox is indeterminate */
  indeterminate?: boolean;
  /** Whether the checkbox is required */
  required?: boolean;
  /** Callback when checkbox state changes */
  onChange?: (event: ChangeEvent<HTMLInputElement>) => void;
  /** Additional CSS classes */
  className?: string;
  /** Optional children to override label */
  children?: ReactNode;
}

/**
 * EpCheckbox - A checkbox input component with label and various states
 */
export const EpCheckbox = forwardRef<HTMLInputElement, EpCheckboxProps>(({
  id,
  label,
  name,
  value,
  checked = false,
  disabled = false,
  indeterminate = false,
  required = false,
  onChange,
  className = '',
  children,
}, ref) => {
  const classes = ['ep-checkbox'];
  
  if (checked) classes.push('ep-checkbox--checked');
  if (disabled) classes.push('ep-checkbox--disabled');
  if (indeterminate) classes.push('ep-checkbox--indeterminate');
  if (className) classes.push(className);

  return (
    <label htmlFor={id} className={classes.join(' ')}>
      <input
        ref={ref}
        id={id}
        type="checkbox"
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        required={required}
        onChange={onChange}
      />
      {children || label}
    </label>
  );
});

EpCheckbox.displayName = 'EpCheckbox';

// packages/epicenter-vue-components/src/components/checkbox/EpCheckbox.vue
<template>
  <label
    :for="id"
    :class="['ep-checkbox', classes]"
  >
    <input
      :id="id"
      v-model="modelValue"
      type="checkbox"
      :name
      :value
      :checked
      :disabled
      :indeterminate
      :required
    >
    {{ label }}
  </label>
</template>

<script setup>
  defineOptions({
    name: 'EpCheckbox'
  })
  import { computed } from 'vue'

  const modelValue = defineModel({
    type: Boolean,
    required: true
  })

  const props = defineProps({
    // required
    id: {
      type: String,
      required: true
    },
    label: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    value: {
      type: String,
      required: true
    },
    // optional
    checked: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    indeterminate: {
      type: Boolean,
      default: false
    },
    required: {
      type: Boolean,
      default: false
    },
  })

  const classes = computed(() => {
    return {
      'ep-checkbox--checked': modelValue.value,
      'ep-checkbox--disabled': props.disabled,
      'ep-checkbox--indeterminate': props.indeterminate,
    }
  })
</script>
