// packages/epicenter-components-vue/src/components/table/EpTableSortableHeader.vue
<script setup lang="ts">
  import ArrowDown01 from '@ericpitcock/epicenter-icons-vue/ArrowDown01'
  import ArrowUp01 from '@ericpitcock/epicenter-icons-vue/ArrowUp01'
  import { computed } from 'vue'

  import type { TableColumn, SortOrder } from '../../types'

  interface EpTableSortableHeaderProps {
    cellWidths?: Record<string, string>[]
    column: TableColumn
    columnIndex?: number | null
    sortColumn: string
    sortOrder: SortOrder
  }

  const {
    sortColumn,
    column,
    cellWidths = [],
    columnIndex = null,
  } = defineProps<EpTableSortableHeaderProps>()

  const emit = defineEmits<{
    sort: [key: string]
  }>()

  const headerClass = computed(() => {
    return [
      'ep-table-sortable-header',
      { 'ep-table-sortable-header--active': sortColumn === column.key }
    ]
  })

  const isSorted = computed(() => {
    return column.sortable && sortColumn === column.key
  })
</script>

<template>
  <th
    :style="columnIndex != null ? cellWidths[columnIndex] : undefined"
    @click="emit('sort', column.key)"
  >
    <div :class="headerClass">
      {{ column.label }}
      <ArrowUp01 v-if="isSorted && sortOrder === 'asc'" />
      <ArrowDown01 v-if="isSorted && sortOrder === 'desc'" />
    </div>
  </th>
</template>

// packages/epicenter-components-react/src/components/table/EpTableSortableHeader.tsx
import React, { useMemo } from 'react'

import type { Column } from './EpTable'

export type SortOrder = 'asc' | 'desc'

export interface EpTableSortableHeaderProps {
  /** Array of width values for each column cell */
  cellWidths?: React.CSSProperties[]
  /** Column configuration */
  column: Column
  /** Column index */
  columnIndex?: number
  /** Callback when header is clicked for sorting */
  onSort: (columnKey: string) => void
  /** Currently sorted column key */
  sortColumn: string
  /** Current sort order */
  sortOrder: SortOrder
}

/**
 * EpTableSortableHeader - Sortable table header cell
 * 
 * Displays column header with sort indicators and handles sort toggle.
 */
export const EpTableSortableHeader: React.FC<EpTableSortableHeaderProps> = ({
  column,
  cellWidths = [],
  columnIndex = 0,
  sortColumn,
  sortOrder,
  onSort
}) => {
  const headerClass = useMemo(() => {
    const classes = ['ep-table-sortable-header']
    if (sortColumn === column.key) {
      classes.push('ep-table-sortable-header--active')
    }
    return classes.join(' ')
  }, [sortColumn, column.key])

  const isSorted = column.sortable && sortColumn === column.key

  return (
    <th
      style={cellWidths[columnIndex]}
      onClick={() => onSort(column.key)}
    >
      <div className={headerClass}>
        {column.label}
        {isSorted && sortOrder === 'asc' && (
          <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M8 4l4 6H4z" />
          </svg>
        )}
        {isSorted && sortOrder === 'desc' && (
          <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M8 12l-4-6h8z" />
          </svg>
        )}
      </div>
    </th>
  )
}
