// packages/epicenter-vue-components/src/components/key-value-table/EpKeyValueTable.vue
<template>
  <ep-flex class="ep-key-value-table flex-col gap-10">
    <template
      v-for="section in processedData"
      :key="section.name"
    >
      <h3
        v-if="sectionHeaders"
        class="text-style--section"
      >
        {{ section.name }}
      </h3>
      <table>
        <tr
          v-for="(value, key) in section.data"
          :key="key"
        >
          <td
            class="text--subtle"
            :style="{ width: keyColumnWidth }"
          >
            {{ key }}
          </td>
          <td :class="{ 'ep-flex gap-5': showActionsMenu }">
            {{ value }}
            <template v-if="$slots['actions-menu']">
              <slot
                name="actions-menu"
                v-bind="{ key, value }"
              />
            </template>
          </td>
        </tr>
      </table>
    </template>
  </ep-flex>
</template>

<script setup>
  import { computed } from 'vue'

  import EpFlex from '../flexbox/EpFlex.vue'

  const props = defineProps({
    data: {
      type: [Array, Object],
      required: true
    },
    commonKeyWidth: {
      type: Boolean,
      default: false
    },
    sectionHeaders: {
      type: Boolean,
      default: false
    },
    showActionsMenu: {
      type: Boolean,
      default: false
    }
  })

  const processedData = computed(() => {
    if (Array.isArray(props.data)) {
      return props.data
    }

    return [props.data]
  })

  const keyColumnWidth = computed(() => {
    if (!props.commonKeyWidth) {
      return 'auto'
    }

    let maxKeyLength = 0

    for (const section of processedData.value) {
      for (const key in section.data) {
        maxKeyLength = Math.max(maxKeyLength, key.length)
      }
    }

    return `${maxKeyLength}ch`
  })
</script>

// packages/epicenter-components-react/src/components/key-value-table/EpKeyValueTable.tsx
import React, { useMemo } from 'react'

import { EpFlex } from '../flexbox/EpFlex'

export interface KeyValueSection {
  data: Record<string, any>
  name: string
}

export interface EpKeyValueTableProps {
  /** Additional CSS classes */
  className?: string
  /** Use common width for all key columns based on longest key */
  commonKeyWidth?: boolean
  /** Table data - either a single object or array of section objects */
  data: Record<string, any> | KeyValueSection[]
  /** Custom value renderer */
  renderValue?: (key: string, value: any) => React.ReactNode
  /** Show section headers */
  sectionHeaders?: boolean
}

/**
 * EpKeyValueTable - Simple key-value pair table
 * 
 * Displays data as key-value pairs with optional sections and custom value rendering.
 */
export const EpKeyValueTable: React.FC<EpKeyValueTableProps> = ({
  data,
  commonKeyWidth = false,
  sectionHeaders = false,
  renderValue,
  className = ''
}) => {
  const processedData = useMemo((): KeyValueSection[] => {
    if (Array.isArray(data)) {
      return data
    }
    return [{ name: '', data }]
  }, [data])

  const keyColumnWidth = useMemo(() => {
    if (!commonKeyWidth) {
      return 'auto'
    }

    let maxKeyLength = 0

    for (const section of processedData) {
      for (const key in section.data) {
        maxKeyLength = Math.max(maxKeyLength, key.length)
      }
    }

    return `${maxKeyLength}ch`
  }, [commonKeyWidth, processedData])

  return (
    <EpFlex className={`ep-key-value-table flex-col gap-10${className ? ` ${className}` : ''}`}>
      {processedData.map((section, sectionIndex) => (
        <React.Fragment key={section.name || sectionIndex}>
          {sectionHeaders && section.name && (
            <h3 className="text-style--section">{section.name}</h3>
          )}
          <table>
            <tbody>
              {Object.entries(section.data).map(([key, value]) => (
                <tr key={key}>
                  <td
                    className="text--subtle"
                    style={{ width: keyColumnWidth }}
                  >
                    {key}
                  </td>
                  <td className="ep-flex gap-5">
                    {renderValue ? renderValue(key, value) : value}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </React.Fragment>
      ))}
    </EpFlex>
  )
}
