// packages/epicenter-react-components/src/components/banner/EpBanner.tsx
import React, { ReactNode } from 'react'

export interface EpBannerProps {
  /**
   * Icon displayed at the start of the banner
   */
  icon?: ReactNode
  /**
   * Main message content of the banner
   */
  message?: ReactNode
  /**
   * Secondary message or additional information
   */
  subtext?: ReactNode
  /**
   * Dismiss button or action
   */
  dismiss?: ReactNode
  /**
   * Handler called when the banner is dismissed
   */
  onDismissed?: () => void
}

const EpBanner: React.FC<EpBannerProps> = ({
  icon,
  message,
  subtext,
  dismiss,
  onDismissed
}) => {
  const handleDismiss = () => {
    onDismissed?.()
  }

  return (
    <div className="ep-banner">
      <div className="ep-banner__color-strip" />
      <div className="ep-banner__body">
        {icon && (
          <div className="ep-banner__body__icon">
            {icon}
          </div>
        )}
        <div className="ep-banner__body__message">
          <div className="ep-banner__body__message__text font-size--small">
            {message}
          </div>
          {subtext && (
            <div className="ep-banner__body__message__subtext">
              {subtext}
            </div>
          )}
        </div>
        {dismiss && React.cloneElement(dismiss as React.ReactElement, {
          onClick: handleDismiss
        })}
      </div>
    </div>
  )
}

export default EpBanner

// packages/epicenter-vue-components/src/components/banner/EpBanner.vue
<template>
  <div class="ep-banner">
    <div class="ep-banner__color-strip" />
    <div class="ep-banner__body">
      <div
        v-if="$slots.icon"
        class="ep-banner__body__icon"
      >
        <!-- @slot Icon displayed at the start of the banner -->
        <slot name="icon" />
      </div>
      <div class="ep-banner__body__message">
        <div class="ep-banner__body__message__text font-size--small">
          <!-- @slot Main message content of the banner -->
          <slot name="message" />
        </div>
        <div
          v-if="$slots.subtext"
          class="ep-banner__body__message__subtext"
        >
          <!-- @slot Secondary message or additional information -->
          <slot name="subtext" />
        </div>
      </div>
      <!-- @slot Dismiss button or action. Receives dismissBanner function as scoped prop. -->
      <slot
        name="dismiss"
        v-bind="{ dismissBanner }"
      />
    </div>
  </div>
</template>

<script setup>
  defineOptions({
    name: 'EpBanner'
  })

  const emit = defineEmits([
    /**
     * Emitted when the banner is dismissed.
     */
    'dismissed'
  ])
  const dismissBanner = () => emit('dismissed')
</script>
