// packages/epicenter-components-react/src/components/inline-edit/EpInlineEdit.tsx
import React, { useCallback, useRef, useState, useEffect, ReactNode, KeyboardEvent } from 'react';
import { ArrowTurnBackward } from '@ericpitcock/epicenter-icons-react/ArrowTurnBackward.jsx';

export interface EpInlineEditProps {
  /** If true, disables editing. */
  disabled?: boolean;
  /** The current value of the editable text */
  value: string;
  /** Callback when the value is saved */
  onSave?: (value: string) => void;
  /** Callback when the value changes */
  onChange?: (value: string) => void;
  /** Optional icon displayed on the left side of the editable text */
  iconLeft?: ReactNode;
}

/**
 * EpInlineEdit - An inline editable text component
 */
export const EpInlineEdit: React.FC<EpInlineEditProps> = ({
  disabled = false,
  value,
  onSave,
  onChange,
  iconLeft,
}) => {
  const contentRef = useRef<HTMLDivElement>(null);
  const [isEditing, setIsEditing] = useState(false);
  const originalValueRef = useRef('');
  const cancelledRef = useRef(false);
  const [hasChanged, setHasChanged] = useState(false);

  const onFocus = useCallback(() => {
    setIsEditing(true);
    originalValueRef.current = value;
    setHasChanged(false);
  }, [value]);

  const onInput = useCallback(() => {
    const current = contentRef.current?.textContent ?? '';
    setHasChanged(current !== originalValueRef.current);
  }, []);

  const save = useCallback(() => {
    const newValue = contentRef.current?.textContent ?? '';
    onChange?.(newValue);
    setIsEditing(false);
    setHasChanged(false);
    onSave?.(newValue);
  }, [onChange, onSave]);

  const onBlur = useCallback(() => {
    if (cancelledRef.current) {
      cancelledRef.current = false;
      return;
    }
    save();
  }, [save]);

  const onKeyDown = useCallback((event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      contentRef.current?.blur();
    }
    if (event.key === 'Escape') {
      cancelledRef.current = true;
      if (contentRef.current) {
        contentRef.current.textContent = originalValueRef.current;
      }
      onChange?.(originalValueRef.current);
      setIsEditing(false);
      contentRef.current?.blur();
    }
  }, [onChange]);

  const onSaveClick = useCallback(() => {
    save();
    contentRef.current?.blur();
  }, [save]);

  const onCancelClick = useCallback(() => {
    cancelledRef.current = true;
    if (contentRef.current) {
      contentRef.current.textContent = originalValueRef.current;
    }
    onChange?.(originalValueRef.current);
    setIsEditing(false);
    setHasChanged(false);
    contentRef.current?.blur();
  }, [onChange]);

  // Sync contenteditable text when value changes externally
  useEffect(() => {
    if (contentRef.current && contentRef.current.textContent !== value) {
      contentRef.current.textContent = value;
    }
  }, [value]);

  const classes = [
    'ep-inline-edit',
    isEditing && 'ep-inline-edit--editing',
    disabled && 'ep-inline-edit--disabled',
  ].filter(Boolean).join(' ');

  return (
    <div className={classes}>
      {iconLeft && (
        <span className="ep-inline-edit__icon">{iconLeft}</span>
      )}
      <div
        ref={contentRef}
        className="ep-inline-edit__content"
        contentEditable={!disabled}
        spellCheck={false}
        suppressContentEditableWarning
        onFocus={onFocus}
        onBlur={onBlur}
        onInput={onInput}
        onKeyDown={onKeyDown}
      >
        {value}
      </div>
      {isEditing && hasChanged && (
        <div className="ep-inline-edit__actions ep-flex gap-10">
          <div
            className="ep-flex gap-5 align-center"
            onMouseDown={(e) => { e.preventDefault(); onSaveClick(); }}
          >
            Save
            <ArrowTurnBackward style={{ '--ep-icon-size': '1.4rem' } as React.CSSProperties} />
          </div>
          <div
            className="ep-flex gap-6 align-center"
            onMouseDown={(e) => { e.preventDefault(); onCancelClick(); }}
          >
            Cancel
            <svg
              width="21"
              height="12"
              viewBox="0 0 28 16"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect x="0.5" y="0.5" width="27" height="15" rx="2" stroke="currentColor" />
              <text
                x="14"
                y="11.5"
                textAnchor="middle"
                fill="currentColor"
                fontSize="9"
                fontFamily="sans-serif"
                fontWeight="500"
                letterSpacing="1"
              >ESC</text>
            </svg>
          </div>
        </div>
      )}
    </div>
  );
};

EpInlineEdit.displayName = 'EpInlineEdit';

// packages/epicenter-components-vue/src/components/inline-edit/EpInlineEdit.vue
<script setup lang="ts">
  import ArrowTurnBackward from '@ericpitcock/epicenter-icons-vue/ArrowTurnBackward'
  import { ref, watch } from 'vue'

  import EpFlex from '../flexbox/EpFlex.vue'

  interface EpInlineEditProps {
    /** If true, disables editing. */
    disabled?: boolean
  }

  const { disabled = false } = defineProps<EpInlineEditProps>()

  const emit = defineEmits<{
    save: [value: string]
  }>()

  const modelValue = defineModel<string>({ required: true })

  const contentRef = ref<HTMLDivElement | null>(null)
  const isEditing = ref(false)
  const originalValue = ref('')
  const cancelled = ref(false)
  const hasChanged = ref(false)

  const onFocus = (): void => {
    isEditing.value = true
    originalValue.value = modelValue.value
    hasChanged.value = false
  }

  const onInput = (): void => {
    const current = contentRef.value?.textContent ?? ''
    hasChanged.value = current !== originalValue.value
  }

  const save = (): void => {
    const newValue = contentRef.value?.textContent ?? ''
    modelValue.value = newValue
    isEditing.value = false
    hasChanged.value = false
    emit('save', newValue)
  }

  const onBlur = (): void => {
    if (cancelled.value) {
      cancelled.value = false
      return
    }
    save()
  }

  const onKeyDown = (event: KeyboardEvent): void => {
    if (event.key === 'Enter') {
      event.preventDefault()
      contentRef.value?.blur()
    }
    if (event.key === 'Escape') {
      cancelled.value = true
      if (contentRef.value) {
        contentRef.value.textContent = originalValue.value
      }
      modelValue.value = originalValue.value
      isEditing.value = false
      contentRef.value?.blur()
    }
  }

  const onSaveClick = (): void => {
    save()
    contentRef.value?.blur()
  }

  const onCancelClick = (): void => {
    cancelled.value = true
    if (contentRef.value) {
      contentRef.value.textContent = originalValue.value
    }
    modelValue.value = originalValue.value
    isEditing.value = false
    hasChanged.value = false
    contentRef.value?.blur()
  }

  // Sync contenteditable text when modelValue changes externally
  watch(modelValue, (newVal) => {
    if (contentRef.value && contentRef.value.textContent !== newVal) {
      contentRef.value.textContent = newVal
    }
  })
</script>

<template>
  <div :class="[
    'ep-inline-edit',
    {
      'ep-inline-edit--editing': isEditing,
      'ep-inline-edit--disabled': disabled,
    }
  ]">
    <span
      v-if="$slots['icon-left']"
      class="ep-inline-edit__icon"
    >
      <!-- @slot Optional icon displayed on the left side of the editable text -->
      <slot name="icon-left" />
    </span>
    <div
      ref="contentRef"
      class="ep-inline-edit__content"
      :contenteditable="!disabled"
      spellcheck="false"
      @focus="onFocus"
      @blur="onBlur"
      @input="onInput"
      @keydown="onKeyDown"
    >
      {{ modelValue }}
    </div>
    <!-- isEditing && hasChanged -->
    <ep-flex
      v-if="isEditing && hasChanged"
      class="ep-inline-edit__actions gap-10"
    >
      <ep-flex
        class="gap-5 align-center"
        @mousedown.prevent="onSaveClick"
      >
        Save
        <ArrowTurnBackward style="--ep-icon-size: 1.4rem;" />
      </ep-flex>
      <ep-flex
        class="gap-6 align-center"
        @mousedown.prevent="onCancelClick"
      >
        Cancel
        <svg
          width="21"
          height="12"
          viewBox="0 0 28 16"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <rect
            x="0.5"
            y="0.5"
            width="27"
            height="15"
            rx="2"
            stroke="currentColor"
          />
          <text
            x="14"
            y="11.5"
            text-anchor="middle"
            fill="currentColor"
            font-size="9"
            font-family="sans-serif"
            font-weight="500"
            letter-spacing="1"
          >ESC</text>
        </svg>
      </ep-flex>
    </ep-flex>
  </div>
</template>
