// packages/epicenter-components-react/src/components/button/EpButton.tsx
import { type ReactNode, type ElementType, type Ref, type MouseEvent, type HTMLAttributes } from 'react';

type ButtonSize = 'small' | 'default' | 'large' | 'xlarge';
type ButtonType = 'button' | 'submit';

export type EpButtonProps = {
  /** The aria-label of the button */
  ariaLabel?: string;
  /** Custom component to render as (e.g., a router Link component) */
  as?: ElementType;
  /** Button content */
  children?: ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** If true, the button will be disabled */
  disabled?: boolean;
  /** URL destination (renders as anchor when provided) */
  href?: string;
  /** Icon displayed on the left side of the button label */
  iconLeft?: ReactNode;
  /** Icon displayed on the right side of the button label */
  iconRight?: ReactNode;
  /** Click handler */
  onClick?: (event: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void;
  /** Ref forwarded to the root element */
  ref?: Ref<HTMLButtonElement | HTMLAnchorElement>;
  /** The size of the button */
  size?: ButtonSize;
  /** Destination path (used with the `as` prop for router links) */
  to?: string;
  /** The type of the button (only applies when rendered as button element) */
  type?: ButtonType;
} & Omit<HTMLAttributes<HTMLElement>, 'type'>;

/**
 * EpButton - A versatile button component that can render as a button, link, or router link
 */
export function EpButton({
  as,
  size = 'default',
  ariaLabel,
  disabled = false,
  type = 'button',
  to,
  href,
  iconLeft,
  iconRight,
  children,
  className = '',
  onClick,
  ref,
  ...rest
}: EpButtonProps) {
  const Element: ElementType = as ?? (href ? 'a' : 'button');

  const computedClasses = [
    'ep-button',
    size !== 'default' && `ep-button--${size}`,
    disabled && 'ep-button--disabled',
    className,
  ].filter(Boolean).join(' ');

  const handleClick = (e: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => {
    if (disabled && Element !== 'button') {
      e.preventDefault();
      return;
    }
    onClick?.(e);
  };

  const elementProps: Record<string, unknown> = {
    className: computedClasses,
    ref,
    onClick: handleClick,
    'aria-label': ariaLabel || undefined,
    ...rest,
  };

  if (Element === 'button') {
    elementProps.type = type;
    elementProps.disabled = disabled;
  } else {
    if (href) elementProps.href = href;
    if (to) elementProps.to = to;
    if (disabled) elementProps['aria-disabled'] = true;
  }

  return (
    <Element {...elementProps}>
      {iconLeft && (
        <span className="ep-button__icon ep-button__icon--left">
          {iconLeft}
        </span>
      )}
      {children && (
        <span className="ep-button__label">{children}</span>
      )}
      {iconRight && (
        <span className="ep-button__icon ep-button__icon--right">
          {iconRight}
        </span>
      )}
    </Element>
  );
}

// packages/epicenter-vue-components/src/components/button/EpButton.vue
<template>
  <component
    :is="element"
    :type
    :class="['ep-button', computedClasses]"
    :aria-label="ariaLabel ? ariaLabel : label"
    :disabled="disabled"
  >
    <span
      v-if="iconLeft"
      class="ep-button__icon ep-button__icon--left"
    >
      <ep-icon v-bind="iconLeft" />
    </span>
    <span
      v-if="label"
      class="ep-button__label"
    >
      {{ label }}
    </span>
    <span
      v-if="iconRight"
      class="ep-button__icon ep-button__icon--right"
    >
      <ep-icon v-bind="iconRight" />
    </span>
  </component>
</template>

<script setup>
  import { computed, useAttrs } from 'vue'

  import EpIcon from '../icon/EpIcon.vue'

  defineOptions({
    name: 'EpButton'
  })

  const props = defineProps({
    /**
     * The size of the button.
     */
    size: {
      type: String,
      default: 'default',
      validator: (value) => [
        'small',
        'default',
        'large',
        'xlarge',
      ].includes(value)
    },
    /**
     * The aria-label of the button.
     */
    ariaLabel: {
      type: String,
      default: ''
    },
    /**
     * The label of the button.
     */
    label: {
      type: String,
      default: ''
    },
    /**
     * The icon to display on the left side of the button.
     */
    iconLeft: {
      type: Object,
      default: undefined
    },
    /**
     * The icon to display on the right side of the button.
     */
    iconRight: {
      type: Object,
      default: undefined
    },
    /**
     * If `true`, the button will be disabled.
     */
    disabled: {
      type: Boolean,
      default: false
    },
    /**
     * The  type of the button.
     */
    type: {
      type: String,
      default: 'button',
      validator: (value) => [
        'button',
        'submit',
      ].includes(value)
    },
  })

  const element = computed(() => {
    const { to, href } = useAttrs()
    return to ? 'router-link' : href ? 'a' : 'button'
  })

  const computedClasses = computed(() => ({
    [`ep-button--${props.size}`]: props.size !== 'default',
    'ep-button--icon-right': props.iconRight,
    'ep-button--icon-left': props.iconLeft,
    'ep-button--disabled': props.disabled,
  }))
</script>
