// packages/epicenter-react-components/src/components/button/EpButton.jsx
import React from 'react';
import PropTypes from 'prop-types';
import EpIcon from '../icon/EpIcon';

const EpButton = ({
  element: Element = 'button',
  size = 'default',
  title,
  label,
  iconLeft,
  iconRight,
  disabled = false,
  ariaLabel,
  className = '',
  ...rest
}) => {
  const computedClasses = `ep-button ep-button--${size} ${className}`;

  return (
    <Element
      className={computedClasses}
      title={title}
      aria-label={ariaLabel || label}
      disabled={disabled}
      {...rest}
    >
      {iconLeft && (
        <span className="ep-button__icon ep-button__icon--left">
          <EpIcon {...iconLeft} />
        </span>
      )}
      {label && <span className="ep-button__label">{label}</span>}
      {iconRight && (
        <span className="ep-button__icon ep-button__icon--right">
          <EpIcon {...iconRight} />
        </span>
      )}
    </Element>
  );
};

EpButton.propTypes = {
  element: PropTypes.elementType,
  size: PropTypes.oneOf(['small', 'default', 'large', 'xlarge']),
  title: PropTypes.string,
  label: PropTypes.string,
  iconLeft: PropTypes.object,
  iconRight: PropTypes.object,
  disabled: PropTypes.bool,
  ariaLabel: PropTypes.string,
  className: PropTypes.string,
};

export default EpButton;

// packages/epicenter-vue-components/src/components/button/EpButton.vue
<template>
  <component
    :is="element"
    :type
    :class="['ep-button', computedClasses]"
    :title
    :aria-label="ariaLabel ? ariaLabel : label"
    :disabled="disabled"
  >
    <span
      v-if="iconLeft"
      class="ep-button__icon ep-button__icon--left"
    >
      <ep-icon v-bind="iconLeft" />
    </span>
    <span
      v-if="label"
      class="ep-button__label"
    >
      {{ label }}
    </span>
    <span
      v-if="iconRight"
      class="ep-button__icon ep-button__icon--right"
    >
      <ep-icon v-bind="iconRight" />
    </span>
  </component>
</template>

<script setup>
  defineOptions({
    name: 'EpButton'
  })

  import { computed, useAttrs } from 'vue'
  import EpIcon from '../icon/EpIcon.vue'

  const props = defineProps({
    size: {
      type: String,
      default: 'default',
      validator: (value) => [
        'small',
        'default',
        'large',
        'xlarge'
      ].includes(value)
    },
    title: {
      type: String,
      default: ''
    },
    ariaLabel: {
      type: String,
      default: ''
    },
    label: {
      type: String,
      default: ''
    },
    iconLeft: {
      type: Object,
      default: undefined
    },
    iconRight: {
      type: Object,
      default: undefined
    },
    disabled: {
      type: Boolean,
      default: false
    },
    isMenuItem: {
      type: Boolean,
      default: false
    },
    isActiveMenuItem: {
      type: Boolean,
      default: false
    },
    type: {
      type: String,
      default: 'button',
      validator: (value) => ['button', 'submit'].includes(value)
    },
  })

  const element = computed(() => {
    const attrs = useAttrs()

    if (attrs.to) {
      return 'router-link'
    }
    if (attrs.href) {
      return 'a'
    }
    return 'button'
  })

  const computedClasses = computed(() => ({
    [`ep-button--${props.size}`]: props.size != 'default',
    'ep-button--icon-right': props.iconRight,
    'ep-button--icon-left': props.iconLeft,
    'ep-button--disabled': props.disabled,
    'ep-button--menu-item': props.isMenuItem,
    'ep-button--menu-item--active': props.isActiveMenuItem
  }))
</script>
