// packages/epicenter-vue-components/src/components/notification/EpNotifications.vue
<template>
  <ep-container class="ep-container-default ep-container--sticky-header">
    <template #header>
      <ep-header>
        <template #left>
          <h2>
            {{ notificationsTitle }}
          </h2>
        </template>
        <template #right>
          <ep-button
            v-show="!isNotificationsEmpty"
            @click="emit('clear-notifications')"
          >
            Clear all
          </ep-button>
        </template>
      </ep-header>
    </template>
    <ep-empty-state v-if="isNotificationsEmpty">
      {{ emptyStateMessage }}
    </ep-empty-state>
    <template v-else>
      <ep-flex class="flex-col gap-10">
        <transition-group name="fade">
          <EpNotification
            v-for="notification in notifications"
            :key="notification.id"
            v-bind="notification"
            @dismiss="emit('remove-notification', notification.id)"
          />
        </transition-group>
      </ep-flex>
    </template>
  </ep-container>
</template>

<script setup>
  import { computed } from 'vue'

  import EpButton from '../button/EpButton.vue'
  import EpContainer from '../container/EpContainer.vue'
  import EpEmptyState from '../empty-state/EpEmptyState.vue'
  import EpFlex from '../flexbox/EpFlex.vue'
  import EpHeader from '../header/EpHeader.vue'
  import EpNotification from '../notification/EpNotification.vue'

  defineOptions({
    name: 'EpNotifications'
  })

  const props = defineProps({
    emptyStateMessage: {
      type: String,
      default: 'You’re all caught up!'
    },
    notificationsTitle: {
      type: String,
      default: 'Notifications'
    },
    notifications: {
      type: Array,
      default: () => []
    }
  })

  const emit = defineEmits([
    'remove-notification',
    'clear-notifications'
  ])

  const isNotificationsEmpty = computed(() => {
    return props.notifications.length === 0
  })
</script>

// packages/epicenter-components-react/src/components/notification/EpNotifications.tsx
import React, { useMemo } from 'react'

import { EpButton } from '../button/EpButton'
import { EpContainer } from '../container/EpContainer'
import { EpEmptyState } from '../empty-state/EpEmptyState'
import { EpFlex } from '../flexbox/EpFlex'
import { EpHeader } from '../header/EpHeader'

import { EpNotification } from './EpNotification'
import type { EpNotificationProps } from './EpNotification'

export interface NotificationItem extends Omit<EpNotificationProps, 'onDismiss'> {
  id: string
  message: string
  timestamp?: string
}

export interface EpNotificationsProps {
  /**
   * Empty state message when there are no notifications
   * @default "You're all caught up!"
   */
  emptyStateMessage?: string
  /**
   * Array of notification items
   * @default []
   */
  notifications?: NotificationItem[]
  /**
   * Title for the notifications panel
   * @default 'Notifications'
   */
  notificationsTitle?: string
  /**
   * Handler called when all notifications are cleared
   */
  onClearNotifications?: () => void
  /**
   * Handler called when a notification is removed
   */
  onRemoveNotification?: (id: string) => void
}

export const EpNotifications: React.FC<EpNotificationsProps> = ({
  emptyStateMessage = "You're all caught up!",
  notificationsTitle = 'Notifications',
  notifications = [],
  onRemoveNotification,
  onClearNotifications
}) => {
  const isNotificationsEmpty = useMemo(() => {
    return notifications.length === 0
  }, [notifications.length])

  return (
    <EpContainer className="ep-container-default ep-container--sticky-header">
      <EpHeader
        left={<h2>{notificationsTitle}</h2>}
        right={
          !isNotificationsEmpty && (
            <EpButton onClick={onClearNotifications}>
              Clear all
            </EpButton>
          )
        }
      />
      {isNotificationsEmpty ? (
        <EpEmptyState>
          {emptyStateMessage}
        </EpEmptyState>
      ) : (
        <EpFlex className="flex-col gap-10">
          {notifications.map((notification) => (
            <EpNotification
              key={notification.id}
              {...notification}
              onDismiss={() => onRemoveNotification?.(notification.id)}
            />
          ))}
        </EpFlex>
      )}
    </EpContainer>
  )
}
