// packages/epicenter-components-vue/src/components/toggle-button/EpToggleButton.vue
<script setup>
  import { computed } from 'vue'

  const props = defineProps({
    /**
     * The label to display inside the button.
     */
    label: {
      type: String,
      default: '',
    },
    /**
     * The class to apply when the button is active.
     */
    activeClass: {
      type: String,
      default: ''
    },
    /**
     * If true, the button is disabled.
     */
    disabled: {
      type: Boolean,
      default: false,
    },
    /**
     * The aria-label for accessibility.
     */
    ariaLabel: {
      type: String,
      default: '',
    },
    /**
     * The size of the button.
     * @values small, default, large, xlarge
     */
    size: {
      type: String,
      default: 'default',
      validator: (value) => ['small', 'default', 'large', 'xlarge'].includes(value)
    },
  })

  const model = defineModel({
    type: Boolean,
    default: false
  })

  function onClick() {
    if (props.disabled) return

    model.value = !model.value
  }

  const computedClasses = computed(() => ({
    [`ep-button--${props.size}`]: props.size !== 'default',
    [`${props.activeClass} ep-button--selected`]: model.value && !props.disabled,
    'ep-button--disabled': props.disabled,
  }))
</script>

<template>
  <button
    :class="['ep-button ep-toggle-button', computedClasses]"
    :aria-label="ariaLabel || label"
    :disabled="disabled"
    @click="onClick"
  >
    <span
      v-if="icon"
      class="ep-toggle-button__icon"
    >
      icon span
    </span>
    <span
      v-if="label"
      class="ep-toggle-button__label"
    >
      {{ label }}
    </span>
  </button>
</template>

// packages/epicenter-components-react/src/components/toggle-button/EpToggleButton.tsx
import { ReactNode } from 'react';

type ButtonSize = 'small' | 'default' | 'large' | 'xlarge';

export interface EpToggleButtonProps {
  /** The class to apply when the button is active */
  activeClass?: string;
  /** The aria-label for accessibility */
  ariaLabel?: string;
  /** Additional CSS classes */
  className?: string;
  /** If true, the button is disabled */
  disabled?: boolean;
  /** Icon to display (ReactNode for flexibility) */
  icon?: ReactNode;
  /** If true, the button is active/selected */
  isActive?: boolean;
  /** The label to display inside the button */
  label?: string;
  /** Callback when button is clicked */
  onClick?: () => void;
  /** The size of the button */
  size?: ButtonSize;
}

/**
 * EpToggleButton - A button component that toggles between active and inactive states
 */
export const EpToggleButton: React.FC<EpToggleButtonProps> = ({
  label = '',
  activeClass = '',
  isActive = false,
  disabled = false,
  ariaLabel,
  size = 'default',
  icon,
  onClick,
  className = '',
}) => {
  const classes = ['ep-button', 'ep-toggle-button'];
  
  if (size !== 'default') classes.push(`ep-button--${size}`);
  if (isActive && !disabled) classes.push(`${activeClass} ep-button--selected`.trim());
  if (disabled) classes.push('ep-button--disabled');
  if (className) classes.push(className);

  const handleClick = () => {
    if (disabled) return;
    if (onClick) onClick();
  };

  return (
    <button
      className={classes.join(' ')}
      aria-label={ariaLabel || label}
      disabled={disabled}
      onClick={handleClick}
    >
      {icon && <span className="ep-toggle-button__icon">{icon}</span>}
      {label && <span className="ep-toggle-button__label">{label}</span>}
    </button>
  );
};

EpToggleButton.displayName = 'EpToggleButton';
