// packages/epicenter-components-react/src/components/header/EpHeader.tsx
import React, { forwardRef, ReactNode } from 'react';

export interface EpHeaderProps {
  [key: string]: unknown;
  center?: ReactNode;
  className?: string;
  left?: ReactNode;
  right?: ReactNode;
}

export const EpHeader = forwardRef<HTMLDivElement, EpHeaderProps>(
  ({ left, center, right, className = '', ...props }, ref) => {
    return (
      <div ref={ref} className={`ep-header ${className}`.trim()} {...props}>
        {left && <div className="ep-header__left">{left}</div>}
        {center && <div className="ep-header__center">{center}</div>}
        {right && <div className="ep-header__right">{right}</div>}
      </div>
    );
  }
);

EpHeader.displayName = 'EpHeader';

// packages/epicenter-vue-components/src/components/header/EpHeader.vue
<template>
  <div class="ep-header">
    <div class="ep-header__content">
      <template v-for="slotName in ['left', 'center', 'right']">
        <div
          v-if="$slots[slotName]"
          :key="slotName"
          :class="`ep-header__content__${slotName}`"
        >
          <slot :name="slotName" />
        </div>
      </template>
    </div>
  </div>
</template>

<script setup>
  defineOptions({
    name: 'EpHeader',
  })
</script>
