// packages/epicenter-react-components/src/components/fieldset/EpFieldset.tsx
import React, { ReactNode } from 'react';

interface EpFieldsetProps {
  /** Label for the fieldset legend */
  label?: string;
  /** Fieldset content */
  children?: ReactNode;
  /** Additional CSS classes */
  className?: string;
}

/**
 * EpFieldset - A fieldset component for grouping form elements
 */
const EpFieldset: React.FC<EpFieldsetProps> = ({ 
  label = '', 
  children, 
  className = '' 
}) => {
  return (
    <fieldset className={`ep-fieldset ep-fieldset--horizontal${className ? ` ${className}` : ''}`}>
      {label && <legend className="ep-fieldset__legend">{label}</legend>}
      <div className="ep-fieldset__content">
        {children}
      </div>
    </fieldset>
  );
};

EpFieldset.displayName = 'EpFieldset';

export default EpFieldset;

// packages/epicenter-components-vue/src/components/fieldset/EpFieldset.vue
<script setup lang="ts">
  interface EpFieldsetProps {
    label?: string
  }

  const { label = '' } = defineProps<EpFieldsetProps>()
</script>

<template>
  <fieldset class="ep-fieldset ep-fieldset--horizontal">
    <legend
      v-if="label"
      class="ep-fieldset__legend"
    >
      {{ label }}
    </legend>

    <div class="ep-fieldset__content">
      <slot />
    </div>
  </fieldset>
</template>
