// packages/epicenter-react-components/src/components/key-value-table/EpKeyValueTable.tsx
import React, { useMemo } from 'react'
import { EpFlex } from '../flexbox/EpFlex'

export interface KeyValueSection {
  name: string
  data: Record<string, any>
}

export interface EpKeyValueTableProps {
  /** Table data - either a single object or array of section objects */
  data: Record<string, any> | KeyValueSection[]
  /** Use common width for all key columns based on longest key */
  commonKeyWidth?: boolean
  /** Show section headers */
  sectionHeaders?: boolean
  /** Custom value renderer */
  renderValue?: (key: string, value: any) => React.ReactNode
  /** Additional CSS classes */
  className?: string
}

/**
 * EpKeyValueTable - Simple key-value pair table
 * 
 * Displays data as key-value pairs with optional sections and custom value rendering.
 */
export const EpKeyValueTable: React.FC<EpKeyValueTableProps> = ({
  data,
  commonKeyWidth = false,
  sectionHeaders = false,
  renderValue,
  className = ''
}) => {
  const processedData = useMemo((): KeyValueSection[] => {
    if (Array.isArray(data)) {
      return data
    }
    return [{ name: '', data }]
  }, [data])

  const keyColumnWidth = useMemo(() => {
    if (!commonKeyWidth) {
      return 'auto'
    }

    let maxKeyLength = 0

    for (const section of processedData) {
      for (const key in section.data) {
        maxKeyLength = Math.max(maxKeyLength, key.length)
      }
    }

    return `${maxKeyLength}ch`
  }, [commonKeyWidth, processedData])

  return (
    <EpFlex className={`ep-key-value-table flex-col gap-10${className ? ` ${className}` : ''}`}>
      {processedData.map((section, sectionIndex) => (
        <React.Fragment key={section.name || sectionIndex}>
          {sectionHeaders && section.name && (
            <h3 className="text-style--section">{section.name}</h3>
          )}
          <table>
            <tbody>
              {Object.entries(section.data).map(([key, value]) => (
                <tr key={key}>
                  <td
                    className="text--subtle"
                    style={{ width: keyColumnWidth }}
                  >
                    {key}
                  </td>
                  <td className="ep-flex gap-5">
                    {renderValue ? renderValue(key, value) : value}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </React.Fragment>
      ))}
    </EpFlex>
  )
}

// packages/epicenter-components-vue/src/components/key-value-table/EpKeyValueTable.vue
<script setup lang="ts">
  import { computed } from 'vue'

  import EpFlex from '../flexbox/EpFlex.vue'

  interface KeyValueSection {
    data: Record<string, unknown>
    name: string
  }

  interface EpKeyValueTableProps {
    commonKeyWidth?: boolean
    data: KeyValueSection | KeyValueSection[]
    sectionHeaders?: boolean
  }

  const {
    data,
    commonKeyWidth = false,
    sectionHeaders = false,
  } = defineProps<EpKeyValueTableProps>()

  const processedData = computed<KeyValueSection[]>(() => {
    if (Array.isArray(data)) {
      return data
    }

    return [data]
  })

  const keyColumnWidth = computed<string>(() => {
    if (!commonKeyWidth) {
      return 'auto'
    }

    let maxKeyLength = 0

    for (const section of processedData.value) {
      for (const key in section.data) {
        maxKeyLength = Math.max(maxKeyLength, key.length)
      }
    }

    return `${maxKeyLength}ch`
  })
</script>

<template>
  <ep-flex class="ep-key-value-table flex-col gap-10">
    <template
      v-for="section in processedData"
      :key="section.name"
    >
      <h3
        v-if="sectionHeaders"
        class="text-style--section"
      >
        {{ section.name }}
      </h3>
      <table>
        <tr
          v-for="(value, key) in section.data"
          :key="key"
        >
          <td
            class="text--subtle"
            :style="{ width: keyColumnWidth }"
          >
            {{ key }}
          </td>
          <td class="ep-flex gap-5">
            <slot
              name="value"
              v-bind="{ key, value }"
            >
              {{ value }}
            </slot>
          </td>
        </tr>
      </table>
    </template>
  </ep-flex>
</template>
