// packages/epicenter-design-system/src/components/banner/EpBanner.vue
<template>
  <div class="ep-banner">
    <div class="ep-banner__color-strip"></div>
    <div class="ep-banner__body">
      <div
        v-if="iconProps.name"
        class="ep-banner__body__icon"
      >
        <ep-icon v-bind="iconProps" />
      </div>
      <div class="ep-banner__body__message">
        <p class="ep-banner__body__message__text font-size--small">{{ message }}
        </p>
        <p
          v-if="subtext"
          class="ep-banner__body__message__subtext"
        >{{ subtext }}</p>
      </div>
      <div
        v-if="dissmissable"
        class="dismiss-button"
      >
        <ep-button
          @click="dismissNotification"
          class="dismiss-button"
          kind="ghost"
          :iconRight="{ name: 'close' }"
        />
      </div>
    </div>
  </div>
</template>

<script>
  import EpButton from '../button/EpButton'
  import EpIcon from '../icon/EpIcon'

  export default {
    name: 'EpBanner',
    emits: ['dismiss'],
    props: {
      bannerStyle: {
        type: String,
        default: 'info' // info, success, warning, error
      },
      dissmissable: {
        type: Boolean,
        default: false
      },
      iconProps: {
        type: Object,
        default: () => ({})
      },
      message: {
        type: String,
        required: true
      },
      subtext: {
        type: String,
        default: ''
      },
    },
    data() {
      return {
        colors: {
          info: 'var(--color--primary)',
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)'
        }
      }
    },
    components: {
      EpButton,
      EpIcon
    },
    computed: {
      colorStrip() {
        return this.colors[this.bannerStyle]
      }
    },
    methods: {
      dismissNotification() {
        this.$emit('dismiss')
      }
    }
  }
</script>

// packages/epicenter-components-react/src/components/banner/EpBanner.tsx
import React, { ReactNode } from 'react'

export interface EpBannerProps {
  /**
   * Dismiss button or action
   */
  dismiss?: ReactNode
  /**
   * Icon displayed at the start of the banner
   */
  icon?: ReactNode
  /**
   * Main message content of the banner
   */
  message?: ReactNode
  /**
   * Handler called when the banner is dismissed
   */
  onDismissed?: () => void
  /**
   * Secondary message or additional information
   */
  subtext?: ReactNode
}

export const EpBanner: React.FC<EpBannerProps> = ({
  icon,
  message,
  subtext,
  dismiss,
  onDismissed
}) => {
  const handleDismiss = () => {
    onDismissed?.()
  }

  return (
    <div className="ep-banner">
      <div className="ep-banner__color-strip" />
      <div className="ep-banner__body">
        {icon && (
          <div className="ep-banner__body__icon">
            {icon}
          </div>
        )}
        <div className="ep-banner__body__message">
          <div className="ep-banner__body__message__text font-size--small">
            {message}
          </div>
          {subtext && (
            <div className="ep-banner__body__message__subtext">
              {subtext}
            </div>
          )}
        </div>
        {dismiss && React.cloneElement(dismiss as React.ReactElement, {
          onClick: handleDismiss
        })}
      </div>
    </div>
  )
}
