// packages/epicenter-vue-components/src/components/table/EpTableCell.vue
<template>
  <span :class="column.class">
    {{ cellContent }}
  </span>
</template>

<script setup>
  import { ref, watchEffect } from 'vue'

  defineOptions({
    name: 'EpTableCell'
  })

  const props = defineProps({
    row: {
      type: Object,
      required: true
    },
    column: {
      type: Object,
      required: true
    },
    styles: {
      type: Array,
      default: () => []
    }
  })

  const cellContent = ref('')

  const formattedCell = (row, column) => {
    const value = row[column.key]
    const formatter = column.formatter

    if (formatter) {
      return formatter(value, row)
    }
    return value
  }

  watchEffect(() => {
    cellContent.value = formattedCell(props.row, props.column)
  })
</script>

// packages/epicenter-react-components/src/components/table/EpTableCell.tsx
import React, { useMemo } from 'react'
import type { Column } from './EpTable'

export interface EpTableCellProps {
  /** Row data object */
  row: any
  /** Column configuration */
  column: Column
  /** Additional styles */
  styles?: React.CSSProperties[]
}

/**
 * EpTableCell - Table cell component with formatter support
 * 
 * Renders table cell content with optional value formatting via column.formatter.
 */
const EpTableCell: React.FC<EpTableCellProps> = ({ row, column, styles = [] }) => {
  const cellContent = useMemo(() => {
    const value = row[column.key]
    const formatter = column.formatter

    if (formatter) {
      return formatter(value, row)
    }
    return value
  }, [row, column])

  return <span className={column.class}>{cellContent}</span>
}

export default EpTableCell
