// packages/epicenter-components-react/src/components/map/EpMap.tsx
import React, { useEffect, useRef, useState } from 'react'

export interface PinLocation {
  lat: number
  lng: number
}

export interface MapSource {
  id: string
  source: any
}

export interface EpMapProps {
  /** Mapbox access token (required) */
  accessToken: string
  /** Additional CSS classes */
  className?: string
  /** Fit map to bounds of source data */
  fitToBounds?: boolean
  /** Map center coordinates [lng, lat] */
  mapCenter?: [number, number]
  /** Map layer configuration */
  mapLayer?: any
  /** Map source configuration */
  mapSource?: MapSource | null
  /** Mapbox style URL */
  mapStyle?: string
  /** Map zoom level */
  mapZoom?: number
  /** Show navigation control */
  navigationControl?: boolean
  /** Callback when center changes */
  onCenterChange?: (center: [number, number]) => void
  /** Callback when pin is dropped */
  onDropPin?: (location: PinLocation) => void
  /** Callback when zoom changes */
  onZoomChange?: (zoom: number) => void
  /** Array of pin locations to display */
  pinLocations?: PinLocation[]
  /** Enable scroll zoom */
  scrollZoom?: boolean
}

/**
 * EpMap - Mapbox GL wrapper component
 * 
 * Interactive map with pin markers, custom layers, and navigation controls.
 * Automatically resizes with container using ResizeObserver.
 */
export const EpMap: React.FC<EpMapProps> = ({
  accessToken,
  mapCenter = [-122.3321, 47.6062],
  mapZoom = 12,
  mapStyle = 'mapbox://styles/mapbox/streets-v11',
  mapSource = null,
  mapLayer = null,
  pinLocations = [],
  scrollZoom = true,
  navigationControl = true,
  fitToBounds = false,
  onCenterChange,
  onZoomChange,
  className = ''
}) => {
  const mapContainerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<any>(null)
  const markersRef = useRef<any[]>([])
  const mapboxglRef = useRef<any>(null)
  const [init, setInit] = useState(true)

  // Load map
  useEffect(() => {
    const loadMap = async () => {
      const mapboxgl = (await import('mapbox-gl')).default
      await import('mapbox-gl/dist/mapbox-gl.css')
      mapboxglRef.current = mapboxgl

      if (!mapContainerRef.current) return

      mapRef.current = new mapboxgl.Map({
        accessToken,
        container: mapContainerRef.current,
        center: mapCenter,
        zoom: mapZoom,
        style: mapStyle
      })

      // Various options
      if (!scrollZoom) mapRef.current.scrollZoom.disable()
      if (navigationControl) mapRef.current.addControl(new mapboxgl.NavigationControl())

      mapRef.current.on('load', () => {
        // map layer
        if (mapSource) addSource(mapSource, mapLayer)
        // fit to bounds
        if (fitToBounds && mapSource) {
          fitBoundsToSource(getBounds(mapSource.source.data.geometry.coordinates))
        }
        // if pin locations exist, add them
        if (pinLocations.length) addMarkers()
        setInit(false)
      })

      mapRef.current.on('dragend', () => {
        const center = mapRef.current.getCenter()
        onCenterChange?.([center.lng, center.lat])
      })
    }

    loadMap()

    return () => {
      if (mapRef.current) {
        removeMarkers()
        if (mapRef.current.getLayer('test')) mapRef.current.removeLayer('test')
        if (mapRef.current.getSource('test')) mapRef.current.removeSource('test')
        mapRef.current.remove()
      }
    }
  }, [])

  // Watch for map center changes
  useEffect(() => {
    if (!init && mapRef.current) {
      onCenterChange?.(mapCenter)
      flyTo(mapCenter, mapZoom)
    }
  }, [mapCenter])

  // Watch for map zoom changes
  useEffect(() => {
    if (!init && mapRef.current) {
      onZoomChange?.(mapZoom)
      flyTo(mapCenter, mapZoom)
    }
  }, [mapZoom])

  // Watch for map style changes
  useEffect(() => {
    if (!init && mapRef.current) {
      mapRef.current.setStyle(mapStyle)
    }
  }, [mapStyle])

  // Watch for pin location changes
  useEffect(() => {
    if (!init && mapRef.current) {
      removeMarkers()
      addMarkers()
    }
  }, [pinLocations])

  // Watch for scroll zoom changes
  useEffect(() => {
    if (!init && mapRef.current) {
      if (scrollZoom) {
        mapRef.current.scrollZoom.enable()
      } else {
        mapRef.current.scrollZoom.disable()
      }
    }
  }, [scrollZoom])

  // Resize observer
  useEffect(() => {
    if (!mapContainerRef.current || !mapRef.current) return

    const observer = new ResizeObserver(() => {
      if (mapRef.current) {
        setTimeout(() => {
          mapRef.current.resize()
        }, 0)
      }
    })

    observer.observe(mapContainerRef.current)

    return () => {
      observer.disconnect()
    }
  }, [init])

  const addMarkers = () => {
    if (!mapboxglRef.current || !mapRef.current) return
    pinLocations.forEach((location) => {
      const marker = new mapboxglRef.current.Marker()
        .setLngLat([location.lng, location.lat])
        .addTo(mapRef.current)
      markersRef.current.push(marker)
    })
  }

  const removeMarkers = () => {
    markersRef.current.forEach((marker) => marker.remove())
    markersRef.current = []
  }

  const flyTo = (center = mapCenter, zoom = mapZoom) => {
    if (mapRef.current) {
      mapRef.current.flyTo({ center, zoom })
    }
  }

  const getBounds = (coordinates: number[][]) => {
    if (!mapboxglRef.current) return null
    return coordinates.reduce(
      (bounds, coord) => bounds.extend(coord),
      new mapboxglRef.current.LngLatBounds(coordinates[0], coordinates[0])
    )
  }

  const fitBoundsToSource = (bounds: any) => {
    if (mapRef.current && bounds) {
      mapRef.current.fitBounds(bounds, {
        linear: false,
        duration: 1000,
        padding: 60
      })
    }
  }

  const addSource = (source: MapSource, layer: any) => {
    if (mapRef.current) {
      mapRef.current.addSource(source.id, source.source)
      if (layer) mapRef.current.addLayer(layer)
    }
  }

  return (
    <div className={`ep-map-container${className ? ` ${className}` : ''}`}>
      <div ref={mapContainerRef} id="ep-map" style={{ width: '100%', height: '100%' }} />
    </div>
  )
}

// packages/epicenter-design-system/src/components/map/EpMap.vue
<template>
  <div class="ep-map-container">
    <div id="ep-map"></div>
  </div>
</template>

<script>
  import mapboxgl from 'mapbox-gl'
  import { mapState } from 'vuex'

  export default {
    name: 'EpMap',
    props: {
      mapCenter: {
        type: Array,
        default: () => [-122.3321, 47.6062]
      },
      mapZoom: {
        type: Number,
        default: 12
      },
      mapStyle: {
        type: String,
        default: ''
      },
      // mapSource: {
      //   type: Object,
      //   default: null
      // },
      // mapLayer: {
      //   type: Object,
      //   default: null
      // },
      scrollZoom: {
        type: Boolean,
        default: true
      },
      navigationControl: {
        type: Boolean,
        default: true
      },
      fitToBounds: {
        type: Boolean,
        default: false
      },
      // flyTo: {
      //   type: Array,
      //   default: null
      // }
    },
    data() {
      return {
        init: true,
        map: null,
        markers: [],
      }
    },
    computed: {
      ...mapState(['theme']),
      computedMapStyle() {
        if (this.mapStyle) return this.mapStyle
        return this.theme == 'dark' ? 'mapbox://styles/mapbox/dark-v10' : 'mapbox://styles/mapbox/streets-v11'
      }
    },
    methods: {
      dropPin(lngLat) {
        this.markers.push(new mapboxgl.Marker()
          .setLngLat(lngLat)
          .addTo(this.map))
        this.$emit('dropPin', lngLat)
      },
      flyTo() {
        this.map.flyTo({
          center: this.mapCenter
        })
      },
      loadMap() {
        return new Promise(resolve => {
          mapboxgl.accessToken = 'pk.eyJ1IjoiZXJpY3BpdGNvY2siLCJhIjoia29WT3AzOCJ9.YTnpZdWBqPD4cH6mlnZoYQ'
          this.map = new mapboxgl.Map({
            container: 'ep-map',
            center: this.mapCenter,
            zoom: this.mapZoom,
            style: this.computedMapStyle,
          })
          // various options
          // scroll zoom
          if (!this.scrollZoom) this.map.scrollZoom.disable()
          // Add zoom and rotation controls to the map.
          if (this.navigationControl) this.map.addControl(new mapboxgl.NavigationControl())

          this.map.on('load', () => resolve())
        })
      },
      getMapCenter() {
        if (this.fitToBounds) {
          let bounds = this.getBounds(this.mapSource.source.data.geometry.coordinates)
          return [bounds.getCenter().lng, bounds.getCenter().lat]
        } else {
          return this.mapCenter
        }
      },
      getBounds(coordinates) {
        let bounds = coordinates.reduce(function (bounds, coord) {
          return bounds.extend(coord)
        }, new mapboxgl.LngLatBounds(coordinates[0], coordinates[0]))
        return bounds
      },
      fitBounds(bounds) {
        this.map.fitBounds(bounds, {
          linear: false,
          duration: 1000,
          padding: 60
        })
      },
      addSource(source, layer) {
        this.map.addSource(source.id, source.source)
        this.map.addLayer(layer)
      }
    },
    watch: {
      // init(val) {
      //   console.log('map has initialized')
      // },
      mapCenter(newCenter, oldCenter) {
        // this.map.setCenter(newCenter)
        this.flyTo(newCenter)
      },
      mapZoom(newZoom, oldZoom) {
        this.map.zoomTo(newZoom)
      },
      mapStyle(newStyle, oldStyle) {
        this.map.setStyle(newStyle)
      }
    },
    mounted() {
      this.loadMap().then(() => {
        // map layer
        if (this.mapSource) this.addSource(this.mapSource, this.mapLayer)
        // fit to bounds
        if (this.fitToBounds) {
          this.fitBounds(this.getBounds(this.mapSource.source.data.geometry.coordinates))
        }
        this.init = false
      })
      // console.log(this.theme)
      // this.map.on('zoom', (event) => {
      // console.log(event)
      // })
      // this.map.on('click', (event) => {
      // console.log('A click event has occurred at ' + event.lngLat)
      // })
    },
    created() {
      // selectively create watchers if features exist
      // do this for everything that is not required

      if (this.mapSource) {
        this.$watch('mapSource', function (newSource, oldSource) {
          if (this.init) return
          console.log('map source changed (mapSource watcher)')
          if (this.map.getLayer('test')) this.map.removeLayer('test')
          if (this.map.getSource('test')) this.map.removeSource('test')
          this.addSource(this.mapSource, this.mapLayer)
          this.fitBounds(this.getBounds(this.mapSource.source.data.geometry.coordinates))
        })
      }
    },
    beforeDestroy() {
      if (this.map) {
        if (this.map.getLayer('test')) this.map.removeLayer('test')
        if (this.map.getSource('test')) this.map.removeSource('test')
        this.map.remove()
      }
    },
    // from https://github.com/soal/vue-mapbox/blob/5a37e7a8bd2fdb8776350e66a00e23b47ec5ad0c/src/components/map/GlMap.vue
    // beforeDestroy() {
    //   this.$nextTick(() => {
    //     if (this.map) this.map.remove()
    //   })
    // }
  }
</script>

<style lang="scss" scoped>
  @import '~mapbox-gl/dist/mapbox-gl.css';
  .ep-map-container {
    position: relative;
    width: 100%;
    height: 100%;
  }
  #ep-map {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
</style>
