// packages/epicenter-react-components/src/components/badge/EpBadge.tsx
import { ReactNode } from 'react';

export interface EpBadgeProps {
  /** Badge content */
  children?: ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** The label to display in the badge */
  label?: string;
}

/**
 * EpBadge - A badge component for displaying labels or status
 */
export const EpBadge = ({ label = '', children, className = '' }: EpBadgeProps) => {
  return (
    <div className={`ep-badge${className ? ` ${className}` : ''}`}>
      {children || label}
    </div>
  );
};

EpBadge.displayName = 'EpBadge';

// packages/epicenter-components-vue/src/components/badge/EpBadge.vue
<script setup lang="ts">
  interface EpBadgeProps {
    /**
     * The label to display in the badge.
     */
    label?: string
  }

  const { label = '' } = defineProps<EpBadgeProps>()
</script>

<template>
  <div class="ep-badge">
    <!-- @slot Default slot for badge content. Falls back to label prop if not provided. -->
    <slot>{{ label }}</slot>
  </div>
</template>
