// packages/epicenter-vue-components/src/components/toggle/EpToggle.vue
<template>
  <div
    :class="['ep-toggle', classes]"
    @click="toggle"
  >
    <div class="ep-toggle__track">
      <div class="ep-toggle__thumb" />
    </div>
    <div class="ep-toggle__label">
      {{ label }}
    </div>
  </div>
</template>

<script setup>
  import { computed } from 'vue'

  defineOptions({
    name: 'EpToggle',
  })

  const props = defineProps({
    /**
     * If true, shows the toggle in the active/on state.
     */
    isActive: {
      type: Boolean,
      default: false,
    },
    /**
     * If true, disables the toggle interaction.
     */
    disabled: {
      type: Boolean,
      default: false,
    },
    /**
     * Label text displayed next to the toggle.
     */
    label: {
      type: String,
      default: '',
    },
    /**
     * The size variant of the toggle.
     * @values 'small', 'default', 'large'
     */
    size: {
      type: String,
      default: 'default',
    },
  })

  const emit = defineEmits(['toggle'])

  const classes = computed(() => {
    return {
      'ep-toggle--active': props.isActive,
      'ep-toggle--disabled': props.disabled,
    }
  })

  const toggle = () => {
    if (props.disabled) return
    emit('toggle')
  }
</script>

// packages/epicenter-components-react/src/components/toggle/EpToggle.tsx

type ToggleSize = 'small' | 'default' | 'large';

export interface EpToggleProps {
  /** Additional CSS classes */
  className?: string;
  /** If true, disables the toggle interaction */
  disabled?: boolean;
  /** If true, shows the toggle in the active/on state */
  isActive?: boolean;
  /** Label text displayed next to the toggle */
  label?: string;
  /** Callback when toggle is clicked */
  onToggle?: () => void;
  /** The size variant of the toggle */
  size?: ToggleSize;
}

/**
 * EpToggle - A toggle switch component for binary on/off states
 */
export const EpToggle: React.FC<EpToggleProps> = ({
  isActive = false,
  disabled = false,
  label = '',
  onToggle,
  size = 'default',
  className = '',
}) => {
  const classes = ['ep-toggle'];
  
  if (size !== 'default') classes.push(`ep-toggle--${size}`);
  if (isActive) classes.push('ep-toggle--active');
  if (disabled) classes.push('ep-toggle--disabled');
  if (className) classes.push(className);

  const handleClick = () => {
    if (disabled) return;
    if (onToggle) onToggle();
  };

  return (
    <div className={classes.join(' ')} onClick={handleClick}>
      <div className="ep-toggle__track">
        <div className="ep-toggle__thumb" />
      </div>
      {label && <div className="ep-toggle__label">{label}</div>}
    </div>
  );
};

EpToggle.displayName = 'EpToggle';
