// packages/epicenter-components-vue/src/components/toggle/EpToggle.vue
<script setup lang="ts">
  import { computed } from 'vue'

  interface EpToggleProps {
    /** If true, disables the toggle interaction. */
    disabled?: boolean
    /** If true, shows the toggle in the active/on state. */
    isActive?: boolean
    /** Label text displayed next to the toggle. */
    label?: string
    /** The size variant of the toggle. */
    size?: 'small' | 'default' | 'large'
  }

  const {
    disabled = false,
    isActive = false,
    label = '',
  } = defineProps<EpToggleProps>()

  const emit = defineEmits<{
    toggle: []
  }>()

  const classes = computed(() => {
    return {
      'ep-toggle--active': isActive,
      'ep-toggle--disabled': disabled,
    }
  })

  const toggle = (): void => {
    if (disabled) return
    emit('toggle')
  }
</script>

<template>
  <div
    :class="['ep-toggle', classes]"
    @click="toggle"
  >
    <div class="ep-toggle__track">
      <div class="ep-toggle__thumb" />
    </div>
    <div class="ep-toggle__label">
      {{ label }}
    </div>
  </div>
</template>

// packages/epicenter-components-react/src/components/toggle/EpToggle.tsx

type ToggleSize = 'small' | 'default' | 'large';

export interface EpToggleProps {
  /** Additional CSS classes */
  className?: string;
  /** If true, disables the toggle interaction */
  disabled?: boolean;
  /** If true, shows the toggle in the active/on state */
  isActive?: boolean;
  /** Label text displayed next to the toggle */
  label?: string;
  /** Callback when toggle is clicked */
  onToggle?: () => void;
  /** The size variant of the toggle */
  size?: ToggleSize;
}

/**
 * EpToggle - A toggle switch component for binary on/off states
 */
export const EpToggle: React.FC<EpToggleProps> = ({
  isActive = false,
  disabled = false,
  label = '',
  onToggle,
  size = 'default',
  className = '',
}) => {
  const classes = ['ep-toggle'];
  
  if (size !== 'default') classes.push(`ep-toggle--${size}`);
  if (isActive) classes.push('ep-toggle--active');
  if (disabled) classes.push('ep-toggle--disabled');
  if (className) classes.push(className);

  const handleClick = () => {
    if (disabled) return;
    if (onToggle) onToggle();
  };

  return (
    <div className={classes.join(' ')} onClick={handleClick}>
      <div className="ep-toggle__track">
        <div className="ep-toggle__thumb" />
      </div>
      {label && <div className="ep-toggle__label">{label}</div>}
    </div>
  );
};

EpToggle.displayName = 'EpToggle';
