// packages/epicenter-components-react/src/components/tab-content/EpTabContent.tsx
import React, { ReactNode } from 'react'

export interface EpTabContentProps {
  /**
   * The index of the currently active tab.
   * @default 0
   */
  activeTabIndex?: number
  /**
   * Array of content for each tab panel
   */
  children?: ReactNode[]
  /**
   * An array of tab items (used to determine tab count).
   */
  items: unknown[]
}

export const EpTabContent: React.FC<EpTabContentProps> = ({
  activeTabIndex = 0,
  items,
  children
}) => {
  const childArray = React.Children.toArray(children)

  return (
    <div className="ep-tab-content">
      {items.map((_, index) => (
        <div
          key={index}
          id={`tabpanel-${index}`}
          className={[
            'ep-tab-content__tab-item',
            index === activeTabIndex && 'ep-tab-content__tab-item--active'
          ].filter(Boolean).join(' ')}
          role="tabpanel"
          aria-labelledby={`tab-${index}`}
          aria-hidden={index !== activeTabIndex}
        >
          {childArray[index]}
        </div>
      ))}
    </div>
  )
}

// packages/epicenter-vue-components/src/components/tabs/EpTabContent.vue
<template>
  <div class="ep-tab-content">
    <div
      v-for="(item, index) in items"
      :id="`tabpanel-${index}`"
      :key="index"
      class="ep-tab-content__tab-item"
      :class="{ 'ep-tab-content__tab-item--active': index === activeTabIndex }"
      role="tabpanel"
      :aria-labelledby="`tab-${index}`"
      :aria-hidden="index !== activeTabIndex"
    >
      <!-- @slot tab-{index} - Content for each tab panel. Use named slots like 'tab-0', 'tab-1', etc. -->
      <slot :name="`tab-${index}`" />
    </div>
  </div>
</template>

<script setup>
  defineOptions({
    name: 'EpTabContent',
  })

  const props = defineProps({
    /**
     * The index of the currently active tab.
     */
    activeTabIndex: {
      type: Number,
      default: 0
    },
    /**
     * An array of tab items (used to determine tab count).
     */
    items: {
      type: Array,
      default: () => []
    }
  })
</script>
