// packages/epicenter-components-vue/src/components/pagination/EpPagination.vue
<script setup lang="ts">
  import ArrowLeft01 from '@ericpitcock/epicenter-icons-vue/ArrowLeft01'
  import ArrowRight01 from '@ericpitcock/epicenter-icons-vue/ArrowRight01'
  import { computed, ref } from 'vue'

  import type { SelectOption } from '../../types'
  import EpButton from '../button/EpButton.vue'
  import EpFlex from '../flexbox/EpFlex.vue'
  import EpSelect from '../select/EpSelect.vue'

  interface EpPaginationProps {
    /** Custom CSS class to apply to pagination buttons. */
    buttonClass?: string
    /** The current active page number. */
    currentPage: number
    /** Number of results to display per page. When provided, shows a dropdown to change this value. */
    resultsPerPage?: number | null
    /** Options for the results per page dropdown. */
    resultsPerPageOptions?: SelectOption[]
    /** If true, displays individual page number buttons instead of just prev/next. */
    showPages?: boolean
    /** Total number of pages available. */
    totalPages: number
  }

  const {
    currentPage,
    totalPages,
    buttonClass = '',
    resultsPerPage = null,
    resultsPerPageOptions = [
      { label: '10 / page', value: 10 },
      { label: '20 / page', value: 20 },
      { label: '50 / page', value: 50 },
      { label: '100 / page', value: 100 },
    ],
    showPages = false,
  } = defineProps<EpPaginationProps>()

  const emit = defineEmits<{
    pageChange: [page: number]
    'update:resultsPerPage': [value: number]
  }>()

  const localResultsPerPage = ref<string | number>(resultsPerPage ?? 10)

  const onResultsPerPageChange = (value: unknown): void => {
    emit('update:resultsPerPage', Number(value))
  }

  const prevPage = (): void => {
    if (currentPage > 1) {
      emit('pageChange', currentPage - 1)
    }
  }

  const nextPage = (): void => {
    if (currentPage < totalPages) {
      emit('pageChange', currentPage + 1)
    }
  }

  const truncationThreshold = 9

  const shouldShowStartEllipsis = computed(() => {
    return totalPages > truncationThreshold && currentPage > 3
  })

  const shouldShowEndEllipsis = computed(() => {
    return totalPages > truncationThreshold && currentPage < totalPages - 2
  })

  const pageRange = computed<number[]>(() => {
    const range: number[] = []

    // Show all pages if under threshold
    if (totalPages <= truncationThreshold) {
      for (let i = 2; i < totalPages; i++) {
        range.push(i)
      }
      return range
    }

    // Show first few pages when near start
    if (currentPage <= 3) {
      return [2, 3, 4]
    }

    // Show last few pages when near end
    if (currentPage >= totalPages - 2) {
      return [totalPages - 3, totalPages - 2, totalPages - 1]
    }

    // Show pages around current page when in middle
    return [currentPage - 1, currentPage, currentPage + 1]
  })
</script>

<template>
  <div class="ep-pagination">
    <ep-flex class="justify-between gap-30">
      <!-- @slot Content displayed on the left side of the pagination controls -->
      <slot name="left">
        <ep-flex
          v-if="resultsPerPage !== null"
          class="justify-end align-center gap-10"
        >
          <div style="--ep-input-width: fit-content;">
            <ep-select
              v-model="localResultsPerPage"
              select-id="resultsPerPage"
              :options="resultsPerPageOptions"
              placeholder=""
              @update:model-value="onResultsPerPageChange"
            />
          </div>
        </ep-flex>
      </slot>
      <ep-flex class="align-center gap-10">
        <ep-button
          :disabled="currentPage === 1"
          aria-label="Previous page"
          :class="buttonClass"
          @click="prevPage"
        >
          <!-- @slot Custom icon for the previous page button. Defaults to <ArrowLeft01 /> -->
          <template #icon-left>
            <slot name="icon-prev">
              <ArrowLeft01 />
            </slot>
          </template>
        </ep-button>
        <template v-if="showPages">
          <ep-button
            aria-label="First page"
            :class="[buttonClass, { 'ep-button--selected': currentPage === 1 }]"
            @click="emit('pageChange', 1)"
          >
            1
          </ep-button>
          <span v-if="shouldShowStartEllipsis">...</span>
          <ep-button
            v-for="page in pageRange"
            :key="page"
            :aria-label="`Page ${page}`"
            :class="[buttonClass, { 'ep-button--selected': currentPage === page }]"
            @click="emit('pageChange', page)"
          >
            {{ page.toString() }}
          </ep-button>
          <span v-if="shouldShowEndEllipsis">...</span>
          <ep-button
            v-if="totalPages > 1"
            aria-label="Last page"
            :class="[buttonClass, { 'ep-button--selected': currentPage === totalPages }]"
            @click="emit('pageChange', totalPages)"
          >
            {{ totalPages.toString() }}
          </ep-button>
        </template>
        <template v-else>
          <span class="ep-pagination-info">
            Page {{ currentPage }} of {{ totalPages }}
          </span>
        </template>
        <ep-button
          aria-label="Next page"
          :disabled="currentPage === totalPages"
          :class="buttonClass"
          @click="nextPage"
        >
          <template #icon-right>
            <!-- @slot Custom icon for the next page button. Defaults to <ArrowRight01 /> -->
            <slot name="icon-next">
              <ArrowRight01 />
            </slot>
          </template>
        </ep-button>
      </ep-flex>
      <!-- @slot Content displayed on the right side of the pagination controls -->
      <slot name="right" />
    </ep-flex>
  </div>
</template>

// packages/epicenter-components-react/src/components/pagination/EpPagination.tsx
import { ArrowLeft01 } from '@ericpitcock/epicenter-icons-react/ArrowLeft01.jsx'
import { ArrowRight01 } from '@ericpitcock/epicenter-icons-react/ArrowRight01.jsx'
import React, { ReactNode, useMemo } from 'react'

import { EpButton } from '../button/EpButton'
import { EpFlex } from '../flexbox/EpFlex'
import { EpSelect } from '../select/EpSelect'

export interface ResultsPerPageOption {
  label: string
  value: number
}

export interface EpPaginationProps {
  /**
   * Custom CSS class to apply to pagination buttons.
   */
  buttonClass?: string
  /**
   * The current active page number.
   */
  currentPage: number
  /**
   * Custom icon for the next page button
   */
  iconNext?: ReactNode
  /**
   * Custom icon for the previous page button
   */
  iconPrev?: ReactNode
  /**
   * Content displayed on the left side of the pagination controls
   */
  leftContent?: ReactNode
  /**
   * Handler called when page changes
   */
  onPageChange?: (page: number) => void
  /**
   * Handler called when results per page changes
   */
  onResultsPerPageChange?: (value: number) => void
  /**
   * Number of results to display per page. When provided, shows a dropdown to change this value.
   */
  resultsPerPage?: number | null
  /**
   * Options for the results per page dropdown.
   */
  resultsPerPageOptions?: ResultsPerPageOption[]
  /**
   * Content displayed on the right side of the pagination controls
   */
  rightContent?: ReactNode
  /**
   * If true, displays individual page number buttons instead of just prev/next.
   * @default false
   */
  showPages?: boolean
  /**
   * Total number of pages available.
   */
  totalPages: number
}

const defaultResultsPerPageOptions: ResultsPerPageOption[] = [
  { label: '10 / page', value: 10 },
  { label: '20 / page', value: 20 },
  { label: '50 / page', value: 50 },
  { label: '100 / page', value: 100 }
]

export const EpPagination: React.FC<EpPaginationProps> = ({
  currentPage,
  totalPages,
  showPages = false,
  buttonClass = '',
  resultsPerPage = null,
  resultsPerPageOptions = defaultResultsPerPageOptions,
  iconPrev,
  iconNext,
  leftContent,
  rightContent,
  onPageChange,
  onResultsPerPageChange
}) => {
  const truncationThreshold = 9

  const shouldShowStartEllipsis = useMemo(() => {
    return totalPages > truncationThreshold && currentPage > 3
  }, [totalPages, currentPage])

  const shouldShowEndEllipsis = useMemo(() => {
    return totalPages > truncationThreshold && currentPage < totalPages - 2
  }, [totalPages, currentPage])

  const pageRange = useMemo(() => {
    const range: number[] = []

    // Show all pages if under threshold
    if (totalPages <= truncationThreshold) {
      for (let i = 2; i < totalPages; i++) {
        range.push(i)
      }
      return range
    }

    // Show first few pages when near start
    if (currentPage <= 3) {
      return [2, 3, 4]
    }

    // Show last few pages when near end
    if (currentPage >= totalPages - 2) {
      return [totalPages - 3, totalPages - 2, totalPages - 1]
    }

    // Show pages around current page when in middle
    return [currentPage - 1, currentPage, currentPage + 1]
  }, [currentPage, totalPages])

  const prevPage = () => {
    if (currentPage > 1) {
      onPageChange?.(currentPage - 1)
    }
  }

  const nextPage = () => {
    if (currentPage < totalPages) {
      onPageChange?.(currentPage + 1)
    }
  }

  const defaultIconPrev = iconPrev || <ArrowLeft01 />
  const defaultIconNext = iconNext || <ArrowRight01 />

  return (
    <div className="ep-pagination">
      <EpFlex className="justify-between gap-30">
        {leftContent || (
          resultsPerPage !== null ? (
            <EpFlex className="justify-end align-center gap-10">
              <div style={{ '--ep-input-width': 'fit-content' } as React.CSSProperties}>
                <EpSelect
                  selectId="resultsPerPage"
                  options={resultsPerPageOptions}
                  value={resultsPerPage}
                  onChange={(value) => onResultsPerPageChange?.(Number(value))}
                  placeholder=""
                />
              </div>
            </EpFlex>
          ) : null
        )}
        <EpFlex className="align-center gap-10">
          <EpButton
            disabled={currentPage === 1}
            aria-label="Previous page"
            className={buttonClass}
            onClick={prevPage}
            iconLeft={defaultIconPrev}
          />
          {showPages ? (
            <>
              <EpButton
                aria-label="First page"
                className={[
                  buttonClass,
                  currentPage === 1 && 'ep-button--selected'
                ].filter(Boolean).join(' ')}
                onClick={() => onPageChange?.(1)}
              >
                1
              </EpButton>
              {shouldShowStartEllipsis && <span>...</span>}
              {pageRange.map(page => (
                <EpButton
                  key={page}
                  aria-label={`Page ${page}`}
                  className={[
                    buttonClass,
                    currentPage === page && 'ep-button--selected'
                  ].filter(Boolean).join(' ')}
                  onClick={() => onPageChange?.(page)}
                >
                  {page}
                </EpButton>
              ))}
              {shouldShowEndEllipsis && <span>...</span>}
              {totalPages > 1 && (
                <EpButton
                  aria-label="Last page"
                  className={[
                    buttonClass,
                    currentPage === totalPages && 'ep-button--selected'
                  ].filter(Boolean).join(' ')}
                  onClick={() => onPageChange?.(totalPages)}
                >
                  {totalPages}
                </EpButton>
              )}
            </>
          ) : (
            <span className="ep-pagination-info">
              Page {currentPage} of {totalPages}
            </span>
          )}
          <EpButton
            aria-label="Next page"
            disabled={currentPage === totalPages}
            className={buttonClass}
            onClick={nextPage}
            iconRight={defaultIconNext}
          />
        </EpFlex>
        {rightContent}
      </EpFlex>
    </div>
  )
}
