// packages/epicenter-react-components/src/components/dropdown/EpDropdown.tsx
import React, { ReactNode, useEffect, useId, useRef, useState, KeyboardEvent, MouseEvent } from 'react'

import { useClickOutside } from '../../hooks/useClickOutside'

export interface EpDropdownTriggerProps {
  attrs: {
    id: string
    'aria-haspopup': string
    'aria-expanded': string
    'aria-controls': string
    disabled?: boolean
  }
  close: () => void
  isOpen: boolean
  onClick: () => void
  onKeyDown: (e: KeyboardEvent) => void
  onMouseOver: () => void
  open: () => void
  toggle: () => void
}

export interface EpDropdownProps {
  /**
   * If true, aligns the dropdown content to the right edge of the trigger.
   * @default false
   */
  alignRight?: boolean
  /**
   * If true, opens the dropdown on hover instead of click.
   * @default false
   */
  showOnHover?: boolean
  /**
   * If true, disables the dropdown
   * @default false
   */
  disabled?: boolean
  /**
   * Trigger element that opens/closes the dropdown
   */
  trigger?: ReactNode | ((props: EpDropdownTriggerProps) => ReactNode)
  /**
   * Content displayed inside the dropdown panel when open
   */
  children?: ReactNode | ((props: { close: () => void }) => ReactNode)
  /**
   * Handler called when dropdown is clicked
   */
  onClick?: () => void
  /**
   * Handler called when dropdown is closed
   */
  onClose?: () => void
}

export const EpDropdown = React.forwardRef<{ openDropdown: () => void; closeDropdown: () => void; toggleDropdown: () => void }, EpDropdownProps>(({
  alignRight = false,
  showOnHover = false,
  disabled = false,
  trigger,
  children,
  onClick,
  onClose
}, ref) => {
  const uniqueId = useId()
  const triggerId = `ep-dropdown-trigger-${uniqueId}`
  const contentId = `ep-dropdown-panel-${uniqueId}`
  
  const [dropdownVisible, setDropdownVisible] = useState(false)
  const dropdownRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)

  const openDropdown = () => {
    if (disabled || dropdownVisible) return
    setDropdownVisible(true)
  }

  const closeDropdown = () => {
    if (disabled || !dropdownVisible) return
    setDropdownVisible(false)
    onClose?.()
  }

  const toggleDropdown = () => {
    if (disabled || showOnHover) return
    setDropdownVisible(!dropdownVisible)
    onClick?.()
  }

  // Focus management
  useEffect(() => {
    if (dropdownVisible) {
      // Focus first menu item when opening
      const firstMenuItem = contentRef.current?.querySelector('[role="menuitem"]') as HTMLElement
      firstMenuItem?.focus()
    } else {
      // Return focus to trigger when closing
      const trigger = dropdownRef.current?.querySelector(`#${triggerId}`) as HTMLElement
      trigger?.focus()
    }
  }, [dropdownVisible, triggerId])

  const handleKeyDown = (e: KeyboardEvent) => {
    if (disabled) return
    
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      toggleDropdown()
    } else if (e.key === 'ArrowDown') {
      e.preventDefault()
      openDropdown()
    } else if (e.key === 'Escape') {
      e.preventDefault()
      closeDropdown()
    }
  }

  const handleMouseOver = () => {
    if (!disabled && showOnHover) {
      setDropdownVisible(true)
    }
  }

  const handleMouseLeave = () => {
    if (!disabled && showOnHover) {
      setDropdownVisible(false)
    }
  }

  useClickOutside(dropdownRef, closeDropdown)

  // Expose methods via ref
  React.useImperativeHandle(ref, () => ({
    openDropdown,
    closeDropdown,
    toggleDropdown
  }))

  const triggerAttrs = {
    id: triggerId,
    'aria-haspopup': 'menu' as const,
    'aria-expanded': String(dropdownVisible),
    'aria-controls': contentId,
    disabled: disabled || undefined
  }

  const triggerProps: EpDropdownTriggerProps = {
    isOpen: dropdownVisible,
    open: openDropdown,
    close: closeDropdown,
    toggle: toggleDropdown,
    attrs: triggerAttrs,
    onClick: toggleDropdown,
    onMouseOver: handleMouseOver,
    onKeyDown: handleKeyDown
  }

  return (
    <div
      ref={dropdownRef}
      className="ep-dropdown"
      onMouseLeave={handleMouseLeave}
    >
      {typeof trigger === 'function' ? (
        trigger(triggerProps)
      ) : trigger ? (
        <div
          {...triggerAttrs}
          onClick={toggleDropdown}
          onMouseOver={handleMouseOver}
          onKeyDown={handleKeyDown}
        >
          {trigger}
        </div>
      ) : (
        <button
          type="button"
          {...triggerAttrs}
          onClick={toggleDropdown}
          onMouseOver={handleMouseOver}
          onKeyDown={handleKeyDown}
        >
          Default dropdown
        </button>
      )}
      {dropdownVisible && (
        <div
          id={contentId}
          className={[
            'ep-dropdown__container',
            alignRight && 'ep-dropdown__container--align-right'
          ].filter(Boolean).join(' ')}
          role="region"
          aria-labelledby={triggerId}
        >
          <div
            ref={contentRef}
            className="ep-dropdown__content"
            tabIndex={-1}
          >
            {typeof children === 'function' ? children({ close: closeDropdown }) : children}
          </div>
        </div>
      )}
    </div>
  )
})

EpDropdown.displayName = 'EpDropdown'

// packages/epicenter-components-vue/src/components/dropdown/EpDropdown.vue
<script setup>
  import { onClickOutside } from '@vueuse/core'
  import { computed, nextTick, ref, useId, useTemplateRef, watch } from 'vue'

  const props = defineProps({
    /**
     * If true, aligns the dropdown content to the right edge of the trigger.
     */
    alignRight: {
      type: Boolean,
      default: false
    },
    /**
     * If true, opens the dropdown on hover instead of click.
     */
    showOnHover: {
      type: Boolean,
      default: false
    },
    /**
     * If true, automatically focuses the first menu item when the dropdown opens.
     */
    autoFocus: {
      type: Boolean,
      default: true
    },
  })

  const emit = defineEmits(['click', 'close'])
  const uniqueId = useId()
  const triggerId = `ep-dropdown-trigger-${uniqueId}`
  const contentId = `ep-dropdown-panel-${uniqueId}`

  const triggerAttrs = computed(() => ({
    id: triggerId,
    'aria-haspopup': 'menu',
    'aria-expanded': String(dropdownVisible.value),
    'aria-controls': contentId,
    disabled: props.disabled || undefined
  }))

  const triggerListeners = computed(() => ({
    click: toggleDropdown,
    mouseover: onMouseover,
    keydown: onKeydown
  }))

  const dropdownVisible = ref(false)

  const openDropdown = () => {
    if (props.disabled || dropdownVisible.value) return

    dropdownVisible.value = true
  }

  const closeDropdown = () => {
    if (props.disabled || !dropdownVisible.value) return

    dropdownVisible.value = false
    emit('close')
  }

  // Focus management
  watch(dropdownVisible, async (isOpen) => {
    await nextTick()

    if (isOpen) {
      // Focus first menu item when opening
      if (props.autoFocus) {
        const firstMenuItem = dropdownRef.value?.querySelector('[role="menuitem"]')
        firstMenuItem?.focus()
      }
    } else {
      // Return focus to trigger when closing
      const trigger = dropdownRef.value?.querySelector(`#${triggerId}`)
      trigger?.focus()
    }
  })

  const toggleDropdown = () => {
    if (props.disabled || props.showOnHover) return

    dropdownVisible.value = !dropdownVisible.value
  }

  const onKeydown = event => {
    if (props.disabled) return
    const key = event.key
    if (key === 'Enter' || key === ' ') {
      event.preventDefault()
      toggleDropdown()
    } else if (key === 'ArrowDown') {
      event.preventDefault()
      openDropdown()
    } else if (key === 'Escape') {
      event.preventDefault()
      closeDropdown()
    }
  }

  const onMouseover = () => {
    if (!props.disabled && props.showOnHover) {
      dropdownVisible.value = true
    }
  }

  const onMouseleave = () => {
    if (!props.disabled && props.showOnHover) {
      dropdownVisible.value = false
    }
  }

  const dropdownRef = useTemplateRef('dropdown')
  onClickOutside(dropdownRef, closeDropdown)

  defineExpose({ openDropdown, closeDropdown, toggleDropdown })
</script>

<template>
  <div
    ref="dropdown"
    class="ep-dropdown"
    @mouseleave="onMouseleave"
  >
    <!-- @slot Trigger element that opens/closes the dropdown. Provides scoped props for custom triggers. -->
    <slot
      name="trigger"
      :is-open="dropdownVisible"
      :open="openDropdown"
      :close="closeDropdown"
      :toggle="toggleDropdown"
      :attrs="triggerAttrs"
      :on="triggerListeners"
    >
      <button
        type="button"
        v-bind="triggerAttrs"
        v-on="triggerListeners"
      >
        Default dropdown
      </button>
    </slot>
    <div
      v-show="dropdownVisible"
      :id="contentId"
      :class="['ep-dropdown__container', { 'ep-dropdown__container--align-right': alignRight }]"
      role="region"
      :aria-labelledby="triggerId"
    >
      <div
        class="ep-dropdown__content"
        tabindex="-1"
      >
        <!-- @slot Content displayed inside the dropdown panel when open -->
        <slot
          name="content"
          :close="closeDropdown"
        />
      </div>
    </div>
  </div>
</template>
