// packages/epicenter-components-react/src/components/table/EpTable.tsx
import React, { useRef } from 'react'

export interface Column {
  class?: string
  formatter?: (value: any, row: any) => any
  key: string
  label: string
  sortable?: boolean
}

export interface EpTableProps {
  /** Gives borders to your table rows */
  bordered?: boolean
  /** Additional CSS classes */
  className?: string
  /** The columns of the table */
  columns: Column[]
  /** Compact rows in a single line table scenario */
  compact?: boolean
  /** The data of the table */
  data: any[]
  /** Whether to use a fixed header or not */
  fixedHeader?: boolean
  /** Columns to hide, but not filter from the data */
  hiddenColumns?: string[]
  /** Callback when container scrolls */
  onContainerScroll?: (scrollLeft: number) => void
  /** Callback when row is clicked */
  onRowClick?: (row: any) => void
  /** Actions menu renderer for each row */
  renderActionsMenu?: (row: any) => React.ReactNode
  /** Custom cell renderer for specific column */
  renderCell?: (column: Column, row: any) => React.ReactNode
  /** Custom fixed header renderer */
  renderFixedHeader?: (props: { visibleColumns: Column[]; showActionsMenu: boolean }) => React.ReactNode
  /** Custom header renderer */
  renderHeader?: (props: { visibleColumns: Column[]; showActionsMenu: boolean }) => React.ReactNode
  /** Selectable rows */
  selectable?: boolean
  /** Enable actions menu */
  showActionsMenu?: boolean
  /** Sticky header or nah */
  stickyHeader?: boolean
  /** Background colors for every other row */
  striped?: boolean
}

/**
 * EpTable - Advanced table component with customizable columns, sorting, and actions
 * 
 * Supports hidden columns, selectable rows, striped/bordered styling, sticky headers,
 * and custom cell rendering with slot-like props.
 */
export const EpTable = React.forwardRef<HTMLDivElement, EpTableProps>(
  (
    {
      columns,
      data,
      hiddenColumns = [],
      compact = false,
      bordered = false,
      selectable = false,
      striped = false,
      stickyHeader = false,
      fixedHeader = false,
      showActionsMenu = false,
      renderHeader,
      renderFixedHeader,
      renderCell,
      renderActionsMenu,
      onRowClick,
      onContainerScroll,
      className = ''
    },
    ref
  ) => {
    const tableContainerRef = useRef<HTMLDivElement | null>(null)

    const visibleColumns = columns.filter(
      (column) => !hiddenColumns.includes(column.key)
    )

    const tableClasses = [
      'ep-table',
      bordered && 'ep-table--bordered',
      compact && 'ep-table--compact',
      selectable && 'ep-table--selectable',
      stickyHeader && 'ep-table--sticky',
      striped && 'ep-table--striped',
      className
    ]
      .filter(Boolean)
      .join(' ')

    const handleRowClick = (row: any) => {
      if (!selectable) return
      onRowClick?.(row)
    }

    const handleScroll = () => {
      if (!fixedHeader || !tableContainerRef.current) return
      onContainerScroll?.(tableContainerRef.current.scrollLeft)
    }

    const defaultCellRenderer = (column: Column, row: any) => {
      const value = row[column.key]
      const formatter = column.formatter

      if (formatter) {
        return formatter(value, row)
      }
      return value
    }

    return (
      <div
        ref={(node) => {
          tableContainerRef.current = node
          if (typeof ref === 'function') {
            ref(node)
          } else if (ref) {
            ref.current = node
          }
        }}
        className="ep-table-container"
        onScroll={handleScroll}
      >
        <table className={tableClasses}>
          {renderHeader ? (
            renderHeader({ visibleColumns, showActionsMenu })
          ) : (
            <thead>
              <tr>
                {visibleColumns.map((column) => (
                  <th key={column.key}>
                    <div>
                      <span className="label">{column.label}</span>
                    </div>
                  </th>
                ))}
                {showActionsMenu && (
                  <th className="ep-table__actions-menu">
                    <div>
                      <span className="label">&nbsp;</span>
                    </div>
                  </th>
                )}
              </tr>
            </thead>
          )}
          <tbody>
            {data.map((row, rowIndex) => (
              <tr key={row.id || rowIndex} onClick={() => handleRowClick(row)}>
                {visibleColumns.map((column) => (
                  <td key={`body-${column.key}`}>
                    {renderCell ? (
                      renderCell(column, row)
                    ) : (
                      <span className={column.class}>
                        {defaultCellRenderer(column, row)}
                      </span>
                    )}
                  </td>
                ))}
                {showActionsMenu && (
                  <td className="ep-table__actions-menu">
                    {renderActionsMenu?.(row)}
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
        {fixedHeader && (
          <table
            className="ep-table ep-table--fixed-header"
            style={{ display: fixedHeader ? undefined : 'none' }}
          >
            {renderFixedHeader?.({ visibleColumns, showActionsMenu })}
          </table>
        )}
      </div>
    )
  }
)

EpTable.displayName = 'EpTable'

// packages/epicenter-components-vue/src/components/table/EpTable.vue
<script setup>
  import { computed, useTemplateRef } from 'vue'

  import EpTableCell from './EpTableCell.vue'

  const props = defineProps({
    /**
     * The columns of the table.
     */
    columns: {
      type: Array,
      required: true
    },
    /**
     * The data of the table.
     */
    data: {
      type: Array,
      required: true
    },
    /**
     * Columns to hide, but not filter from the data. An ID, for example, can be hidden, but still accessible to the app.
     */
    hiddenColumns: {
      type: Array,
      default: () => []
    },
    /**
     * Compact rows in a single line table scenario.
     */
    compact: {
      type: Boolean,
      default: false
    },
    /**
     * Gives borders to your table rows. Helpful for tables with a lot of data.
     */
    bordered: {
      type: Boolean,
      default: false
    },
    /**
     * Selectable rows
     */
    selectable: {
      type: Boolean,
      default: false
    },
    /**
     * Background colors for every other row. Helpful for tables with a lot of data.
     */
    striped: {
      type: Boolean,
      default: false
    },
    /**
     * Sticky header or nah
     */
    stickyHeader: {
      type: Boolean,
      default: false
    },
    /**
     * Whether to use a fixed header or not (requires useFixedHeader composable)
     */
    fixedHeader: {
      type: Boolean,
      default: false
    },
    /**
     * Enable actions menu
     */
    showActionsMenu: {
      type: Boolean,
      default: false
    },
  })

  const emit = defineEmits(['row-click', 'container-scroll'])

  const visibleColumns = computed(() => {
    return props.columns.filter(column => !props.hiddenColumns.includes(column.key))
  })

  const tableContainer = useTemplateRef('tableContainer')

  const classes = computed(() => {
    return {
      'ep-table--bordered': props.bordered,
      'ep-table--compact': props.compact,
      'ep-table--selectable': props.selectable,
      'ep-table--sticky': props.stickyHeader,
      'ep-table--striped': props.striped,
    }
  })

  const onRowClick = (row) => {
    if (!props.selectable) return
    emit('row-click', row)
  }

  const onScroll = () => {
    if (!props.fixedHeader) return
    emit('container-scroll', tableContainer.value.scrollLeft)
  }
</script>

<template>
  <div
    ref="tableContainer"
    class="ep-table-container"
    @scroll="onScroll"
  >
    <table :class="['ep-table', classes]">
      <!-- @slot Table header slot. Use this to define your table headers with columns and sorting. -->
      <slot
        name="thead"
        v-bind="{ visibleColumns, showActionsMenu }"
      />
      <tbody ref="tableBody">
        <tr
          v-for="row in data"
          :key="row.id"
          @click="onRowClick(row)"
        >
          <template
            v-for="column in visibleColumns"
            :key="`body-${column.key}`"
          >
            <td>
              <!-- @slot Custom cell content for a specific column. The slot name is dynamically generated as `cell-${column.key}`. -->
              <slot
                v-if="$slots[`cell-${column.key}`]"
                :name="`cell-${column.key}`"
                v-bind="{ row, column }"
              />
              <ep-table-cell
                v-else
                :row="row"
                :column="column"
              />
            </td>
          </template>
          <td
            v-if="showActionsMenu"
            class="ep-table__actions-menu"
          >
            <!-- @slot Actions menu for each row. Receives the current row data. -->
            <slot
              name="actions-menu"
              v-bind="{ row }"
            />
          </td>
        </tr>
      </tbody>
    </table>
    <table
      v-show="fixedHeader"
      ref="tableFixed"
      class="ep-table ep-table--fixed-header"
    >
      <!-- @slot Fixed header slot for when using fixed header mode. Syncs with the main table header. -->
      <slot
        name="thead-fixed"
        v-bind="{ visibleColumns, showActionsMenu }"
      />
    </table>
  </div>
</template>
