// packages/epicenter-components-react/src/components/table/EpTablePagination.tsx
import React, { useMemo } from 'react'

import { EpButton } from '../button/EpButton'
import { EpFlex } from '../flexbox/EpFlex'
import { EpFooter } from '../footer/EpFooter'
import { EpSelect } from '../select/EpSelect'

export interface EpTablePaginationProps {
  /** Additional CSS classes */
  className?: string
  /** Current page number */
  currentPage: number
  /** Callback when page changes */
  onPageChange: (page: number) => void
  /** Callback when results per page changes */
  onResultsPerPageChange: (value: number) => void
  /** Results per page */
  resultsPerPage: number
  /** Show individual page buttons */
  showPages?: boolean
  /** Total number of pages */
  totalPages: number
}

const resultsPerPageOptions = [
  { label: '10', value: 10 },
  { label: '20', value: 20 },
  { label: '50', value: 50 },
  { label: '100', value: 100 }
]

/**
 * EpTablePagination - Pagination controls for tables
 * 
 * Provides page navigation with optional page numbers, ellipsis truncation,
 * and results-per-page selector.
 */
export const EpTablePagination: React.FC<EpTablePaginationProps> = ({
  currentPage,
  showPages = false,
  resultsPerPage,
  totalPages,
  onPageChange,
  onResultsPerPageChange,
  className = ''
}) => {
  const truncationThreshold = 9

  const shouldShowStartEllipsis = useMemo(() => {
    return totalPages > truncationThreshold && currentPage > 3
  }, [totalPages, currentPage])

  const shouldShowEndEllipsis = useMemo(() => {
    return totalPages > truncationThreshold && currentPage < totalPages - 2
  }, [totalPages, currentPage])

  const pageRange = useMemo(() => {
    const range: number[] = []
    if (totalPages <= truncationThreshold) {
      for (let i = 2; i < totalPages; i++) {
        range.push(i)
      }
    } else {
      if (currentPage <= 3) {
        for (let i = 2; i <= 4; i++) {
          range.push(i)
        }
      } else if (currentPage >= totalPages - 2) {
        for (let i = totalPages - 3; i < totalPages; i++) {
          range.push(i)
        }
      } else {
        for (let i = currentPage - 1; i <= currentPage + 1; i++) {
          range.push(i)
        }
      }
    }
    return range
  }, [totalPages, currentPage])

  const prevPage = () => {
    if (currentPage > 1) {
      onPageChange(currentPage - 1)
    }
  }

  const nextPage = () => {
    if (currentPage < totalPages) {
      onPageChange(currentPage + 1)
    }
  }

  const resultsPerPageControl = (
    <EpFlex className="justify-end align-center gap-10 text--overflow-hidden">
      Results per page
      <div style={{ '--ep-input-styler-width': '7.5rem' } as React.CSSProperties}>
        <EpSelect
          value={resultsPerPage}
          selectId="resultsPerPage"
          options={resultsPerPageOptions}
          onChange={(value) => onResultsPerPageChange(Number(value))}
        />
      </div>
    </EpFlex>
  )

  const pageControls = (
    <EpFlex>
      <EpButton
        disabled={currentPage === 1}
        aria-label="Previous page"
        onClick={prevPage}
        iconLeft={
          <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M10 12l-4-4 4-4" stroke="currentColor" strokeWidth="2" fill="none" />
          </svg>
        }
      />
      {showPages && (
        <>
          <EpButton
            aria-label="First page"
            className={currentPage === 1 ? 'ep-button--selected' : ''}
            onClick={() => onPageChange(1)}
          >
            1
          </EpButton>
          {shouldShowStartEllipsis && <span>...</span>}
          {pageRange.map((page) => (
            <EpButton
              key={page}
              aria-label={`Page ${page}`}
              className={currentPage === page ? 'ep-button--selected' : ''}
              onClick={() => onPageChange(page)}
            >
              {page.toString()}
            </EpButton>
          ))}
          {shouldShowEndEllipsis && <span>...</span>}
          {totalPages > 1 && (
            <EpButton
              aria-label="Last page"
              className={currentPage === totalPages ? 'ep-button--selected' : ''}
              onClick={() => onPageChange(totalPages)}
            >
              {totalPages.toString()}
            </EpButton>
          )}
        </>
      )}
      <EpButton
        aria-label="Next page"
        disabled={currentPage === totalPages}
        onClick={nextPage}
        iconRight={
          <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M6 12l4-4-4-4" stroke="currentColor" strokeWidth="2" fill="none" />
          </svg>
        }
      />
    </EpFlex>
  )

  return (
    <div className={`ep-table-pagination${className ? ` ${className}` : ''}`}>
      <EpFooter
        rightGap="1rem"
        leftFlex="0 1 40rem"
        left={resultsPerPageControl}
        right={pageControls}
      />
    </div>
  )
}

// packages/epicenter-components-vue/src/components/table/EpTablePagination.vue
<script setup lang="ts">
  import ArrowLeft01 from '@ericpitcock/epicenter-icons-vue/ArrowLeft01'
  import ArrowRight01 from '@ericpitcock/epicenter-icons-vue/ArrowRight01'
  import { computed } from 'vue'

  import type { SelectOption } from '../../types'
  import EpButton from '../button/EpButton.vue'
  import EpFlex from '../flexbox/EpFlex.vue'
  import EpFooter from '../footer/EpFooter.vue'
  import EpSelect from '../select/EpSelect.vue'

  interface EpTablePaginationProps {
    currentPage: number
    resultsPerPage: number
    showPages?: boolean
    totalPages: number
  }

  const {
    resultsPerPage,
    currentPage,
    totalPages,
    showPages = false,
  } = defineProps<EpTablePaginationProps>()

  const emit = defineEmits<{
    pageChange: [page: number]
    'update:resultsPerPage': [value: number]
  }>()

  const resultsPerPageOptions: SelectOption[] = [
    { label: '10', value: 10 },
    { label: '20', value: 20 },
    { label: '50', value: 50 },
    { label: '100', value: 100 }
  ]

  const onResultsPerPageChange = (value: unknown): void => {
    emit('update:resultsPerPage', Number(value))
  }

  const prevPage = (): void => {
    if (currentPage > 1) {
      emit('pageChange', currentPage - 1)
    }
  }

  const nextPage = (): void => {
    if (currentPage < totalPages) {
      emit('pageChange', currentPage + 1)
    }
  }

  const truncationThreshold = 9

  const shouldShowStartEllipsis = computed(() => {
    return totalPages > truncationThreshold && currentPage > 3
  })

  const shouldShowEndEllipsis = computed(() => {
    return totalPages > truncationThreshold && currentPage < totalPages - 2
  })

  const pageRange = computed((): number[] => {
    const range: number[] = []
    if (totalPages <= truncationThreshold) {
      for (let i = 2; i < totalPages; i++) {
        range.push(i)
      }
    } else {
      if (currentPage <= 3) {
        for (let i = 2; i <= 4; i++) {
          range.push(i)
        }
      } else if (currentPage >= totalPages - 2) {
        for (let i = totalPages - 3; i < totalPages; i++) {
          range.push(i)
        }
      } else {
        for (let i = currentPage - 1; i <= currentPage + 1; i++) {
          range.push(i)
        }
      }
    }
    return range
  })
</script>

<template>
  <div class="ep-table-pagination">
    <ep-footer
      right-gap="1rem"
      left-flex="0 1 40rem"
    >
      <template #right>
        <ep-button
          :disabled="currentPage === 1"
          aria-label="Previous page"
          @click="prevPage"
        >
          <template #icon-left>
            <arrow-left01 />
          </template>
        </ep-button>
        <template v-if="showPages">
          <ep-button
            aria-label="First page"
            :class="{ 'ep-button--selected': currentPage === 1 }"
            @click="emit('pageChange', 1)"
          >
            1
          </ep-button>
          <span v-if="shouldShowStartEllipsis">...</span>
          <ep-button
            v-for="page in pageRange"
            :key="page"
            aria-label="Page {{ page }}"
            :class="{ 'ep-button--selected': currentPage === page }"
            @click="emit('pageChange', page)"
          >
            {{ page.toString() }}
          </ep-button>
          <span v-if="shouldShowEndEllipsis">...</span>
          <ep-button
            v-if="totalPages > 1"
            aria-label="Last page"
            :class="{ 'ep-button--selected': currentPage === totalPages }"
            @click="emit('pageChange', totalPages)"
          >
            {{ totalPages.toString() }}
          </ep-button>
        </template>
        <ep-button
          aria-label="Next page"
          :disabled="currentPage === totalPages"
          @click="nextPage"
        >
          <template #icon-right>
            <arrow-right01 />
          </template>
        </ep-button>
      </template>
      <template #left>
        <ep-flex class="justify-end align-center gap-10 text--overflow-hidden">
          Results per page
          <div style="--ep-input-width: 7.5rem;">
            <ep-select
              :model-value="resultsPerPage"
              select-id="resultsPerPage"
              :options="resultsPerPageOptions"
              @update:model-value="onResultsPerPageChange"
            />
          </div>
        </ep-flex>
      </template>
    </ep-footer>
  </div>
</template>
