// packages/epicenter-vue-components/src/components/image/EpImage.vue
<script setup>
  import { computed, onBeforeUnmount, onMounted, ref } from 'vue'

  const props = defineProps({
    /**
     * The source URL of the image.
     */
    src: {
      type: String,
      required: true,
    },
    /**
     * The alt text for the image.
     */
    alt: {
      type: String,
      default: '',
    },
    /**
     * The width of the image.
     */
    width: {
      type: [String, Number],
      default: '100%',
    },
    /**
     * The height of the image.
     */
    height: {
      type: [String, Number],
      default: '100%',
    },
    /**
     * Additional CSS class name for the image element.
     */
    className: {
      type: String,
      default: '',
    },
    /**
     * URL of the placeholder image to display while loading.
     */
    placeholder: {
      type: String,
      default: '',
    },
    /**
     * The background color of the placeholder.
     */
    placeholderColor: {
      type: String,
      default: '#f5f5f5',
    },
    /**
     * The opacity of the placeholder.
     */
    placeholderOpacity: {
      type: Number,
      default: 1,
    },
    /**
     * If true, enables lazy loading using Intersection Observer.
     */
    lazy: {
      type: Boolean,
      default: true,
    },
  })

  const isLoaded = ref(false)
  const imageEl = ref(null)
  let observer = null

  const placeholderStyle = computed(() => {
    return {
      width: props.width,
      height: props.height,
      backgroundColor: props.placeholderColor,
      opacity: props.placeholderOpacity,
      backgroundImage: props.placeholder ? `url(${props.placeholder})` : '',
      backgroundSize: 'cover',
    }
  })

  const addLazyLoadListener = () => {
    observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          loadImage()
          observer.unobserve(entry.target)
        }
      })
    })

    if (imageEl.value) {
      observer.observe(imageEl.value)
    }
  }

  const loadImage = () => {
    const img = new Image()
    img.src = props.src
    img.onload = () => {
      isLoaded.value = true
    }
  }

  onMounted(() => {
    if (props.lazy) {
      addLazyLoadListener()
    } else {
      loadImage()
    }
  })

  onBeforeUnmount(() => {
    if (observer) {
      observer.disconnect()
      observer = null
    }
  })
</script>

<template>
  <div
    ref="imageEl"
    class="ep-image"
  >
    <img
      v-if="isLoaded"
      :src="src"
      :alt="alt"
      :width="width"
      :height="height"
      :class="className"
    >
    <div
      v-else
      class="image__placeholder"
      :style="placeholderStyle"
    />
  </div>
</template>

<style lang="scss" scoped>
  .image {
    display: inline-block;
    position: relative;
    overflow: hidden;

    img {
      display: block;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .image__placeholder {
      position: absolute;
      top: 0;
      left: 0;
    }
  }
</style>

// packages/epicenter-react-components/src/components/image/EpImage.tsx
import React, { useState, useRef, useEffect, CSSProperties } from 'react';

interface EpImageProps {
  /** The source URL of the image */
  src: string;
  /** The alt text for the image */
  alt?: string;
  /** The width of the image */
  width?: string | number;
  /** The height of the image */
  height?: string | number;
  /** Additional CSS class name for the image element */
  className?: string;
  /** URL of the placeholder image to display while loading */
  placeholder?: string;
  /** The background color of the placeholder */
  placeholderColor?: string;
  /** The opacity of the placeholder */
  placeholderOpacity?: number;
  /** If true, enables lazy loading using Intersection Observer */
  lazy?: boolean;
}

/**
 * EpImage - An image component with lazy loading and placeholder support
 */
const EpImage: React.FC<EpImageProps> = ({
  src,
  alt = '',
  width = '100%',
  height = '100%',
  className = '',
  placeholder = '',
  placeholderColor = '#f5f5f5',
  placeholderOpacity = 1,
  lazy = true,
}) => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [shouldLoad, setShouldLoad] = useState(!lazy);
  const imageRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!lazy) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setShouldLoad(true);
            observer.disconnect();
          }
        });
      },
      { threshold: 0.01 }
    );

    if (imageRef.current) {
      observer.observe(imageRef.current);
    }

    return () => {
      observer.disconnect();
    };
  }, [lazy]);

  const placeholderStyle: CSSProperties = {
    width,
    height,
    backgroundColor: placeholderColor,
    opacity: placeholderOpacity,
    backgroundImage: placeholder ? `url(${placeholder})` : undefined,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  };

  const imageStyle: CSSProperties = {
    width,
    height,
    objectFit: 'cover',
  };

  return (
    <div
      ref={imageRef}
      className={`ep-image${className ? ` ${className}` : ''}`}
      style={placeholderStyle}
    >
      {shouldLoad && (
        <img
          src={src}
          alt={alt}
          style={{
            ...imageStyle,
            opacity: isLoaded ? 1 : 0,
            transition: 'opacity 0.3s ease-in-out',
          }}
          onLoad={() => setIsLoaded(true)}
        />
      )}
    </div>
  );
};

EpImage.displayName = 'EpImage';

export default EpImage;
