// packages/epicenter-vue-components/src/components/container/EpContainer.vue
<template>
  <div
    ref="epContainer"
    class="ep-container"
  >
    <div
      v-if="$slots.header"
      class="ep-container__header"
    >
      <!-- @slot Header content of the container -->
      <slot name="header" />
    </div>
    <div class="ep-container__content">
      <!-- @slot Main content of the container -->
      <slot />
    </div>
    <div
      v-if="$slots.footer"
      class="ep-container__footer"
    >
      <!-- @slot Footer content of the container -->
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup>
  import { useTemplateRef } from 'vue'

  defineOptions({
    name: 'EpContainer'
  })

  const epContainer = useTemplateRef('epContainer')

  defineExpose({
    epContainer
  })
</script>

// packages/epicenter-components-react/src/components/container/EpContainer.tsx
import { ReactNode, forwardRef } from 'react';

export interface EpContainerProps {
  /** Header content of the container */
  header?: ReactNode;
  /** Main content of the container */
  children?: ReactNode;
  /** Footer content of the container */
  footer?: ReactNode;
  /** Additional CSS classes */
  className?: string;
}

/**
 * EpContainer - A container component with optional header and footer sections
 */
export const EpContainer = forwardRef<HTMLDivElement, EpContainerProps>(({
  header,
  children,
  footer,
  className = ''
}, ref) => {
  return (
    <div ref={ref} className={`ep-container${className ? ` ${className}` : ''}`}>
      {header && (
        <div className="ep-container__header">
          {header}
        </div>
      )}
      <div className="ep-container__content">
        {children}
      </div>
      {footer && (
        <div className="ep-container__footer">
          {footer}
        </div>
      )}
    </div>
  );
});

EpContainer.displayName = 'EpContainer';
