// packages/epicenter-components-react/src/components/map/EpMap.tsx
import React, { useEffect, useRef, useState } from 'react'

export interface PinLocation {
  lat: number
  lng: number
}

export interface MapSource {
  id: string
  source: any
}

export interface EpMapProps {
  /** Mapbox access token (required) */
  accessToken: string
  /** Additional CSS classes */
  className?: string
  /** Fit map to bounds of source data */
  fitToBounds?: boolean
  /** Map center coordinates [lng, lat] */
  mapCenter?: [number, number]
  /** Map layer configuration */
  mapLayer?: any
  /** Map source configuration */
  mapSource?: MapSource | null
  /** Mapbox style URL */
  mapStyle?: string
  /** Map zoom level */
  mapZoom?: number
  /** Show navigation control */
  navigationControl?: boolean
  /** Callback when center changes */
  onCenterChange?: (center: [number, number]) => void
  /** Callback when pin is dropped */
  onDropPin?: (location: PinLocation) => void
  /** Callback when zoom changes */
  onZoomChange?: (zoom: number) => void
  /** Array of pin locations to display */
  pinLocations?: PinLocation[]
  /** Enable scroll zoom */
  scrollZoom?: boolean
}

/**
 * EpMap - Mapbox GL wrapper component
 * 
 * Interactive map with pin markers, custom layers, and navigation controls.
 * Automatically resizes with container using ResizeObserver.
 */
export const EpMap: React.FC<EpMapProps> = ({
  accessToken,
  mapCenter = [-122.3321, 47.6062],
  mapZoom = 12,
  mapStyle = 'mapbox://styles/mapbox/streets-v11',
  mapSource = null,
  mapLayer = null,
  pinLocations = [],
  scrollZoom = true,
  navigationControl = true,
  fitToBounds = false,
  onCenterChange,
  onZoomChange,
  className = ''
}) => {
  const mapContainerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<any>(null)
  const markersRef = useRef<any[]>([])
  const mapboxglRef = useRef<any>(null)
  const [init, setInit] = useState(true)

  // Load map
  useEffect(() => {
    const loadMap = async () => {
      const mapboxgl = (await import('mapbox-gl')).default
      await import('mapbox-gl/dist/mapbox-gl.css')
      mapboxglRef.current = mapboxgl

      if (!mapContainerRef.current) return

      mapRef.current = new mapboxgl.Map({
        accessToken,
        container: mapContainerRef.current,
        center: mapCenter,
        zoom: mapZoom,
        style: mapStyle
      })

      // Various options
      if (!scrollZoom) mapRef.current.scrollZoom.disable()
      if (navigationControl) mapRef.current.addControl(new mapboxgl.NavigationControl())

      mapRef.current.on('load', () => {
        // map layer
        if (mapSource) addSource(mapSource, mapLayer)
        // fit to bounds
        if (fitToBounds && mapSource) {
          fitBoundsToSource(getBounds(mapSource.source.data.geometry.coordinates))
        }
        // if pin locations exist, add them
        if (pinLocations.length) addMarkers()
        setInit(false)
      })

      mapRef.current.on('dragend', () => {
        const center = mapRef.current.getCenter()
        onCenterChange?.([center.lng, center.lat])
      })
    }

    loadMap()

    return () => {
      if (mapRef.current) {
        removeMarkers()
        if (mapRef.current.getLayer('test')) mapRef.current.removeLayer('test')
        if (mapRef.current.getSource('test')) mapRef.current.removeSource('test')
        mapRef.current.remove()
      }
    }
  }, [])

  // Watch for map center changes
  useEffect(() => {
    if (!init && mapRef.current) {
      onCenterChange?.(mapCenter)
      flyTo(mapCenter, mapZoom)
    }
  }, [mapCenter])

  // Watch for map zoom changes
  useEffect(() => {
    if (!init && mapRef.current) {
      onZoomChange?.(mapZoom)
      flyTo(mapCenter, mapZoom)
    }
  }, [mapZoom])

  // Watch for map style changes
  useEffect(() => {
    if (!init && mapRef.current) {
      mapRef.current.setStyle(mapStyle)
    }
  }, [mapStyle])

  // Watch for pin location changes
  useEffect(() => {
    if (!init && mapRef.current) {
      removeMarkers()
      addMarkers()
    }
  }, [pinLocations])

  // Watch for scroll zoom changes
  useEffect(() => {
    if (!init && mapRef.current) {
      if (scrollZoom) {
        mapRef.current.scrollZoom.enable()
      } else {
        mapRef.current.scrollZoom.disable()
      }
    }
  }, [scrollZoom])

  // Resize observer
  useEffect(() => {
    if (!mapContainerRef.current || !mapRef.current) return

    const observer = new ResizeObserver(() => {
      if (mapRef.current) {
        setTimeout(() => {
          mapRef.current.resize()
        }, 0)
      }
    })

    observer.observe(mapContainerRef.current)

    return () => {
      observer.disconnect()
    }
  }, [init])

  const addMarkers = () => {
    if (!mapboxglRef.current || !mapRef.current) return
    pinLocations.forEach((location) => {
      const marker = new mapboxglRef.current.Marker()
        .setLngLat([location.lng, location.lat])
        .addTo(mapRef.current)
      markersRef.current.push(marker)
    })
  }

  const removeMarkers = () => {
    markersRef.current.forEach((marker) => marker.remove())
    markersRef.current = []
  }

  const flyTo = (center = mapCenter, zoom = mapZoom) => {
    if (mapRef.current) {
      mapRef.current.flyTo({ center, zoom })
    }
  }

  const getBounds = (coordinates: number[][]) => {
    if (!mapboxglRef.current) return null
    return coordinates.reduce(
      (bounds, coord) => bounds.extend(coord),
      new mapboxglRef.current.LngLatBounds(coordinates[0], coordinates[0])
    )
  }

  const fitBoundsToSource = (bounds: any) => {
    if (mapRef.current && bounds) {
      mapRef.current.fitBounds(bounds, {
        linear: false,
        duration: 1000,
        padding: 60
      })
    }
  }

  const addSource = (source: MapSource, layer: any) => {
    if (mapRef.current) {
      mapRef.current.addSource(source.id, source.source)
      if (layer) mapRef.current.addLayer(layer)
    }
  }

  return (
    <div className={`ep-map${className ? ` ${className}` : ''}`}>
      <div ref={mapContainerRef} className="ep-map__canvas" />
    </div>
  )
}

// packages/epicenter-components-vue/src/components/map/EpMap.vue
<script setup lang="ts">
  import 'mapbox-gl/dist/mapbox-gl.css'
  import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'

  interface MapSource {
    id: string
    source: Record<string, unknown>
  }

  interface EpMapProps {
    accessToken: string
    fitToBounds?: boolean
    mapCenter?: [number, number]
    mapLayer?: Record<string, unknown> | null
    mapSource?: (MapSource & { source: { data: { geometry: { coordinates: [number, number][] } } } }) | null
    mapStyle?: string
    mapZoom?: number
    navigationControl?: boolean
    pinLocations?: [number, number][]
    scrollZoom?: boolean
  }

  const {
    accessToken,
    fitToBounds = false,
    mapCenter = [-122.3321, 47.6062],
    mapLayer = null,
    mapSource = null,
    mapStyle = 'mapbox://styles/mapbox/streets-v11',
    mapZoom = 12,
    navigationControl = true,
    pinLocations = [],
    scrollZoom = true,
  } = defineProps<EpMapProps>()

  const emit = defineEmits<{
    centerChange: [center: [number, number]]
    dropPin: []
    zoomChange: [zoom: number]
  }>()

  const init = ref(true)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const map = ref<any>(null)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const markers = ref<any[]>([])
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let mapboxgl: any = null

  watch(() => mapCenter, (newCenter) => {
    emit('centerChange', newCenter)
    flyTo(newCenter, mapZoom)
  })

  watch(() => mapZoom, (newZoom) => {
    emit('zoomChange', newZoom)
    flyTo(mapCenter, newZoom)
  })

  watch(() => mapStyle, (newStyle: string) => {
    map.value.setStyle(newStyle)
  })

  watch(() => pinLocations, () => {
    removeMarkers()
    addMarkers()
  })

  watch(() => scrollZoom, (newScrollZoom: boolean) => {
    if (newScrollZoom) {
      map.value.scrollZoom.enable()
    } else {
      map.value.scrollZoom.disable()
    }
  })

  const epMapContainer = ref<HTMLDivElement | null>(null)

  const observer = new ResizeObserver(() => {
    if (map.value) {
      nextTick(() => {
        map.value.resize()
      })
    }
  })

  onMounted(() => {
    loadMap().then(() => {
      if (mapSource && mapLayer) addSource(mapSource, mapLayer)
      if (fitToBounds && mapSource) {
        fitBounds(getBounds(mapSource.source.data.geometry.coordinates))
      }
      if (pinLocations.length) addMarkers()
      init.value = false
    })

    if (epMapContainer.value) {
      observer.observe(epMapContainer.value)
    }
  })

  onBeforeUnmount(() => {
    observer.disconnect()

    if (map.value) {
      removeMarkers()

      if (map.value.getLayer('test')) map.value.removeLayer('test')
      if (map.value.getSource('test')) map.value.removeSource('test')
      map.value.remove()
    }
  })

  const loadMap = (): Promise<void> => {
    return new Promise((resolve) => {
      import('mapbox-gl').then((module) => {
        mapboxgl = module.default
        map.value = new mapboxgl.Map({
          accessToken: accessToken,
          container: 'ep-map',
          center: mapCenter,
          zoom: mapZoom,
          style: mapStyle,
        })

        if (!scrollZoom) map.value.scrollZoom.disable()
        if (navigationControl) map.value.addControl(new mapboxgl.NavigationControl())

        map.value.on('load', () => resolve())
        map.value.on('dragend', onDragEnd)
      })
    })
  }

  const addMarkers = (): void => {
    pinLocations.forEach((location) => {
      const marker = new mapboxgl.Marker().setLngLat(location).addTo(map.value)
      markers.value.push(marker)
    })
  }

  const removeMarkers = (): void => {
    markers.value.forEach((marker) => marker.remove())
    markers.value = []
  }

  const flyTo = (center: [number, number] = mapCenter, zoom: number = mapZoom): void => {
    map.value.flyTo({
      center,
      zoom
    })
  }

  const onDragEnd = (): void => {
    const center = map.value.getCenter()
    emit('centerChange', [center.lng, center.lat])
  }

  const getBounds = (coordinates: [number, number][]): unknown => {
    return coordinates.reduce(
      (bounds: unknown, coord: [number, number]) => (bounds as { extend: (c: [number, number]) => unknown }).extend(coord),
      new mapboxgl.LngLatBounds(coordinates[0], coordinates[0])
    )
  }

  const fitBounds = (bounds: unknown): void => {
    map.value.fitBounds(bounds, {
      linear: false,
      duration: 1000,
      padding: 60
    })
  }

  const addSource = (source: MapSource, layer: Record<string, unknown>): void => {
    map.value.addSource(source.id, source.source)
    map.value.addLayer(layer)
  }
</script>

<template>
  <div
    ref="epMapContainer"
    class="ep-map-container"
  >
    <div id="ep-map" />
  </div>
</template>
