// packages/epicenter-components-vue/src/components/status-indicator/EpStatusIndicator.vue
<script setup lang="ts">
  interface EpStatusIndicatorProps {
    /**
     * If true, the status indicator will pulse.
     */
    pulse?: boolean
  }

  const { pulse = false } = defineProps<EpStatusIndicatorProps>()
</script>

<template>
  <span class="ep-status-indicator">
    <span
      class="ep-status-indicator__dot"
      :class="{ 'ep-status-indicator__dot--pulse': pulse }"
    />
    <!-- @slot Default slot for label or text content next to the indicator. -->
    <slot />
  </span>
</template>

// packages/epicenter-components-react/src/components/status-indicator/EpStatusIndicator.tsx
import React, { ReactNode } from 'react';

export interface EpStatusIndicatorProps {
  /** Label or text content next to the indicator */
  children?: ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** If true, the status indicator will pulse */
  pulse?: boolean;
}

/**
 * EpStatusIndicator - A status indicator component with optional pulsing animation
 */
export const EpStatusIndicator: React.FC<EpStatusIndicatorProps> = ({ 
  pulse = false, 
  children, 
  className = '' 
}) => {
  const dotClasses = ['ep-status-indicator__dot'];
  if (pulse) {
    dotClasses.push('ep-status-indicator__dot--pulse');
  }

  return (
    <span className={`ep-status-indicator${className ? ` ${className}` : ''}`}>
      <span className={dotClasses.join(' ')} />
      {children}
    </span>
  );
};

EpStatusIndicator.displayName = 'EpStatusIndicator';
