// packages/epicenter-components-vue/src/components/input-styler/EpInputStyler.vue
<script setup lang="ts">
  import Cancel01 from '@ericpitcock/epicenter-icons-vue/Cancel01'
  import { computed } from 'vue'

  import type { Size } from '../../types'

  interface EpInputStylerProps {
    clearable?: boolean
    disabled?: boolean
    error?: boolean
    errorEnabled?: boolean
    errorMessage?: string
    hasInput?: boolean
    id?: string
    label?: string
    size?: Size
  }

  const {
    clearable = false,
    disabled = false,
    error = false,
    errorEnabled = false,
    errorMessage = '',
    hasInput = false,
    id = '',
    label = '',
    size = 'default',
  } = defineProps<EpInputStylerProps>()

  defineEmits<{
    click: []
  }>()

  const computedClasses = computed(() => ({
    [`ep-input-styler--${size}`]: size !== 'default',
    'ep-input-styler--disabled': disabled,
    'ep-input-styler--error': error,
  }))
</script>

<template>
  <div class="ep-input-styler__container">
    <label
      v-if="label"
      class="ep-input-styler__label"
      :for="id"
    >
      {{ label }}
    </label>
    <div :class="['ep-input-styler', computedClasses]">
      <div class="ep-input-styler__inner">
        <div
          v-if="$slots['icon-left']"
          :class="[
            'ep-input-styler__icon-left',
            `ep-input-styler__icon-left--${size}`
          ]"
        >
          <slot name="icon-left" />
        </div>
        <div
          v-if="$slots['icon-right'] || clearable"
          :class="[
            'ep-input-styler__icon-right',
            `ep-input-styler__icon-right--${size}`
          ]"
        >
          <slot
            v-if="$slots['icon-right'] && !clearable"
            name="icon-right"
          />
          <Cancel01
            v-if="clearable && hasInput && !disabled"
            class="ep-input-styler__icon-right--clickable"
            @click="$emit('click')"
          />
        </div>
      </div>
      <slot />
    </div>
    <p
      v-if="errorEnabled"
      class="ep-input-styler__error-message"
    >
      {{ errorMessage || '\u00A0' }}
    </p>
  </div>
</template>

// packages/epicenter-components-react/src/components/input-styler/EpInputStyler.tsx
import { Cancel01 } from '@ericpitcock/epicenter-icons-react/Cancel01.jsx'
import React, { ReactNode } from 'react'

export interface EpInputStylerProps {
  /**
   * Input/select element to wrap
   */
  children?: ReactNode
  /**
   * If true, shows clear button when input has value
   */
  clearable?: boolean
  /**
   * If true, applies disabled styling
   */
  disabled?: boolean
  /**
   * If true, applies error styling
   */
  error?: boolean
  /**
   * If true, enables error state and message display
   */
  errorEnabled?: boolean
  /**
   * Error message displayed below the input
   */
  errorMessage?: string
  /**
   * Whether the input has a value
   */
  hasInput?: boolean
  /**
   * Icon content for left side
   */
  iconLeft?: ReactNode
  /**
   * Icon content for right side
   */
  iconRight?: ReactNode
  /**
   * If true, makes right icon clickable
   */
  iconRightClickable?: boolean
  /**
   * If true, shows right icon even when clearable
   */
  iconRightVisible?: boolean
  /**
   * The ID to associate with the input/select element
   */
  id?: string
  /**
   * Label text displayed above the input
   */
  label?: string
  /**
   * Handler for clear button click
   */
  onClear?: () => void
  /**
   * Size variant
   * @default 'default'
   */
  size?: 'small' | 'default' | 'large' | 'xlarge'
}

export const EpInputStyler: React.FC<EpInputStylerProps> = ({
  id,
  hasInput = false,
  label,
  clearable = false,
  disabled = false,
  errorEnabled = false,
  error = false,
  errorMessage = '',
  size = 'default',
  iconLeft,
  iconRight,
  iconRightVisible = false,
  onClear,
  children
}) => {
  const stylerClasses = [
    'ep-input-styler',
    size !== 'default' && `ep-input-styler--${size}`,
    disabled && 'ep-input-styler--disabled',
    error && 'ep-input-styler--error'
  ].filter(Boolean).join(' ')

  const showClearButton = clearable && hasInput && !disabled
  const showIconRight = iconRight && (!clearable || iconRightVisible)

  return (
    <div className="ep-input-styler__container">
      {label && (
        <label className="ep-input-styler__label" htmlFor={id}>
          {label}
        </label>
      )}
      <div className={stylerClasses}>
        <div className="ep-input-styler__inner">
          {iconLeft && (
            <div className={`ep-input-styler__icon-left ep-input-styler__icon-left--${size}`}>
              {iconLeft}
            </div>
          )}
          {(showIconRight || showClearButton) && (
            <div className={`ep-input-styler__icon-right ep-input-styler__icon-right--${size}`}>
              {showIconRight && !showClearButton && iconRight}
              {showClearButton && (
                <Cancel01
                  className="ep-input-styler__icon-right--clickable"
                  onClick={onClear}
                />
              )}
            </div>
          )}
        </div>
        {children}
      </div>
      {errorEnabled && (
        <p className="ep-input-styler__error-message">
          {errorMessage || '\u00A0'}
        </p>
      )}
    </div>
  )
}
