// packages/epicenter-react-components/src/components/overlay/EpOverlay.tsx
import React, { ReactNode, useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'

export interface EpOverlayProps {
  /**
   * The type of overlay to display.
   * @default 'modal'
   */
  type?: 'modal' | 'toast'
  /**
   * Controls the visibility of the overlay
   */
  visible?: boolean
  /**
   * Handler called when the overlay should be closed
   */
  onClose?: () => void
  /**
   * If true, automatically dismisses the overlay after the specified duration.
   * @default false
   */
  autoDismiss?: boolean
  /**
   * Duration in milliseconds before auto-dismissing (when autoDismiss is true).
   * @default 3000
   */
  duration?: number
  /**
   * If true, clicking the backdrop will close the overlay.
   * @default true
   */
  backdropClose?: boolean
  /**
   * Content to display inside the overlay dialog
   */
  children?: ReactNode
}

export const EpOverlay: React.FC<EpOverlayProps> = ({
  type = 'modal',
  visible = false,
  onClose,
  autoDismiss = false,
  duration = 3000,
  backdropClose = true,
  children
}) => {
  const dialogRef = useRef<HTMLDialogElement>(null)

  useEffect(() => {
    const dialog = dialogRef.current
    if (!dialog) return

    if (visible) {
      if (type === 'modal') {
        dialog.showModal()
      } else {
        dialog.show()
      }
    } else {
      dialog.close()
    }
  }, [visible, type])

  useEffect(() => {
    if (visible && autoDismiss) {
      const timer = setTimeout(() => {
        onClose?.()
      }, duration)
      
      return () => clearTimeout(timer)
    }
  }, [visible, autoDismiss, duration, onClose])

  const handleBackdropClick = (e: React.MouseEvent<HTMLDialogElement>) => {
    // Only close if clicking directly on the dialog (backdrop)
    if (e.target === dialogRef.current && backdropClose) {
      onClose?.()
    }
  }

  if (!visible) return null

  return createPortal(
    <dialog
      ref={dialogRef}
      className="ep-dialog"
      role="dialog"
      aria-modal={type === 'modal' ? 'true' : undefined}
      onClick={handleBackdropClick}
    >
      {children}
    </dialog>,
    document.body
  )
}

// packages/epicenter-vue-components/src/components/overlays/EpOverlay.vue
<template>
  <Teleport
    defer
    to="#app"
  >
    <dialog
      ref="dialog"
      class="ep-dialog"
      role="dialog"
      :aria-modal="type === 'modal' ? 'true' : undefined"
      @click.self="onBackdropClick"
    >
      <!-- @slot Content to display inside the overlay dialog -->
      <slot />
    </dialog>
  </Teleport>
</template>

<script setup>
  import { ref, watch } from 'vue'

  defineOptions({
    name: 'EpOverlay'
  })

  const props = defineProps({
    /**
     * The type of overlay to display.
     * @values 'modal', 'toast'
     */
    type: {
      type: String,
      default: 'modal',
    },
    /**
     * Controls the visibility of the overlay (use with v-model).
     */
    modelValue: {
      type: Boolean,
      default: false,
    },
    /**
     * If true, automatically dismisses the overlay after the specified duration.
     */
    autoDismiss: {
      type: Boolean,
      default: false,
    },
    /**
     * Duration in milliseconds before auto-dismissing (when autoDismiss is true).
     */
    duration: {
      type: Number,
      default: 3000,
    },
    /**
     * If true, clicking the backdrop will close the overlay.
     */
    backdropClose: {
      type: Boolean,
      default: true,
    },
  })

  const emit = defineEmits(['update:modelValue'])

  const dialog = ref(null)

  watch(() => props.modelValue, (newVal) => {
    if (!dialog.value) return

    if (newVal === true) {
      if (props.type === 'modal') {
        dialog.value.showModal()
      } else {
        dialog.value.show()
      }
    } else if (newVal === false) {
      dialog.value.close()
    }
  },
    { immediate: true }
  )

  const onBackdropClick = () => {
    if (!props.backdropClose) return

    emit('update:modelValue', false)
    dialog.value.close()
  }
</script>

<style lang="scss" scoped>
  .ep-dialog {
    position: absolute;
    top: 3rem;
    right: 3rem;

    &::backdrop {
      background: var(--overlay-color);
      cursor: pointer;
    }
  }
</style>
