// packages/epicenter-react-components/src/components/button/EpButton.tsx
import React, { useMemo, forwardRef, ReactNode, CSSProperties, MouseEvent } from 'react';
import { Link } from 'react-router-dom';

type ButtonSize = 'small' | 'default' | 'large' | 'xlarge';
type ButtonType = 'button' | 'submit';

export interface EpButtonProps {
  /** The size of the button */
  size?: ButtonSize;
  /** The aria-label of the button */
  ariaLabel?: string;
  /** If true, the button will be disabled */
  disabled?: boolean;
  /** The type of the button (only applies when rendered as button element) */
  type?: ButtonType;
  /** Router link destination (renders as Link when provided) */
  to?: string;
  /** URL destination (renders as anchor when provided) */
  href?: string;
  /** Icon displayed on the left side of the button label */
  iconLeft?: ReactNode;
  /** Icon displayed on the right side of the button label */
  iconRight?: ReactNode;
  /** Button content */
  children?: ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** Inline styles */
  style?: CSSProperties;
  /** Click handler */
  onClick?: (event: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void;
  /** Additional props */
  [key: string]: any;
}

/**
 * EpButton - A versatile button component that can render as a button, link, or router link
 */
export const EpButton = forwardRef<HTMLButtonElement | HTMLAnchorElement, EpButtonProps>(({
  size = 'default',
  ariaLabel,
  disabled = false,
  type = 'button',
  to,
  href,
  iconLeft,
  iconRight,
  children,
  className = '',
  ...rest
}, ref) => {
  // Determine the element type based on props (matching Vue logic)
  const Element = useMemo(() => {
    if (to) return Link;
    if (href) return 'a';
    return 'button';
  }, [to, href]) as any;

  // Compute dynamic classes (matching Vue computed classes)
  const computedClasses = useMemo(() => {
    const classes = ['ep-button'];
    
    if (size !== 'default') {
      classes.push(`ep-button--${size}`);
    }
    
    if (disabled) {
      classes.push('ep-button--disabled');
    }
    
    if (className) {
      classes.push(className);
    }
    
    return classes.join(' ');
  }, [size, disabled, className]);

  // Props specific to different element types
  const elementProps: any = {
    className: computedClasses,
    ref,
    ...rest,
  };

  // Add button-specific props
  if (Element === 'button') {
    elementProps.type = type;
    elementProps.disabled = disabled;
  }

  // Add link-specific props
  if (Element === 'a') {
    elementProps.href = href;
    if (disabled) {
      elementProps['aria-disabled'] = true;
      elementProps.onClick = (e: MouseEvent<HTMLAnchorElement>) => e.preventDefault();
    }
  }

  // Add router-link-specific props
  if (Element === Link) {
    elementProps.to = to;
    if (disabled) {
      elementProps['aria-disabled'] = true;
      elementProps.onClick = (e: MouseEvent<HTMLAnchorElement>) => e.preventDefault();
    }
  }

  // Add aria-label if provided
  if (ariaLabel) {
    elementProps['aria-label'] = ariaLabel;
  }

  return (
    <Element {...elementProps}>
      {iconLeft && (
        <span className="ep-button__icon ep-button__icon--left">
          {iconLeft}
        </span>
      )}
      {children}
      {iconRight && (
        <span className="ep-button__icon ep-button__icon--right">
          {iconRight}
        </span>
      )}
    </Element>
  );
});

EpButton.displayName = 'EpButton';

// packages/epicenter-components-vue/src/components/button/EpButton.vue
<script setup lang="ts">
  import { computed, useAttrs } from 'vue'

  import type { ButtonType, Size } from '../../types'

  interface Props {
    /** The aria-label of the button. */
    ariaLabel?: string
    /** If `true`, the button will be disabled. */
    disabled?: boolean
    /** The size of the button. */
    size?: Size
    /** The type of the button. */
    type?: ButtonType
  }

  const {
    size = 'default',
    ariaLabel = '',
    disabled = false,
    type = 'button',
  } = defineProps<Props>()

  defineOptions({ name: 'EpButton' })

  const element = computed(() => {
    const { to, href } = useAttrs()
    return to ? 'router-link' : href ? 'a' : 'button'
  })

  const computedClasses = computed(() => ({
    [`ep-button--${size}`]: size !== 'default',
    'ep-button--disabled': disabled,
  }))
</script>

<template>
  <component
    :is="element"
    :type
    :class="['ep-button', computedClasses]"
    :aria-label="ariaLabel ? ariaLabel : null"
    :disabled="disabled"
  >
    <span
      v-if="$slots['icon-left']"
      class="ep-button__icon ep-button__icon--left"
    >
      <!-- @slot Icon displayed on the left side of the button label -->
      <slot name="icon-left" />
    </span>
    <!-- @slot Default slot for button text/content -->
    <span
      v-if="$slots.default"
      class="ep-button__label"
    >
      <slot />
    </span>
    <span
      v-if="$slots['icon-right']"
      class="ep-button__icon ep-button__icon--right"
    >
      <!-- @slot Icon displayed on the right side of the button label -->
      <slot name="icon-right" />
    </span>
  </component>
</template>
