// packages/epicenter-react-components/src/components/button/EpButton.jsx
import React from 'react';
import PropTypes from 'prop-types';
import EpIcon from '../icon/EpIcon';

const EpButton = ({
  element: Element = 'button',
  size = 'default',
  title,
  label,
  iconLeft,
  iconRight,
  disabled = false,
  ariaLabel,
  className = '',
  ...rest
}) => {
  const computedClasses = `ep-button ep-button--${size} ${className}`;

  return (
    <Element
      className={computedClasses}
      title={title}
      aria-label={ariaLabel || label}
      disabled={disabled}
      {...rest}
    >
      {iconLeft && (
        <span className="ep-button__icon ep-button__icon--left">
          <EpIcon {...iconLeft} />
        </span>
      )}
      {label && <span className="ep-button__label">{label}</span>}
      {iconRight && (
        <span className="ep-button__icon ep-button__icon--right">
          <EpIcon {...iconRight} />
        </span>
      )}
    </Element>
  );
};

EpButton.propTypes = {
  element: PropTypes.elementType,
  size: PropTypes.oneOf(['small', 'default', 'large', 'xlarge']),
  title: PropTypes.string,
  label: PropTypes.string,
  iconLeft: PropTypes.object,
  iconRight: PropTypes.object,
  disabled: PropTypes.bool,
  ariaLabel: PropTypes.string,
  className: PropTypes.string,
};

export default EpButton;

// packages/epicenter-components-vue/src/components/button/EpButton.vue
<script setup>
  import { computed, useAttrs } from 'vue'

  const props = defineProps({
    /**
     * The size of the button.
     */
    size: {
      type: String,
      default: 'default',
      validator: (value) => [
        'small',
        'default',
        'large',
        'xlarge',
      ].includes(value)
    },
    /**
     * The aria-label of the button.
     */
    ariaLabel: {
      type: String,
      default: ''
    },
    /**
     * If `true`, the button will be disabled.
     */
    disabled: {
      type: Boolean,
      default: false
    },
    /**
     * The  type of the button.
     */
    type: {
      type: String,
      default: 'button',
      validator: (value) => [
        'button',
        'submit',
      ].includes(value)
    },
  })

  const element = computed(() => {
    const { to, href } = useAttrs()
    return to ? 'router-link' : href ? 'a' : 'button'
  })

  const computedClasses = computed(() => ({
    [`ep-button--${props.size}`]: props.size !== 'default',
    'ep-button--disabled': props.disabled,
  }))
</script>

<template>
  <component
    :is="element"
    :type
    :class="['ep-button', computedClasses]"
    :aria-label="ariaLabel ? ariaLabel : null"
    :disabled="disabled"
  >
    <span
      v-if="$slots['icon-left']"
      class="ep-button__icon ep-button__icon--left"
    >
      <!-- @slot Icon displayed on the left side of the button label -->
      <slot name="icon-left" />
    </span>
    <!-- @slot Default slot for button text/content -->
    <span
      v-if="$slots.default"
      class="ep-button__label"
    >
      <slot />
    </span>
    <span
      v-if="$slots['icon-right']"
      class="ep-button__icon ep-button__icon--right"
    >
      <!-- @slot Icon displayed on the right side of the button label -->
      <slot name="icon-right" />
    </span>
  </component>
</template>
