// packages/epicenter-components-react/src/components/empty-state/EpEmptyState.tsx
import React, { ReactNode } from 'react'

export interface EpEmptyStateProps {
  /**
   * Main content/message of the empty state
   */
  children?: ReactNode
  /**
   * Call-to-action button or link
   */
  cta?: ReactNode
  /**
   * Layout direction of the empty state content.
   * @default 'column'
   */
  direction?: 'column' | 'row'
  /**
   * Image or icon to display in the empty state
   */
  img?: ReactNode
  /**
   * Horizontal alignment of the content.
   * @default 'center'
   */
  justify?: 'left' | 'center' | 'right'
  /**
   * Additional descriptive text or instructions
   */
  subtext?: ReactNode
}

export const EpEmptyState: React.FC<EpEmptyStateProps> = ({
  direction = 'column',
  justify = 'center',
  img,
  children,
  subtext,
  cta
}) => {
  const classes = [
    'ep-empty-state',
    direction === 'column' && 'ep-empty-state--column',
    direction === 'row' && 'ep-empty-state--row',
    justify === 'left' && 'ep-empty-state--justify-left',
    justify === 'right' && 'ep-empty-state--justify-right'
  ].filter(Boolean).join(' ')

  return (
    <div className={classes}>
      {img && (
        <div className="ep-empty-state__img">
          {img}
        </div>
      )}
      <div className="ep-empty-state__body">
        {children}
        {subtext && (
          <div className="text--subtle font-size--small">
            {subtext}
          </div>
        )}
        {cta && (
          <div className="ep-empty-state__body__cta">
            {cta}
          </div>
        )}
      </div>
    </div>
  )
}

// src/components/empty-state/EpEmptyState.vue
<template>
  <div :class="['ep-empty-state', classes]">
    <div class="ep-empty-state__img">
      <img v-if="image.src" :alt="image.alt" class="ep-empty-state__cover" :src="image.src" />
    </div>
    <div class="ep-empty-state__body">
      <h2 class="font-size--large" >{{ message }}</h2>
      <p v-if="subtext" class="text--subtle font-size--small">{{ subtext }}</p>
      <div v-if="$slots.cta" class="ep-empty-state__body__cta">
        <slot name="cta"></slot>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'EpEmptyState',
    props: {
      direction: {
        type: String,
        default: 'column'
      },
      image: {
        type: Object,
        default: () => ({})
      },
      message: {
        type: String,
        default: ''
      },
      subtext: {
        type: String,
        default: ''
      }
    },
    computed: {
      classes() {
        return {
          'ep-empty-state--column': this.direction === 'column',
          'ep-empty-state--row': this.direction === 'row'
        }
      }
    }
  }
</script>
<style lang="scss" scoped>
  .ep-empty-state {
    display: flex;
    gap: 3rem;
    img {
      max-width: 10rem;
    }
    &--column {
      flex-direction: column;
      align-items: center;
      .ep-empty-state__body {
        text-align: center;
      }
    }
    &--row {
      flex-direction: row;
      align-items: center;
    }
    &__body {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }
  }
</style>
