// packages/epicenter-components-react/src/components/menu/EpMenuItem.tsx
import React, { useRef, useState, useCallback, createContext, useContext, KeyboardEvent } from 'react'

export type MenuItemType = 'item' | 'divider' | 'section'

export interface EpMenuItemProps {
  /** Menu item content */
  children?: React.ReactNode
  /** Additional CSS classes */
  className?: string
  /** Whether the menu item is disabled */
  disabled?: boolean
  /** Callback when menu item is selected */
  onSelect?: (event: React.MouseEvent | KeyboardEvent) => void
  /** Submenu content that appears on hover/focus */
  submenu?: React.ReactNode
  /** The type of menu item to render */
  type?: MenuItemType
}

// Context to provide closeParentSubmenu function
const SubmenuContext = createContext<(() => void) | null>(null)

/**
 * EpMenuItem - Menu item component with support for submenus
 * 
 * Can render as interactive item, divider, or section header.
 * Supports nested submenus with keyboard navigation (Arrow keys, Enter, Space).
 */
export const EpMenuItem = React.forwardRef<HTMLDivElement, EpMenuItemProps>(
  (
    {
      disabled = false,
      type = 'item',
      children,
      submenu,
      onSelect,
      className = ''
    },
    ref
  ) => {
    const [showSubmenu, setShowSubmenu] = useState(false)
    const menuItemRef = useRef<HTMLDivElement>(null)
    const hasSubmenu = Boolean(submenu)

    // Inject parent's close function (if this item is in a submenu)
    const closeParentSubmenu = useContext(SubmenuContext)

    // Provide close function for child submenu items
    const closeThisSubmenu = useCallback(() => {
      setShowSubmenu(false)
    }, [])

    const handleMousedown = (event: React.MouseEvent) => {
      if (disabled) {
        // Prevent focus when clicking a disabled menu item
        // This prevents submenus from sticking open when clicking disabled items
        event.preventDefault()
        event.stopPropagation()
      }
    }

    const handleClick = (event: React.MouseEvent) => {
      if (disabled) {
        event.preventDefault()
        event.stopPropagation()
        return
      }

      if (type === 'item') {
        // If this item has a submenu, don't emit select - let keyboard handle it
        if (!hasSubmenu) {
          onSelect?.(event)
          // Close parent submenu if this item is inside one
          closeParentSubmenu?.()
        }
      }
    }

    const handleFocusIn = (event: React.FocusEvent) => {
      // Don't interfere with focus if it's going to a submenu item
      const isSubmenuElement = (event.target as HTMLElement).closest(
        '.ep-menu__item__sub-menu'
      )
      if (isSubmenuElement) {
        return // Let submenu items receive focus normally
      }

      // If focus goes to a child element (like a button), redirect it to the menu item wrapper
      if (event.target !== menuItemRef.current && menuItemRef.current) {
        event.preventDefault()
        event.stopPropagation()
        menuItemRef.current.focus()
      }
    }

    const handleFocusOut = (event: React.FocusEvent) => {
      // Close submenu if focus is leaving this menu item entirely
      if (showSubmenu && menuItemRef.current) {
        // Check if the new focus target is outside this menu item
        const newFocusTarget = event.relatedTarget as Node | null
        if (!menuItemRef.current.contains(newFocusTarget)) {
          setShowSubmenu(false)
        }
      }
    }

    const openSubmenuAndFocusFirst = useCallback(async () => {
      if (!hasSubmenu) return

      setShowSubmenu(true)

      // Wait for DOM update before focusing
      await new Promise((resolve) => setTimeout(resolve, 0))

      const submenuElement = menuItemRef.current?.querySelector('.ep-menu__item__sub-menu')
      const firstItem = submenuElement?.querySelector<HTMLElement>('[role="menuitem"]')

      if (firstItem) {
        // Ensure the first item is focusable
        if (firstItem.getAttribute('tabindex') !== '0') {
          firstItem.setAttribute('tabindex', '0')
        }
        firstItem.focus()
      }
    }, [hasSubmenu])

    const handleKeydown = (event: KeyboardEvent<HTMLDivElement>) => {
      if (type !== 'item') return

      const key = event.key

      // Handle Arrow Left from within submenu - close it and return to parent
      if (key === 'ArrowLeft') {
        if (closeParentSubmenu) {
          // We're inside a submenu, close it and focus parent
          event.preventDefault()
          event.stopPropagation()
          closeParentSubmenu()
          // Focus the parent menu item
          menuItemRef.current
            ?.closest('.ep-menu__item__sub-menu')
            ?.closest<HTMLElement>('.ep-menu__item')
            ?.focus()
          return
        }
        // If we have a submenu and it's open, close it
        if (showSubmenu) {
          event.preventDefault()
          event.stopPropagation()
          setShowSubmenu(false)
          menuItemRef.current?.focus()
        }
      }
      // Handle Enter and Space
      else if (key === 'Enter' || key === ' ') {
        event.preventDefault()
        event.stopPropagation()

        // If has submenu, open it and focus first item
        if (hasSubmenu) {
          openSubmenuAndFocusFirst()
        } else {
          // No submenu - activate the menu item
          onSelect?.(event)
          closeParentSubmenu?.()
        }
      }
      // Arrow right to open submenu if present
      else if (key === 'ArrowRight' && hasSubmenu) {
        event.preventDefault()
        event.stopPropagation()
        openSubmenuAndFocusFirst()
      }
      // Escape to close submenu
      else if (key === 'Escape' && showSubmenu) {
        event.preventDefault()
        event.stopPropagation()
        setShowSubmenu(false)
        menuItemRef.current?.focus()
      }
    }

    const handleMouseover = () => {
      if (hasSubmenu) {
        setShowSubmenu(true)
      }
    }

    const handleMouseleave = () => {
      // Only hide submenu on mouse leave if no element within this menu item has focus
      // This prevents submenu from hiding when using keyboard navigation
      if (!menuItemRef.current?.contains(document.activeElement)) {
        setShowSubmenu(false)
      }
    }

    // Render divider
    if (type === 'divider') {
      return <div className="ep-divider ep-divider--horizontal" role="separator" />
    }

    // Render section header
    if (type === 'section') {
      return (
        <div className="ep-menu__section text-style--section" role="presentation">
          {children}
        </div>
      )
    }

    // Render interactive menu item
    return (
      <SubmenuContext.Provider value={closeThisSubmenu}>
        <div
          ref={(node) => {
            // Update local ref
            (menuItemRef as React.MutableRefObject<HTMLDivElement | null>).current = node
            // Forward ref
            if (typeof ref === 'function') {
              ref(node)
            } else if (ref) {
              (ref as React.MutableRefObject<HTMLDivElement | null>).current = node
            }
          }}
          className={`ep-menu__item${className ? ` ${className}` : ''}`}
          role="menuitem"
          aria-disabled={disabled || undefined}
          aria-haspopup={hasSubmenu ? 'menu' : undefined}
          aria-expanded={hasSubmenu ? showSubmenu : undefined}
          tabIndex={-1}
          onMouseDown={handleMousedown}
          onClick={handleClick}
          onKeyDown={handleKeydown}
          onMouseOver={handleMouseover}
          onMouseLeave={handleMouseleave}
          onFocusCapture={handleFocusIn}
          onBlur={handleFocusOut}
        >
          {children}
          {submenu && (
            <div
              className="ep-menu__item__sub-menu"
              role="menu"
              style={{ display: showSubmenu ? undefined : 'none' }}
            >
              {submenu}
            </div>
          )}
        </div>
      </SubmenuContext.Provider>
    )
  }
)

EpMenuItem.displayName = 'EpMenuItem'

// packages/epicenter-components-vue/src/components/menu/EpMenuItem.vue
<script setup lang="ts">
  import { computed, inject, nextTick, provide, ref, useSlots } from 'vue'

  type MenuItemType = 'item' | 'divider' | 'section'

  interface EpMenuItemProps {
    /** Whether the menu item is disabled. */
    disabled?: boolean
    /** The type of menu item to render. */
    type?: MenuItemType
  }

  const { disabled = false, type = 'item' } = defineProps<EpMenuItemProps>()

  const emit = defineEmits<{
    select: [event: Event]
  }>()

  const slots = useSlots()

  const showSubmenu = ref(false)
  const menuItemRef = ref<HTMLDivElement | null>(null)
  const hasSubmenu = computed(() => !!slots.submenu)

  provide('closeParentSubmenu', () => {
    showSubmenu.value = false
  })

  const closeParentSubmenu = inject<(() => void) | null>('closeParentSubmenu', null)

  const onMousedown = (event: MouseEvent): void => {
    if (disabled) {
      event.preventDefault()
      event.stopPropagation()
    }
  }

  const onClick = (event: MouseEvent): void => {
    if (disabled) {
      event.preventDefault()
      event.stopPropagation()
      return
    }

    if (type === 'item') {
      if (!hasSubmenu.value) {
        emit('select', event)
        closeParentSubmenu?.()
      }
    }
  }

  const onFocusIn = (event: FocusEvent): void => {
    const isSubmenuElement = (event.target as HTMLElement).closest('.ep-menu__item__sub-menu')
    if (isSubmenuElement) {
      return
    }

    if (event.target !== menuItemRef.value && menuItemRef.value) {
      event.preventDefault()
      event.stopPropagation()
      menuItemRef.value.focus()
    }
  }

  const onFocusOut = (event: FocusEvent): void => {
    if (showSubmenu.value && menuItemRef.value) {
      const newFocusTarget = event.relatedTarget as Node | null
      if (!menuItemRef.value.contains(newFocusTarget)) {
        showSubmenu.value = false
      }
    }
  }

  const openSubmenuAndFocusFirst = async (): Promise<void> => {
    if (!hasSubmenu.value) return

    showSubmenu.value = true

    await nextTick()

    const submenu = menuItemRef.value?.querySelector('.ep-menu__item__sub-menu')
    const firstItem = submenu?.querySelector('[role="menuitem"]') as HTMLElement | null

    if (firstItem) {
      if (firstItem.getAttribute('tabindex') !== '0') {
        console.warn('Submenu item had wrong tabindex, fixing it')
        firstItem.setAttribute('tabindex', '0')
      }
      firstItem.focus()
    }
  }

  const onKeydown = (event: KeyboardEvent): void => {
    if (type !== 'item') return

    const key = event.key

    if (key === 'ArrowLeft') {
      if (closeParentSubmenu) {
        event.preventDefault()
        event.stopPropagation()
        closeParentSubmenu()
          ; (menuItemRef.value?.closest('.ep-menu__item__sub-menu')?.closest('.ep-menu__item') as HTMLElement)?.focus()
        return
      }
      if (showSubmenu.value) {
        event.preventDefault()
        event.stopPropagation()
        showSubmenu.value = false
        menuItemRef.value?.focus()
      }
    }
    else if (key === 'Enter' || key === ' ') {
      event.preventDefault()
      event.stopPropagation()

      if (hasSubmenu.value) {
        openSubmenuAndFocusFirst()
      } else {
        emit('select', event)
        closeParentSubmenu?.()
      }
    }
    else if (key === 'ArrowRight' && hasSubmenu.value) {
      event.preventDefault()
      event.stopPropagation()
      openSubmenuAndFocusFirst()
    }
    else if (key === 'Escape' && showSubmenu.value) {
      event.preventDefault()
      event.stopPropagation()
      showSubmenu.value = false
      menuItemRef.value?.focus()
    }
  }

  const onMouseover = (): void => {
    if (hasSubmenu.value) {
      showSubmenu.value = true
    }
  }

  const onMouseleave = (): void => {
    if (!menuItemRef.value?.contains(document.activeElement)) {
      showSubmenu.value = false
    }
  }
</script>

<template>
  <div
    v-if="type === 'divider'"
    class="ep-divider ep-divider--horizontal"
    role="separator"
  />
  <div
    v-else-if="type === 'section'"
    class="ep-menu__section text-style--section"
    role="presentation"
  >
    <!-- @slot Default slot for section label text. -->
    <slot />
  </div>
  <div
    v-else
    ref="menuItemRef"
    class="ep-menu__item"
    role="menuitem"
    :aria-disabled="disabled || undefined"
    :aria-haspopup="hasSubmenu ? 'menu' : undefined"
    :aria-expanded="hasSubmenu ? showSubmenu : undefined"
    @mousedown="onMousedown"
    @click="onClick"
    @keydown="onKeydown"
    @mouseover="onMouseover"
    @mouseleave="onMouseleave"
    @focusin="onFocusIn"
    @focusout="onFocusOut"
  >
    <!-- @slot Default slot for menu item content. -->
    <slot />
    <div
      v-if="$slots.submenu"
      v-show="showSubmenu"
      class="ep-menu__item__sub-menu"
      role="menu"
    >
      <!-- @slot submenu - Content for a submenu that appears on hover. -->
      <slot name="submenu" />
    </div>
  </div>
</template>
