// packages/epicenter-components-react/src/components/fieldset/EpFieldset.tsx
import React, { ReactNode } from 'react';

export interface EpFieldsetProps {
  /** Fieldset content */
  children?: ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** Label for the fieldset legend */
  label?: string;
}

/**
 * EpFieldset - A fieldset component for grouping form elements
 */
export const EpFieldset: React.FC<EpFieldsetProps> = ({ 
  label = '', 
  children, 
  className = '' 
}) => {
  return (
    <fieldset className={`ep-fieldset ep-fieldset--horizontal${className ? ` ${className}` : ''}`}>
      {label && <legend className="ep-fieldset__legend">{label}</legend>}
      <div className="ep-fieldset__content">
        {children}
      </div>
    </fieldset>
  );
};

EpFieldset.displayName = 'EpFieldset';

// packages/epicenter-vue-components/src/components/fieldset/EpFieldset.vue
<template>
  <fieldset class="ep-fieldset ep-fieldset--horizontal">
    <legend
      v-if="props.label"
      class="ep-fieldset__legend"
    >
      {{ props.label }}
    </legend>

    <div class="ep-fieldset__content">
      <slot />
    </div>
  </fieldset>
</template>

<script setup>
  const props = defineProps({
    label: {
      type: String,
      default: ''
    }
  })
</script>
