// packages/epicenter-components-react/src/components/date-picker/EpDatePicker.tsx
import React, {
  forwardRef,
  useEffect,
  useRef,
  useImperativeHandle,
  InputHTMLAttributes,
} from 'react';

type FlatpickrInstance = {
  destroy: () => void;
  setDate: (date: Date | string | Date[] | string[], triggerChange?: boolean) => void;
  clear: () => void;
  open: () => void;
  close: () => void;
};

export interface EpDatePickerProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'> {
  className?: string;
  dateFormat?: string;
  enableCloseOnSelect?: boolean;
  inputProps?: InputHTMLAttributes<HTMLInputElement>;
  mode?: 'single' | 'multiple' | 'range';
  onChange?: (dates: Date[], dateStr: string) => void;
  onOpen?: () => void;
  positionX?: 'auto' | 'left' | 'right';
  positionY?: 'auto' | 'above' | 'below';
  value?: string | string[];
}

export interface EpDatePickerRef {
  flatpickr: FlatpickrInstance | null;
}

export const EpDatePicker = forwardRef<EpDatePickerRef, EpDatePickerProps>(
  (
    {
      value,
      onChange,
      onOpen,
      mode = 'single',
      dateFormat = 'Y-m-d',
      positionX = 'auto',
      positionY = 'auto',
      enableCloseOnSelect = true,
      inputProps = {},
      className = '',
      ...props
    },
    ref
  ) => {
    const inputRef = useRef<HTMLInputElement>(null);
    const flatpickrRef = useRef<FlatpickrInstance | null>(null);

    useImperativeHandle(ref, () => ({
      get flatpickr() {
        return flatpickrRef.current;
      },
    }));

    useEffect(() => {

      const initFlatpickr = async () => {
        if (!inputRef.current) return;

        try {
          // Dynamic import of Flatpickr
          const module = await import('flatpickr');
          const flatpickr = module.default;

          // Import Flatpickr CSS
          await import('flatpickr/dist/flatpickr.min.css');

          // Determine position
          let position: 'auto' | 'above' | 'below' | 'auto left' | 'auto right' | 'above left' | 'above right' | 'below left' | 'below right' = 'auto';
          
          if (positionY === 'auto' && positionX === 'auto') {
            position = 'auto';
          } else if (positionY === 'auto' && positionX === 'left') {
            position = 'auto left';
          } else if (positionY === 'auto' && positionX === 'right') {
            position = 'auto right';
          } else if (positionY === 'above' && positionX === 'auto') {
            position = 'above';
          } else if (positionY === 'above' && positionX === 'left') {
            position = 'above left';
          } else if (positionY === 'above' && positionX === 'right') {
            position = 'above right';
          } else if (positionY === 'below' && positionX === 'auto') {
            position = 'below';
          } else if (positionY === 'below' && positionX === 'left') {
            position = 'below left';
          } else if (positionY === 'below' && positionX === 'right') {
            position = 'below right';
          }

          flatpickrRef.current = flatpickr(inputRef.current, {
            mode,
            dateFormat,
            position,
            clickOpens: true,
            onChange: (selectedDates, dateStr) => {
              onChange?.(selectedDates, dateStr);
              if (enableCloseOnSelect && flatpickrRef.current) {
                flatpickrRef.current.close();
              }
            },
            onOpen: () => {
              onOpen?.();
            },
            defaultDate: value,
          });
        } catch (error) {
          console.error('Failed to load Flatpickr:', error);
        }
      };

      initFlatpickr();

      return () => {
        if (flatpickrRef.current) {
          flatpickrRef.current.destroy();
          flatpickrRef.current = null;
        }
      };
    }, [mode, dateFormat, positionX, positionY, enableCloseOnSelect, onChange, onOpen, value]);

    const mergedInputProps = {
      placeholder: 'Select date...',
      ...inputProps,
      ...props,
    };

    return (
      <div className={`ep-date-picker ${className}`.trim()}>
        <input
          ref={inputRef}
          type="text"
          className="ep-date-picker__input"
          {...mergedInputProps}
        />
      </div>
    );
  }
);

EpDatePicker.displayName = 'EpDatePicker';

// packages/epicenter-vue-components/src/components/date-picker/EpDatePicker.vue
<template>
  <div class="ep-date-picker">
    <ep-input
      v-bind="computedInputProps"
      v-model="value"
    />
  </div>
</template>

<script setup>
  defineOptions({
    name: 'EpDatePicker'
  })

  import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue'
  import EpInput from '../input/EpInput.vue'

  const props = defineProps({
    enableCloseOnSelect: {
      type: Boolean,
      default: true
    },
    positionX: {
      type: String,
      default: 'left'
    },
    positionY: {
      type: String,
      default: 'auto'
    },
    dateFormat: {
      type: String,
      default: 'm/d/Y'
    },
    inputProps: {
      type: Object,
      default: () => ({})
    },
    mode: {
      type: String,
      default: 'single'
    }
  })

  const emit = defineEmits(['input', 'change', 'focus', 'blur', 'keydown'])

  const datePickerInput = ref(null)
  const value = ref('')

  const inputDefaults = {
    inputId: 'dp',
    type: 'text',
    width: '30rem',
    placeholder: 'Select a date',
    placeholderColor: 'var(--text-color)',
    iconLeft: {
      name: 'calendar',
    },
  }

  const computedInputProps = computed(() => ({
    ...inputDefaults,
    ...props.inputProps,
  }))

  let flatpickrInstance = null // Reference for dynamic import

  const initFlatpickr = async () => {
    if (!flatpickrInstance) {
      const { default: Flatpickr } = await import('flatpickr') // Dynamic import
      flatpickrInstance = Flatpickr
    }

    flatpickrInstance('#dp', {
      closeOnSelect: props.enableCloseOnSelect,
      dateFormat: props.dateFormat,
      mode: props.mode,
      position: `${props.positionY} ${props.positionX}`,
      onChange: onChange,
      onOpen: onOpen,
    })
  }

  onMounted(initFlatpickr)

  watch(
    () => [props.mode],
    initFlatpickr
  )

  const onChange = (selectedDates, dateStr) => {
    value.value = dateStr
    emit('change', selectedDates, dateStr)
  }

  const onOpen = () => {
    value.value = ''
  }

  onBeforeUnmount(() => {
    if (datePickerInput.value) {
      datePickerInput.value.flatpickrInstance?.destroy()
    }
  })
</script>
