// packages/epicenter-components-react/src/components/sign-in/EpSignIn.tsx
import React, { forwardRef, useState, FormEvent } from 'react';

import { EpButton } from '../button/EpButton';
import { EpContainer } from '../container/EpContainer';
import { EpInput } from '../input/EpInput';
import { EpLoadingState } from '../loading-state/EpLoadingState';
import { EpicenterLogo } from '../logo/EpicenterLogo';

type SignInState = 'signin' | 'loading' | 'message' | 'reset';

// Placeholder icon - replace with actual icon when available
const Eye = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
    <circle cx="12" cy="12" r="3" />
  </svg>
);

export interface EpSignInProps {
  className?: string;
  containerProps?: React.ComponentProps<typeof EpContainer>;
  onReset?: (email: string) => void;
  onSignIn?: (email: string, password: string) => void;
}

export const EpSignIn = forwardRef<HTMLDivElement, EpSignInProps>(
  ({ onSignIn, onReset, containerProps = {}, className = '', ...props }, ref) => {
    const [state, setState] = useState<SignInState>('signin');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [loadingMessage, setLoadingMessage] = useState('Signing in…');

    const buttonLabel =
      state === 'reset'
        ? 'Send password reset email'
        : state === 'loading'
        ? 'Signing in…'
        : 'Sign in';

    const footerText =
      state === 'reset' ? 'Back to sign in' : 'Forgot your password?';

    const handleButtonClick = (e: FormEvent) => {
      e.preventDefault();

      if (state === 'reset') {
        // Handle password reset
        onReset?.(email);
        return;
      }

      // Simulate loading state
      setState('loading');
      setLoadingMessage('Signing in…');

      // Simulate async sign-in
      setTimeout(() => {
        setState('signin');
        onSignIn?.(email, password);
      }, 1500);
    };

    const handleFooterClick = () => {
      if (state === 'reset') {
        setState('signin');
      } else {
        setState('reset');
      }
    };

    const renderContent = () => {
      if (state === 'loading') {
        return (
          <div className="ep-sign-in__form__message">
            <EpLoadingState
              message={{
                icon: 'oval',
                message: loadingMessage,
              }}
            />
          </div>
        );
      }

      if (state === 'message') {
        return (
          <div className="ep-sign-in__form__message">
            <p>Check your email for a password reset link</p>
          </div>
        );
      }

      return (
        <form>
          <EpInput
            id="email"
            value={email}
            onChange={setEmail}
            type="email"
            size="xlarge"
            placeholder="Email"
            data-1p-ignore
            onClear={() => setEmail('')}
          />
          {state !== 'reset' && (
            <EpInput
              id="password"
              value={password}
              onChange={setPassword}
              type="password"
              size="xlarge"
              placeholder="Password"
              iconRight={<Eye />}
              data-1p-ignore
              onClear={() => setPassword('')}
            />
          )}
          <EpButton
            className="ep-button-var--primary"
            type="submit"
            size="large"
            onClick={handleButtonClick}
          >
            {buttonLabel}
          </EpButton>
        </form>
      );
    };

    return (
      <div ref={ref} className={`ep-sign-in ${className}`.trim()} {...props}>
        <EpContainer
          {...containerProps}
          header={
            <div className="ep-sign-in__header">
              <EpicenterLogo width="140px" />
            </div>
          }
          footer={
            <div className="ep-sign-in__footer">
              <p className="text--link" onClick={handleFooterClick}>
                {footerText}
              </p>
            </div>
          }
        >
          <div className="ep-sign-in__form">{renderContent()}</div>
        </EpContainer>
      </div>
    );
  }
);

EpSignIn.displayName = 'EpSignIn';

// packages/epicenter-components-vue/src/components/sign-in/EpSignIn.vue
<script setup lang="ts">
  import { computed, ref } from 'vue'

  import EpButton from '../button/EpButton.vue'
  import EpContainer from '../container/EpContainer.vue'
  import EpInput from '../input/EpInput.vue'
  import EpLoadingState from '../loading-state/EpLoadingState.vue'
  import EpicenterLogo from '../logo/EpicenterLogo.vue'

  defineOptions({ name: 'EpSignIn' })

  type SignInState = 'signin' | 'loading' | 'message' | 'reset'

  interface LoadingMessage {
    icon: string
    message: string
  }

  const email = ref('')
  const password = ref('')
  const state = ref<SignInState>('signin')
  const loadingMessages = ref<LoadingMessage[]>([
    {
      icon: 'oval',
      message: 'Signing in…'
    }
  ])

  const buttonLabel = computed((): string => {
    return state.value === 'signin' ? 'Sign in' : 'Send reset email'
  })

  const footerText = computed((): string => {
    switch (state.value) {
      case 'signin':
        return 'Reset your password'
      case 'loading':
        return 'Signing in…'
      case 'message':
        return '< Back to Sign In'
      case 'reset':
        return '< Back to Sign In'
      default:
        return ''
    }
  })

  const signin = (): void => {
    console.log('signin')
  }

  const onButtonClick = (): void => {
    if (state.value === 'signin') {
      console.log('signin')
      state.value = 'loading'
      setTimeout(() => {
        state.value = 'signin'
      }, 2000)
    } else {
      console.log('reset')
      state.value = 'message'
    }
  }

  const onFooterClick = (): void => {
    state.value = state.value === 'signin' ? 'reset' : 'signin'
  }

  // const validateEmail = (email: string): boolean => {
  //   const emailRegex = /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/
  //   return emailRegex.test(email)
  // }
</script>

<template>
  <div class="ep-sign-in">
    <ep-container
      :style="{
        '--ep-container-width': '400px',
        '--ep-container-height': '475px',
        '--ep-container-bg-color': 'var(--interface-surface)',
        '--ep-container-content-padding': '0 3rem 6rem 3rem',
      }"
      style="box-shadow: var(--drop-shadow);"
    >
      <template #header>
        <div class="ep-sign-in__header">
          <epicenter-logo style="width: 50px;" />
        </div>
      </template>
      <div class="ep-sign-in__form">
        <ep-loading-state
          v-if="state === 'loading'"
          background-color="var(--interface-surface)"
          :messages="loadingMessages"
        />
        <div
          v-if="state === 'message'"
          class="ep-sign-in__form__message copy-block"
        >
          mail icon
          <p class="text-align--center">
            Please check your email for password<br> reset instructions
          </p>
        </div>
        <form
          v-else
          @submit.prevent="signin"
        >
          <ep-input
            id="email"
            v-model="email"
            type="email"
            size="xlarge"
            placeholder="Email"
            data-1p-ignore
            @clear="email = ''"
          />
          <ep-input
            v-if="state != 'reset'"
            id="password"
            v-model="password"
            type="password"
            size="xlarge"
            placeholder="Password"
            :icon-right="{ name: 'f-eye' }"
            data-1p-ignore
            @clear="password = ''"
          />
          <ep-button
            class="ep-button-var--primary"
            type="submit"
            size="large"
            @click="onButtonClick"
          >
            {{ buttonLabel }}
          </ep-button>
        </form>
      </div>
      <template #footer>
        <div class="ep-sign-in__footer">
          <p
            class="text--link"
            @click="onFooterClick"
          >
            {{ footerText }}
          </p>
        </div>
      </template>
    </ep-container>
  </div>
</template>
