// packages/epicenter-components-vue/src/components/loaders/EpLoaderSquares.vue
<template>
  <svg
    class="ep-loader ep-loader--squares"
    viewBox="0 0 50 50"
    aria-hidden="true"
  >
    <rect
      x="3"
      y="3"
      width="18"
      height="18"
      rx="2"
      fill="currentColor"
    >
      <animate
        attributeName="opacity"
        values="1;0.3;0.3;1"
        dur="1.6s"
        begin="0s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x="29"
      y="3"
      width="18"
      height="18"
      rx="2"
      fill="currentColor"
    >
      <animate
        attributeName="opacity"
        values="0.3;1;0.3;0.3"
        dur="1.6s"
        begin="0s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x="29"
      y="29"
      width="18"
      height="18"
      rx="2"
      fill="currentColor"
    >
      <animate
        attributeName="opacity"
        values="0.3;0.3;1;0.3"
        dur="1.6s"
        begin="0s"
        repeatCount="indefinite"
      />
    </rect>
    <rect
      x="3"
      y="29"
      width="18"
      height="18"
      rx="2"
      fill="currentColor"
    >
      <animate
        attributeName="opacity"
        values="0.3;0.3;0.3;1"
        dur="1.6s"
        begin="0s"
        repeatCount="indefinite"
      />
    </rect>
  </svg>
</template>

// packages/epicenter-components-react/src/components/loaders/EpLoaderSquares.tsx
import React from 'react'

export const EpLoaderSquares: React.FC = () => (
  <svg
    className="ep-loader ep-loader--squares"
    viewBox="0 0 50 50"
    aria-hidden="true"
  >
    <rect x="3" y="3" width="18" height="18" rx="2" fill="currentColor">
      <animate attributeName="opacity" values="1;0.3;0.3;1" dur="1.6s" begin="0s" repeatCount="indefinite" />
    </rect>
    <rect x="29" y="3" width="18" height="18" rx="2" fill="currentColor">
      <animate attributeName="opacity" values="0.3;1;0.3;0.3" dur="1.6s" begin="0s" repeatCount="indefinite" />
    </rect>
    <rect x="29" y="29" width="18" height="18" rx="2" fill="currentColor">
      <animate attributeName="opacity" values="0.3;0.3;1;0.3" dur="1.6s" begin="0s" repeatCount="indefinite" />
    </rect>
    <rect x="3" y="29" width="18" height="18" rx="2" fill="currentColor">
      <animate attributeName="opacity" values="0.3;0.3;0.3;1" dur="1.6s" begin="0s" repeatCount="indefinite" />
    </rect>
  </svg>
)

EpLoaderSquares.displayName = 'EpLoaderSquares'
