// packages/epicenter-components-vue/src/components/table/EpDatePickerFilter.vue
<script setup lang="ts">
  import { ref } from 'vue'

  interface EpDatePickerFilterProps {
    appliedFilters: Record<string, unknown>
    columnKey: string
    filterKey: string
  }

  const props = defineProps<EpDatePickerFilterProps>()

  const emit = defineEmits<{
    'update:appliedFilters': [value: Record<string, string>]
  }>()

  // Initialize selected date
  const selectedDate = ref<string>('')

  // Method to apply filter and emit event
  const applyFilter = (): void => {
    // Emit event to update applied filters in parent component
    emit('update:appliedFilters', { [props.columnKey]: selectedDate.value })
  }
</script>

<template>
  <div>
    <input
      v-model="selectedDate"
      type="date"
      @change="applyFilter"
    >
  </div>
</template>

// packages/epicenter-components-react/src/components/date-picker-filter/EpDatePickerFilter.tsx
import React, { forwardRef, ChangeEvent, CSSProperties } from 'react';

export interface EpDatePickerFilterProps {
  style?: CSSProperties;
  appliedFilters: Record<string, unknown>;
  className?: string;
  columnKey: string;
  filterKey: string;
  onChange?: (filters: Record<string, string>) => void;
  value?: string;
}

export const EpDatePickerFilter = forwardRef<
  HTMLInputElement,
  EpDatePickerFilterProps
>(
  (
    {
      appliedFilters,
      columnKey,
      value = '',
      onChange,
      className = '',
      style,
      ...props
    },
    ref
  ) => {
    const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.value;
      onChange?.({ [columnKey]: newValue });
    };

    return (
      <div className={`ep-date-picker-filter ${className}`.trim()} style={style as React.CSSProperties}>
        <input
          ref={ref}
          type="date"
          value={value || (appliedFilters[columnKey] as string) || ''}
          onChange={handleChange}
          {...props}
        />
      </div>
    );
  }
);

EpDatePickerFilter.displayName = 'EpDatePickerFilter';
