// packages/epicenter-components-react/src/components/select/EpSelect.tsx
import { ArrowDown01 } from '@ericpitcock/epicenter-icons-react/ArrowDown01.jsx'
import React, { forwardRef, ReactNode, useId, ChangeEvent } from 'react'

import { EpInputStyler } from '../input-styler/EpInputStyler'

export interface EpSelectOption {
  disabled?: boolean
  label: string
  value: string | number
}

export interface EpSelectProps extends Omit<React.SelectHTMLAttributes<HTMLSelectElement>, 'size' | 'onChange'> {
  /**
   * If true, automatically focuses the select on mount.
   * @default false
   */
  autofocus?: boolean
  /**
   * If true, disables the select element.
   * @default false
   */
  disabled?: boolean
  /**
   * If true, displays the select in error state.
   * @default false
   */
  error?: boolean
  /**
   * If true, enables error state styling and message display.
   * @default false
   */
  errorEnabled?: boolean
  /**
   * Error message to display below the select.
   */
  errorMessage?: string
  /**
   * Icon content for left side
   */
  iconLeft?: ReactNode
  /**
   * Label text for the select (used as placeholder when no option is selected).
   */
  label?: string
  /**
   * Handler called when select loses focus
   */
  onBlur?: () => void
  /**
   * Change handler for controlled select
   */
  onChange?: (value: string | number) => void
  /**
   * Handler called when select is focused
   */
  onFocus?: () => void
  /**
   * Array of option objects with 'label', 'value', and optional 'disabled' properties.
   */
  options: EpSelectOption[]
  /**
   * Placeholder text shown when no option is selected.
   * @default 'Select an option'
   */
  placeholder?: string
  /**
   * If true, makes the select read-only.
   * @default false
   */
  readonly?: boolean
  /**
   * If true, marks the select as a required field.
   * @default false
   */
  required?: boolean
  /**
   * The ID attribute for the select element.
   */
  selectId?: string
  /**
   * The size variant of the select.
   * @default 'default'
   */
  size?: 'small' | 'default' | 'large' | 'xlarge'
  /**
   * Current value of the select
   */
  value?: string | number
}

export const EpSelect = forwardRef<HTMLSelectElement, EpSelectProps>(({ 
  label = '',
  disabled = false,
  autofocus = false,
  required = false,
  selectId,
  size = 'default',
  options,
  placeholder = 'Select an option',
  value = '',
  onChange,
  errorEnabled = false,
  error = false,
  errorMessage = '',
  iconLeft,
  onBlur,
  onFocus,
  ...rest
}, ref) => {
  const generatedId = useId()
  const computedId = selectId || generatedId

  const selectClasses = [
    'ep-select',
    size !== 'default' && `ep-select--${size}`,
    disabled && 'ep-select--disabled',
    error && 'ep-select--error'
  ].filter(Boolean).join(' ')

  const handleChange = (event: ChangeEvent<HTMLSelectElement>) => {
    event.target.blur()
    onChange?.(event.target.value)
  }

  const handleBlur = () => {
    onBlur?.()
  }

  const handleFocus = () => {
    onFocus?.()
  }

  return (
    <EpInputStyler
      id={computedId}
      label={label}
      disabled={disabled}
      size={size}
      errorEnabled={errorEnabled}
      error={error}
      errorMessage={errorMessage}
      iconLeft={iconLeft}
      iconRight={<ArrowDown01 />}
      iconRightVisible={true}
      iconRightClickable={false}
    >
      <select
        id={computedId}
        ref={ref}
        className={selectClasses}
        value={value}
        onChange={handleChange}
        onBlur={handleBlur}
        onFocus={handleFocus}
        disabled={disabled}
        autoFocus={autofocus}
        required={required}
        {...rest}
      >
        {placeholder && (
          <option disabled value="">
            {placeholder}
          </option>
        )}
        {options.map((option) => (
          <option
            key={option.value}
            value={option.value}
            disabled={option.disabled}
          >
            {option.label}
          </option>
        ))}
      </select>
    </EpInputStyler>
  )
})

EpSelect.displayName = 'EpSelect'

// packages/epicenter-components-vue/src/components/select/EpSelect.vue
<script setup lang="ts">
  import ArrowDown01 from '@ericpitcock/epicenter-icons-vue/ArrowDown01'
  import { computed, ref, useId } from 'vue'

  import type { SelectOption, Size } from '../../types'
  import EpInputStyler from '../input-styler/EpInputStyler.vue'

  interface EpSelectProps {
    autofocus?: boolean
    disabled?: boolean
    error?: boolean
    errorEnabled?: boolean
    errorMessage?: string
    label?: string
    options: SelectOption[]
    placeholder?: string
    readonly?: boolean
    required?: boolean
    selectId: string
    size?: Size
  }

  const {
    selectId,
    autofocus = false,
    disabled = false,
    error = false,
    errorEnabled = false,
    errorMessage = '',
    label = '',
    placeholder = 'Select an option',
    readonly = false,
    required = false,
    size = 'default',
  } = defineProps<EpSelectProps>()

  const emit = defineEmits<{
    'update:modelValue': [value: string | number]
    blur: []
    focus: []
  }>()

  const modelValue = defineModel<string | number>({ default: '' })

  const selectClasses = computed(() => ({
    [`ep-select--${size}`]: size !== 'default',
    'ep-select--disabled': disabled,
    'ep-select--error': error,
  }))

  const computedId = ref(selectId || useId())

  const stylerProps = computed(() => ({
    id: computedId.value,
    label: label,
    disabled: disabled,
    size: size,
    errorEnabled: errorEnabled,
    error: error,
    errorMessage: errorMessage,
    iconRightClickable: false,
    iconRightVisible: true
  }))

  const onBlur = (): void => emit('blur')
  const onChange = (event: Event): void => {
    const target = event.target as HTMLSelectElement
    target.blur()
    modelValue.value = target.value
  }
  const onFocus = (): void => emit('focus')
</script>

<template>
  <ep-input-styler v-bind="stylerProps">
    <template #icon-left>
      <!-- @slot Optional icon displayed on the left side of the select -->
      <slot name="icon-left" />
    </template>
    <select
      :id="computedId"
      v-model="modelValue"
      :class="['ep-select', selectClasses]"
      :disabled="disabled"
      :autofocus="autofocus"
      :required="required"
      @blur="onBlur"
      @focus="onFocus"
      @change="onChange"
    >
      <option
        v-if="placeholder"
        disabled
        value=""
      >
        {{ placeholder }}
      </option>
      <option
        v-for="option in options"
        :key="option.value"
        :value="option.value"
        :disabled="option.disabled"
      >
        {{ option.label }}
      </option>
    </select>
    <template #icon-right>
      <ArrowDown01 />
    </template>
  </ep-input-styler>
</template>
